client/src/components/WorkspaceNav.jsx
client/src/components/workspace-nav/CollectionsList.jsx
client/src/components/workspace-nav/NavLink.jsx
client/src/components/workspace-nav/NavWorkspaceSwitch.jsx
client/src/components/workspace-nav/OrganizationMenu.jsx
client/src/styles/LibraryHeader.scss
client/src/styles/WorkspaceNav.scss
client/src/styles/style.global.scss

Adding a few more basic styles as per #10 
I had to make a few superficial changes to some components. Hopefully no conflicts

[#10] Add basic styles for main navigation menu

---

backend/src/org/akvo/dash/endpoint/activity.clj
backend/src/org/akvo/dash/endpoint/dataset.clj
backend/src/org/akvo/dash/endpoint/root.clj
backend/src/org/akvo/dash/endpoint/util.clj
backend/src/org/akvo/dash/endpoint/visualisation.clj

Also removed old testing people.csv resource.

[#61] Using endpoint/util fns were appropriate.

---

client/src/components/charts/DashAreaChart.jsx
client/src/components/charts/DashBarChart.jsx
client/src/components/charts/DashLineChart.jsx
client/src/components/charts/DashScatterChart.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/components/visualisation/configMenu/OneAxisConfigMenu.jsx
client/src/components/visualisation/configMenu/PieConfigMenu.jsx
client/src/components/visualisation/configMenu/TwoAxisConfigMenu.jsx
client/src/styles/style.global.scss

[#70] Fix 0th column visualisation bug

---

client/.eslintrc.json
client/package.json

* Remove custom no-jsx-bind rule as arrow functions are now allowed in render function

[#58] Update client deps

---

backend/src/org/akvo/dash/component/tenant_manager.clj
backend/src/org/akvo/dash/endpoint/dataset.clj
backend/src/org/akvo/dash/endpoint/files.clj
backend/src/org/akvo/dash/endpoint/library.clj
backend/src/org/akvo/dash/endpoint/root.clj
backend/src/org/akvo/dash/endpoint/visualisation.clj
backend/src/org/akvo/dash/import.clj
backend/src/org/akvo/dash/main.clj
backend/src/org/akvo/dash/middleware.clj
backend/src/org/akvo/dash/migrate.clj
backend/src/org/akvo/dash/system.clj
backend/src/org/akvo/dash/transformation.clj
backend/test/org/akvo/dash/middleware_test.clj
client/src/components/modals/createDataset/DataFileDataSourceSettings.jsx

Before this resumable uploads was tunnelled on the auth middleware. Now
the client sends the token and we validate requests.

[#83] Enforce valid JWT token on /files upload

---

backend/src/org/akvo/dash/component/tenant_manager.clj
backend/src/org/akvo/dash/endpoint/visualisation.clj
backend/test/org/akvo/dash/middleware_test.clj

Also added a type hint on the connection.

[#96] Removed isClosed connection check

---

client/index.html

[#100] Remove base href tag

---

client/src/components/dataset/ColumnHeader.jsx
client/src/components/dataset/DataTableSidebar.jsx
client/src/components/dataset/DatasetTable.jsx
client/src/components/dataset/TransformContextMenu.jsx
client/src/styles/DataTableSidebar.scss
client/src/styles/DatasetTable.scss
client/src/styles/style.global.scss

[#139] Add prototype UI for transformations

---

backend/src/org/akvo/dash/endpoint/share.clj

[#161] New share id generator

---

client/src/components/modals/CreateDataset.jsx

[#179] Disable import button if dataset name not present

---

client/package.json
client/src/components/modals/ShareEntity.jsx
client/src/styles/ShareEntity.scss

[#195] Improve sharing UI

---

client/src/components/dataset/ColumnHeader.jsx
client/src/components/dataset/DatasetTable.jsx
client/src/reducers/transform.js
client/src/reducers/transforms/sortColumn.js
client/src/styles/ColumnHeader.scss
client/src/styles/Dataset.scss
client/src/styles/DatasetTable.scss
client/src/styles/modules/colors.scss

[#198] sorted label

---

client/src/components/dataset/sidebars/TransformationLog.jsx
client/src/styles/DataTableSidebar.scss

[#192] Style transformation log entries

---

client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/styles/style.global.scss

[#183] dashboard ux

---

client/src/components/dataset/ColumnHeader.jsx
client/src/styles/ColumnHeader.scss

[#218] Truncate long column titles in dataset editor

---

backend/src/org/akvo/lumen/endpoint/public.clj

[#230] Add viewport meta tag to sharing template

---

client/src/styles/DatasetTable.scss

[#226] Clip cell contents on cell overflow

---

client/src/components/modals/createDataset/DataFileDataSourceSettings.jsx
client/src/styles/CreateDataset.scss

[#234] Add explicit error message when csv upload fails

---

backend/project.clj
backend/src/org/akvo/lumen/import/csv.clj
backend/test/org/akvo/lumen/import/csv_test.clj

[#248] Detect csv file encoding via ICU's CharsetDetector

---

client/package.json
client/src/components/dashboard/DashboardCanvasItemEditable.jsx
client/src/components/dashboard/DashboardEditor.jsx
client/src/styles/DashboardCanvasItem.scss
client/src/styles/DashboardEditor.scss

[#220] dashboard editor text entities

---

client/src/components/Library.jsx
client/src/containers/Dataset.jsx
client/src/reducers/datasets.js

[#242] Make dataset permalinks work properly

---

client/src/index.jsx

[#270] Change org name to Akvo Lumen

---

backend/resources/org/akvo/lumen/migrations_tenants/008-dashboard.up.sql
backend/src/org/akvo/lumen/endpoint/visualisation.clj

- Missing ON DELETE CASCADE added
- Switched pprint of errors to printStackTrace method.

[#273] Fix issue deleting items that is part of Dashboard

---

backend/profiles.clj.template
backend/src/org/akvo/lumen/config.clj
backend/src/org/akvo/lumen/middleware.clj
backend/src/org/akvo/lumen/system.clj
backend/test/org/akvo/lumen/middleware_test.clj
client/src/auth.js
client/webpack.config.js

[#261] Make keycloak url a config

---

client/src/components/library/LibraryListing.jsx
client/src/components/library/LibraryListingGroup.jsx
client/src/components/modals/CreateDataset.jsx

-  ~~Test plan | Unit test | Integration test~~
-  ~~Copyright header~~
-  ~~Documentation~~
* Use momentjs for parsing and formatting

[#275] Fix library date formatting in firefox and safari

---

client/src/components/WorkspaceNav.jsx
client/src/components/common/ContextMenu.jsx
client/src/styles/style.global.scss

[#284] Disable text selection for ContextMenu and WorkSpaceNav

---

client/src/components/dashboard/DashboardEditor.jsx
client/src/styles/DashboardEditor.scss

[#279] dashboard helptext

---

client/src/components/dashboard/DashboardEditor.jsx
client/src/containers/Dashboard.jsx
client/src/styles/DashboardEditor.scss

[#282] dashboard name input

---

client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/containers/Dashboard.jsx
client/src/reducers/dashboards.js
client/src/styles/DashboardEditor.scss

[#247] dashboard permalinks

---

client/src/components/dashboard/DashboardVisualisationList.jsx
client/src/styles/DashboardVisualisationList.scss

[#281] Add temp image placeholder for visualisation list

---

client/src/components/Library.jsx
client/src/components/library/LibraryListingItem.jsx
client/src/components/modals/DeleteConfirmationModal.jsx
client/src/styles/DeleteConfirmationModal.scss

[#153] delete modal

---

client/src/styles/WorkspaceNav.scss

[#293] Increase floating workspacenav zindex

---

client/src/components/charts/DashMap.jsx

[#296] Use OSM tiles via https

---

client/src/components/dashboard/DashboardEditor.jsx
client/src/containers/Dashboard.jsx

[#311] Prevent multiple API requests for the same dataset or dashboard

---

client/src/components/charts/AsyncDashChart.jsx
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardViewer.jsx
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx
client/src/index-pub.jsx
client/src/utilities/chart.js

[#300] Initial code-splitting for containers

---

.travis.yml

Since Travis now supports 9.5.

[#323] Remove custom Postgres 9.5 install

---

client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/containers/Dashboard.jsx

[#321] Only rerender dashboard items when dimensions changed

---

backend/project.clj
backend/src/org/akvo/lumen/main.clj

It should be LUMEN_FILE_UPLOAD_PATH

[#329] Make sure correct env vars are used

---

client/server.js

[#336] Update webpack proxy regex

---

RELEASE_NOTES.md

[#349] First cut on release notes for 0.2

---

backend/dev_helpers/bash/headers.sh
backend/dev_helpers/fish/functions/lumen-request.fish
backend/dev_helpers/fish/functions/set-lumen-request-token.fish

This is the hipster version, using fish and httpie.

[#326] Add fish functions to call API from terminal

---

backend/project.clj

[#346] Update backend deps

---

client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/modals/ShareEntity.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Visualisation.jsx

[#355] Improve cloning and inheriting state

---

backend/src/org/akvo/lumen/lib/public_impl.clj
backend/src/org/akvo/lumen/lib/visualisation_impl.clj

We did not unpack the response from dashboard/fetch, hence got
ring maps within the end ring response.

[#366] Fixed public shared visualisations

---

backend/dev/resources/dev.edn
backend/project.clj
backend/resources/org/akvo/lumen/system.edn

Updated clj-http, duct & postgres libs. Duct required the use of #var
before a var in the system .edn files.

[#380] Upgrade backend dependencies

---

backend/src/org/akvo/lumen/transformation/engine.clj

[#389] typo tennant -> tenant

---

doc/arch/adr-004-postgresql-for-data.md
doc/arch/adr-005-transforms-in-js.md

Spell check using hunspell(http://hunspell.github.io/) and a custom
dictionary for known acronyms

[#404] Spell check ADR

---

client/package.json
client/webpack.config.js

[#417] Add json-loader dep

---

client/src/components/dataset/ColumnHeader.jsx
client/src/components/modals/CreateDataset.jsx
client/src/components/visualisation/ConfigMenu.jsx
client/src/components/visualisation/configMenu/FilterMenu.jsx
client/src/containers/Visualisation.jsx
client/src/utilities/chart.js
client/src/utilities/vega-specs/Bar.js
client/src/utilities/vega-specs/Pie.js

[#394] Reponsive label sizes for bar charts

---

.github/PULL_REQUEST_TEMPLATE.md

[#447] Add release notes to PR template

---

.github/ISSUE_TEMPLATE.md
Makefile

[#440] First version of an issue template

---

RELEASE_NOTES.md
client/src/containers/Visualisation.jsx

[#456] Remove library navigation push on viz editor save

---

client/src/components/modals/CreateCollection.jsx
client/src/components/modals/CreateDataset.jsx
client/src/components/modals/DatasetSettings.jsx
client/src/components/modals/DeleteConfirmationModal.jsx
client/src/components/modals/ShareEntity.jsx

[#467] Add contentLabel prop to modals

---

client/src/actions/visualisation.js
client/src/containers/Visualisation.jsx

[#465] Update url with correct visualisation id on save

---

RELEASE_NOTES.md
client/src/components/charts/MapVisualisation.jsx
client/src/containers/Visualisation.jsx
client/src/utilities/chart.js

[#475] Fix maps regression

---

client/src/components/visualisation/configMenu/MapConfigMenu.jsx

[#475] Fix latitude/longitude mixup for maps

---

Makefile
RELEASE_NOTES.md
ci/service.yaml
client/default.conf
ingress/prod.yaml

Since we now have an ingress we don’t want to expose and create the
service and load balancer that way. This introduce the need for a
service definition found in ci/service.yaml.

[#420] Moved ingress to lumen repo.

---

RELEASE_NOTES.md
backend/src/akvo/lumen/transformation.clj
backend/src/akvo/lumen/transformation/engine.clj
backend/src/akvo/lumen/transformation/engine.sql
backend/test/akvo/lumen/transformation_test.clj
client/src/components/dataset/context-menus/ColumnContextMenu.jsx
doc/spec/transformations.md

[#480] Delete column transformation

---

RELEASE_NOTES.md
backend/src/akvo/lumen/transformation.clj
backend/src/akvo/lumen/transformation/engine.clj
backend/test/akvo/lumen/transformation_test.clj
client/src/components/dataset/DataTableSidebar.jsx
client/src/components/dataset/DatasetTable.jsx
client/src/components/dataset/context-menus/ColumnContextMenu.jsx
client/src/components/dataset/sidebars/RenameColumn.jsx
doc/spec/transformations.md

[#481] Rename column transformation

---

RELEASE_NOTES.md
client/src/components/visualisation/configMenu/PieConfigMenu.jsx

[#484] Fix broken Pie and Donut charts

---

RELEASE_NOTES.md
backend/project.clj

[#486] Bump akvo/resumed version to 0.2.0

---

client/default.conf

[#486] Remove unwanted header mutation

---

RELEASE_NOTES.md
backend/project.clj
backend/src/akvo/lumen/endpoint/files.clj

[#486] Use resumed snapshot release (with @jonase )

---

RELEASE_NOTES.md
client/src/containers/Dataset.jsx

[#495] Use redux to read/store the dataset in the dataset editor

---

ci/dev/deploy.sh
ci/prod/deploy.sh

[#494] Use cluster name variables in deploy script

---

RELEASE_NOTES.md
client/default.conf

[#493] Updated Nginx config

---

backend/Dockerfile
client/Dockerfile

[#505] Use explicit version on base images

---

RELEASE_NOTES.md
client/package.json
keycloak/Dockerfile

[#510] Update keycloak

---

ci/deployment.yaml
ingress/dev.yaml

Also changed ingress to point to new host

[#494] Update deployment to use keycloak url value from config

---

RELEASE_NOTES.md
client/src/utilities/chart.js

[#508] Stacked bar height

---

doc/spec/visualisations.md

[#537] Document filter spec format

---

RELEASE_NOTES.md
backend/src/akvo/lumen/import/csv.clj

[#543] Read 100kb for character encoding detection

---

client/src/components/charts/Chart.jsx
client/src/components/visualisation/ConfigMenu.jsx
client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/components/visualisation/configMenu/PieConfigMenu.jsx
client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
client/src/containers/Visualisation.jsx
client/src/containers/Visualisation/barSpecTemplate.js
client/src/containers/Visualisation/scatterSpecTemplate.js
client/src/utilities/chart.js
client/src/utilities/vega-specs/Bar.js
client/src/utilities/vega-specs/Scatter.js
doc/spec/visualisations.md

[#541] update spec format for bar and scatter visualisations

---

client/src/components/library/LibraryListingGroup.jsx

[#563] Fix reverse sort order in library listing

---

RELEASE_NOTES.md
client/src/containers/Visualisation.jsx

[#569] Prevent multiple copies of visualisations being saved on first save

---

RELEASE_NOTES.md
client/src/components/entity-editor/EntityTitleInput.jsx
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/visualisation/VisualisationHeader.jsx
client/src/containers/Visualisation.jsx

[#552] Show "Unsaved changes" while user editing visualisation title

---

client/default.conf

[#515] try_files requires two or more args

---

client/Dockerfile

[#515] Remove nginx default index.html file

---

client/Dockerfile
client/default.conf

[#515] Move index files to root location

---

RELEASE_NOTES.md
client/src/components/charts/MapVisualisation.jsx
client/src/components/visualisation/configMenu/ColorLabels.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/styles/style.global.scss
client/src/utilities/chart.js

[#561] Improve handling of blank values in visualisations with legends

---

backend/src/akvo/lumen/admin/util.clj

[#526] Make sure new tenants use TLS on db connections

---

RELEASE_NOTES.md
client/src/components/dataset/DatasetTable.jsx
client/src/components/dataset/sidebars/ChangeDataType.jsx
client/src/components/dataset/sidebars/CombineColumns.jsx
client/src/components/dataset/sidebars/DeriveColumn.jsx
client/src/components/dataset/sidebars/Filter.jsx
client/src/components/dataset/sidebars/RenameColumn.jsx
client/src/components/dataset/sidebars/SidebarControls.jsx
client/src/components/dataset/sidebars/SidebarHeader.jsx
client/src/components/dataset/sidebars/TransformationLog.jsx
client/src/styles/DataTableSidebar.scss
client/src/styles/DatasetTable.scss
client/src/styles/DeriveColumn.scss
client/src/styles/style.global.scss

[#534] More feedback on syntax error for derived column transformation

---

client/src/styles/DataTableSidebar.scss
client/src/styles/MapConfigMenu.scss
client/src/styles/MapVisualisation.scss
client/src/styles/PivotTable.scss
client/src/styles/VisualisationEditor.scss

[#524] Use "overflow:auto" instead of "overflow:scroll"

---

client/src/styles/DashboardViewerItem.scss

#622 
This is such a small change I will merge myself once checks pass

[#622] Show dashboard text entities with "pre" whitespace

---

client/src/containers/Dashboard.jsx
client/src/utilities/aggregationOnlyVisualisationTypes.js

[#623] Always request API data for pivot tables on dashboard editor load

---

client/src/components/visualisation/configMenu/BarConfigMenu.jsx

[#588] Allow x axis to be chosen before y axis in bar chart

---

client/src/components/charts/PivotTable.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/utilities/chart.js

[#638] Fix toString() regression on undefined spec properties

---

client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/styles/ConfigMenu.scss

[#635] Fix pivot editor help text

---

client/src/actions/dashboard.js
client/src/components/dashboard/DashboardHeader.jsx
client/src/containers/Dashboard.jsx

[#618] Show dashboard save status and remain in editor on save

---

client/src/components/charts/PivotTable.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/utilities/chart.js

Changes to address https://github.com/akvo/akvo-lumen/pull/634#issuecomment-284694469
should be merged after https://github.com/akvo/akvo-lumen/pull/639 has already been merged

[#621] custom row title wrap

---

client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx

[#642] Handle columnOptions not being populated before pivot api returns

---

client/src/components/charts/PivotTable.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/containers/Visualisation/pivotTableSpecTemplate.js
client/src/styles/PivotTable.scss
client/src/styles/PivotTableConfigMenu.scss
client/src/utilities/chart.js
doc/spec/visualisations.md

[#601] [#606] Add totals to pivot table with option to display values as percentages

---

client/src/components/charts/PivotTable.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/containers/Visualisation/pivotTableSpecTemplate.js
client/src/styles/PivotTable.scss
client/src/styles/PivotTableConfigMenu.scss
client/src/utilities/chart.js
doc/spec/visualisations.md

To be reviewed and merged *after* https://github.com/akvo/akvo-lumen/pull/647
#609

[#609] Limit pivot tables to max 50 columns

---

RELEASE_NOTES.md
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardVisualisationList.jsx
client/src/containers/Visualisation/pivotTableSpecTemplate.js
client/src/styles/DashboardVisualisationList.scss
client/src/styles/PivotTable.scss
client/src/utilities/chart.js

[#656] pivot tuning

---

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/components/visualisation/configMenu/PieConfigMenu.jsx
client/src/containers/Visualisation/barSpecTemplate.js
client/src/containers/Visualisation/pieSpecTemplate.js
client/src/styles/PieConfigMenu.scss
client/src/utilities/vega-specs/Bar.js
client/src/utilities/vega-specs/Pie.js
doc/spec/visualisations.md

#589 
Make the "Legend" title user-editable for pie and bar charts

[#589] Custom legend text

---

RELEASE_NOTES.md
client/src/components/charts/AsyncVisualisationViewer.jsx
client/src/components/charts/Chart.jsx
client/src/components/charts/MapVisualisation.jsx
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/components/library/LibraryListingItem.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx
client/src/styles/Chart.scss
client/src/styles/DashboardCanvasItem.scss
client/src/styles/DashboardVisualisationList.scss
client/src/styles/LibraryListing.scss
client/src/styles/MapVisualisation.scss
client/src/styles/style.global.scss
client/src/utilities/chart.js
client/src/utilities/vega-specs/Bar.js
client/src/utilities/vega-specs/Pie.js
client/src/utilities/vega-specs/Scatter.js

This is kind of a catch-all PR for all the small visual and styling tweaks that we wanted to get in pre-lisbon.
See RELEASE_NOTES for what's changed

[#582] [various] Front-end visual enhancements

---

client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/components/visualisation/configMenu/LabelInput.jsx
client/src/components/visualisation/configMenu/PieConfigMenu.jsx
client/src/styles/DashboardCanvasItem.scss
client/src/utilities/vega-specs/Pie.js
doc/spec/visualisations.md

[#663] styling issues

---

client/src/components/Library.jsx
client/src/components/library/LibrarySearch.jsx
client/src/styles/LibraryHeader.scss

#698 
RELEASE_NOTES: `Fixed bug where it was not possible to "clear" a search done in the Library view`

[#698] Add clear for library search

---

backend/src/akvo/lumen/endpoint/env.clj
client/src/auth.js
client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx

[#531] update flow-api-root -> flow-api-url

---

backend/src/akvo/lumen/lib/public_impl.clj
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/containers/Dashboard.jsx
client/src/utilities/aggregationOnlyVisualisationTypes.js

#717
RELEASE_NOTES: `Fixed bug where donut charts would not appear in the Dashboard editor.`

[#717] Treat donut charts as pie charts for dashboard and sharing

---

client/server.js

Please read #725 before reviewing or testing

Update server.js to only run on t1.lumen.localhost

---

client/src/components/modals/createDataset/SourceSelection.jsx

RELEASE_NOTES: `Use the new spelling of Akvo Flow`

[#498] Fix Akvo Flow spelling

---

RELEASE_NOTES.md

[#727] Update release notes for 0.9.0

---

ci/deployment.yaml

[#729] Update k8s deployment to use new configs (with @jonase)

---

backend/src/akvo/lumen/transformation.sql
backend/src/akvo/lumen/transformation/engine.clj
backend/test/akvo/lumen/transformation_test.clj
backend/test/akvo/lumen/transformation_test.sql

[#744] Remove undone data tables

---

backend/src/akvo/lumen/transformation/engine.clj

[#744] Drop the previous table before delivering the success promise

---

client/src/components/Library.jsx
client/src/components/library/LibraryListing.jsx

[#754] Fix visualisations not appearing in collections

---

backend/src/akvo/lumen/import/csv.clj

[#756] Sanitize url in link data source

---

client/package.json
keycloak/Dockerfile

[#760] Update keycloak to version 3.1.0.Final

---

client/src/components/DashboardModal.scss
client/src/components/WorkspaceNav.jsx
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/dataset/DatasetControls.jsx
client/src/components/dataset/DatasetHeader.jsx
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/library/LibraryListingItem.jsx
client/src/components/modals/createDataset/SourceSelection.jsx
client/src/components/visualisation/VisualisationHeader.jsx
client/src/components/visualisation/configMenu/ToggleInput.scss
client/src/styles/style.global.scss

[#462] Grey out not implemented features

---

client/src/auth.js

[#801] set checkLoginIframe to false

---

backend/src/akvo/lumen/transformation/engine.clj
backend/test/akvo/lumen/transformation_test.clj

[#808] Relax column name constraints in transformations

---

.gitignore
ci/deployment.yaml.template
ci/dev/deploy.sh
ci/prod/deploy.sh

Enables changes to container env to be picked up.

[#615] Apply K8s deployment on new deployment.

---

circle.yml
client/Dockerfile
client/package-lock.json

[#857] Update to latest Node.js version

---

client/src/components/entity-editor/EntityTitleInput.jsx
client/src/components/entity-editor/EntityTypeHeader.scss

[#804]Title is now clearly showing that its editable

---

client/src/components/library/LibraryListing.scss
client/src/components/library/LibraryListingItem.jsx

[#890] Use visualisation icons in library view

---

client/src/components/library/LibraryListing.scss

[#762] Prevent bulk action menu covering last item in list

---

client/src/components/library/LibraryListing.jsx
client/src/components/library/LibraryListing.scss

[#795] Show help text when no search results

---

client/src/components/library/LibraryListing.jsx

[#795] Fix bug where two "no results" messages show

---

README.md

[892] Added a logo and a thank you note to README.

---

ci/deployment.yaml

[#729] Remove Flow report database env var

---

client/src/components/modals/ShareEntity.jsx
client/src/components/modals/ShareEntity.scss

[#818] Fix share modal regression

---

client/src/components/entity-editor/EntityTypeHeader.scss

[#804] Fix header title input size

---

client/src/components/Library.jsx
client/src/components/library/LibraryListing.jsx
client/src/components/library/LibraryListingGroup.jsx
client/src/components/library/LibraryListingItem.jsx

[#813] Use real links for entities in Library view

---

client/src/components/library/LibraryHeader.scss
client/src/components/library/LibraryListing.scss

[#774] Minor styling fixes

---

client/src/components/modals/DeleteCollection.jsx

[#818] Fix "delete collection" modal bug

---

client/src/components/library/LibraryListing.scss
client/src/components/library/LibraryListingGroup.jsx
client/src/components/library/LibraryListingItem.jsx

[#789] Hide entity checkboxes by default

---

client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardHeader.jsx
client/src/containers/Dashboard.jsx

[#769] Make dashboard header title editable

---

backend/src/akvo/lumen/admin/add_tenant.clj

[#875] Fix add-tenant regression

---

client/src/components/modals/ShareEntity.jsx

Fix sharing modal regression in work on #818

[#818] Fix sharing regression

---

client/src/components/charts/MapVisualisation.scss
client/src/components/library/LibraryHeader.scss
client/src/components/modals/ModalHeader.scss
client/src/components/users/ConfirmUserAction.jsx
client/src/components/visualisation/configMenu/ButtonRowInput.scss

[#917] small tweaks

---

backend/resources/akvo/lumen/email/create_new_account_and_invite_to_tenant.txt
backend/resources/akvo/lumen/email/invite_to_tenant.txt

* Text in user invitation emails has been improved

[#882] Modified user invitation email text

---

RELEASE_NOTES.md

Issue/925 release 0.11.0

---

circle.yml

[#927] Remove Keycloak container build optimisations

---

ci/prod/deploy.sh

[#929] Use correct path to deployment template in production

---

client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx

[#934] Add require for Select component style file

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#787] Don't show datatype in map legend

---

client/src/utilities/chart.js
client/src/utilities/vega-specs/Scatter.js

[#788] Show bucket column name in hover text for scatter chart

---

RELEASE_NOTES.md
backend/resources/akvo/lumen/email/create_new_account_and_invite_to_tenant.txt
backend/resources/akvo/lumen/email/invite_to_tenant.txt
backend/src/akvo/lumen/lib/user.clj
backend/src/akvo/lumen/lib/user_impl.clj

[#881] Invitation emails use email as origin reference

---

client/src/auth.js

[#801] Redirect to login page in case of token refresh failure

---

backend/src/akvo/lumen/import.clj

[#947] Make sure imported columns is a vector

---

backend/src/akvo/lumen/import/flow.clj

[#946] Render caddisfly responses as json strings

---

backend/src/akvo/lumen/import.clj

Bug found by @janagombitova and @nadiagorchakova

[#947] Allow new columns when updating a dataset

---

client/src/components/WorkspaceNav.jsx
client/src/components/WorkspaceNav.scss

[#907] Remove hamburger menu

---

.github/PULL_REQUEST_TEMPLATE.md

[#974] Simplify PR template

---

client/index.ejs

[#953] Add support hero widget

---

client/src/components/library/LibraryHeader.jsx
client/src/components/library/LocationIndicator.jsx
client/src/components/visualisation/configMenu/ToggleInput.jsx
client/src/containers/App.jsx

If label and labelId is undefined we fallback to empty string.

[#1007] ToggleInput use empty string as fallback

---

backend/src/akvo/lumen/admin/remove_tenant.clj

`RELEASE_NOTES`: Update remove-tenant script to cleanup keycloak

[#874] Cleanup keycloak as part of remove-tenant script

---

client/src/components/visualisation/VisualisationConfig.scss

[#828] Make text input background true white

---

client/src/components/common/Header.jsx
client/src/components/common/Header.scss
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/entity-editor/EntityTypeHeader.scss

`RELEASE_NOTES (refactor)`: Refactor client headers

[#1079] Refactor EntityTypeHeader to use new Header Component

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#1082] Hide "Counters" toggle in map editor

---

backend/resources/akvo/lumen/system.edn
backend/src/akvo/lumen/auth.clj
backend/src/akvo/lumen/component/tenant_manager.clj
backend/src/akvo/lumen/endpoint/healthz.clj
client/default.conf
client/server.js

`RELEASE_NOTES` Add /healthz check

[#1091] Add healthz check

---

client/src/components/transformation/merge/SelectDataset.jsx

[#1078] Sort dataset selection alphabetically

---

backend/src/akvo/lumen/admin/util.clj

`RELEASE NOTES (bug)` Fix broken add-tenant script

[#1104] Fix typo in format string

---

ci/deployment.yaml.template
ci/dev/deploy.sh
ci/redis-master-windshaft.yaml
ci/service.yaml
circle.yml

* Updated cluster name in CI script
* Added limits/requests for CPU as the new cluster is a little bit more busy
* Added a service.yaml file as none was available

[#1106] Deploy to new test cluster

---

ci/deployment.yaml.template
ci/dev/deploy.sh
ci/prod/build_containers.sh
ci/prod/deploy.sh

Adding Windshaft to the deployment template and deploying the Redis service to production

[#1108] Deploy Windshaft to production

---

Makefile
client/default.conf

[#1114] Add /maps routing to client Nginx

---

client/default.conf

[#1114] Adding trailing slash to maps Nginx directive

---

client/src/components/visualisation/VisualisationEditor.jsx

[#1122] Fetch new tiles when custom colors changed in maps editor

---

client/src/components/visualisation/configMenu/MapConfigMenu.jsx

[#1118] Default to geopoint column for map when there is only 1

---

client/src/components/dataset/context-menus/ColumnContextMenu.jsx

[#1119] Fix context menu for geopoint columns in Dataset editor

---

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/components/visualisation/configMenu/FilterMenu.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/components/visualisation/configMenu/LineConfigMenu.jsx
client/src/components/visualisation/configMenu/PieConfigMenu.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
client/src/utilities/utils.js

[#1128] Filter out geopoint columns from select menus where they don't make sense

---

client/src/components/charts/MapVisualisation.jsx

[#1132] Set max zoom of 12 for auto bounds fit

---

client/src/components/charts/MapVisualisation.scss

[#1130] legend position

---

backend/src/akvo/lumen/lib/aggregation/filter.clj

- Bugfix
```Fix filter regression```

[1144] Fix filter regression

---

backend/src/akvo/lumen/lib/aggregation/filter.clj

[1144] Quote texts in is filter

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#1150] Change null checks to catch undefined

---

backend/src/akvo/lumen/import/common.clj
backend/src/akvo/lumen/transformation/geo.clj

[#1152] Index geo columns on import and 'derive geo column' transform

---

windshaft/Dockerfile

[#1166] Update Akvo maps version

---

backend/src/akvo/lumen/admin/remove_tenant.clj

[#1156] Update doc string on remove-tenant script

---

client/src/components/common/ContextMenu.jsx
client/src/components/common/ContextMenuItem.jsx
client/src/components/dashboard/DashboardVisualisationList.jsx
client/src/components/dataset/ColumnHeader.jsx
client/src/components/dataset/DatasetControls.jsx
client/src/components/dataset/sidebars/GenerateGeopoints.jsx
client/src/components/dataset/sidebars/SidebarControls.jsx
client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/components/visualisation/configMenu/LayerMenuItem.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/components/visualisation/configMenu/SelectInput.jsx

- This pull request is necessary to continue with our tests with puppeteer, using the new tenant:
https://lumencitest.akvotest.org

[#1171] Add data-test-id's needed for the tests

---

client/default.conf

Plus do not log the whole layer group in the Nginx logs

[#1179] Allow just GET requests to Windshaft 

---

backend/src/akvo/lumen/lib/public_impl.clj

[#1187] Cast to bool in merge sort function

---

client/src/components/modals/ShareEntity.jsx
client/src/components/modals/ShareEntity.scss

RELEASE_NOTES: `Show iframe embed code in the share dialog for visualisations and dashboards`

[#1201] Show embed code in share dialog

---

backend/src/akvo/lumen/lib/visualisation/map_config.clj

[#1205] Use double quotes for unique values in cartocss

---

backend/src/akvo/lumen/lib/dataset_impl.clj
backend/src/akvo/lumen/lib/visualisation.sql
client/src/actions/dataset.js
client/src/components/modals/DeleteConfirmationModal.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#1209] Naive cascading delete for maps

---

backend/src/akvo/lumen/lib/visualisation/map_config.clj

[#1212] Round aggregation to 5 places

---

client/src/components/dashboard/DashboardCanvasItem.jsx

[#1219] Add undefined check

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx

[#1234] Prevent styling geom column resetting when styling column changes

---

client/src/components/visualisation/VisualisationEditor.jsx

#1229 
This is just an effort to make the previous change more documented

[#1229] Refactor render logic to be less confusing

---

backend/project.clj
backend/src/akvo/lumen/transformation/change_datatype.clj
backend/src/akvo/lumen/transformation/engine.sql
backend/src/akvo/lumen/transformation/geo.clj

[#1175] Fix issue with undo

---

client/src/components/charts/MapVisualisation.jsx
client/src/components/visualisation/VisualisationEditor.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/containers/Raster.jsx
client/src/containers/Visualisation/mapLayerSpecTemplate.js

[#1256] raster UI improvements

---

backend/src/akvo/lumen/lib/raster_impl.clj

- Instead of loading all the SQL file in memory we stream the response from `raster2pgsql` to the running JVM
- It's now a bit slower (but safer?) to load the data since we execute one INSERT statement per line

[#1161] Stream response from raster2pgsql

---

client/src/containers/Main.jsx
client/src/containers/Main.scss
client/src/reducers/loadStatus.js
client/src/reducers/rootReducer.js

[#1240] Show message when user unauthorized for tenant

---

backend/src/akvo/lumen/lib/visualisation/map_metadata.clj

[#1215] Fix out-of-date column titles bug

---

backend/src/akvo/lumen/transformation/engine.clj

[#1232] Log failed transformations

---

backend/src/akvo/lumen/lib/aggregation/pivot_impl.clj
client/src/utilities/chart.js

[#1267] Fix usage of dates as columns in pivot table

---

client/src/components/charts/MapVisualisation.jsx
client/src/components/visualisation/VisualisationEditor.jsx
client/src/utilities/utils.js

[#1288] Fix broken maps

---

client/Dockerfile

[#1295] Nginx container version

---

backend/src/akvo/lumen/lib/visualisation/map_metadata.clj
client/src/components/charts/MapVisualisation.jsx
client/src/utilities/chart.js

[#1293] Raster min max

---

client/vendor/sourcemapped-stacktrace.js

#1744
@gabemart needed to add it first in separate PR so that it could be served from develop branch

#1744 added sourcemapped-stacktrace 3rd party lib

---

client/src/components/dataset/DatasetControls.jsx
client/src/components/dataset/DatasetControls.scss
client/src/components/dataset/DatasetTable.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx
client/src/translations/en.json
client/src/translations/es.json
client/src/translations/fr.json

Add a visualize button to dataset editor #998

---

client/e2e-test/script-test.js

Puppeteer sourcemaps from cdn to GitHub

---

backend/src/akvo/lumen/lib/visualisation/map_config.clj

* Reduce the visual weight of the borders of map points

[#1304] Reduce point border prominence in maps

---

client/src/components/visualisation/VisualisationEditor.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#1313] Fix maps

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/utilities/utils.js

Raster datasets always appear at bottom of map layer dataset menu #1307

---

client/src/components/library/LibraryListing.scss
client/src/components/library/LibraryListingItem.jsx

Dataset context menu unreachable #1279

Dataset context menu unreachable #1279

---

backend/src/akvo/lumen/lib/public_impl.clj

[#1316] Fix sharing of all-raster maps

---

client/src/index-pub.ejs
client/webpack.config.dev.js
client/webpack.config.prod.js

Help button in publicly shared visualisations and dashboards #1012

---

backend/src/akvo/lumen/transformation.sql
backend/src/akvo/lumen/transformation/engine.clj

Dating of changed maps and datasets in Lumen library #1294

---

client/src/components/dataset/DatasetTable.jsx
client/src/containers/Dataset.jsx
client/src/containers/Notification.scss

Transformation fails silently #1284

---

backend/src/akvo/lumen/lib/dataset.sql
backend/src/akvo/lumen/lib/dataset_impl.clj
client/src/components/charts/Chart.jsx
client/src/components/charts/Chart.scss
client/src/components/charts/MapVisualisation.jsx
client/src/components/charts/MapVisualisation.scss
client/src/components/charts/PivotTable.jsx
client/src/components/charts/PivotTable.scss
client/src/styles/style.global.scss
client/src/translations/en.json
client/src/translations/es.json
client/src/translations/fr.json
client/src/utilities/chart.js

Add date when last updated to asset metadata #1017

---

client/src/actions/collection.js
client/src/actions/dashboard.js
client/src/actions/dataset.js
client/src/actions/raster.js
client/src/actions/visualisation.js
client/src/components/Library.jsx
client/src/components/modals/CreateDataset.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Visualisation.jsx

Improvements to lumen collections ui #1036

---

client/src/components/common/Header.jsx
client/src/components/common/Header.scss
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardEditor.scss
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/entity-editor/EntityTypeHeader.scss
client/src/components/visualisation/ConfigMenu.jsx
client/src/components/visualisation/VisualisationHeader.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Visualisation.jsx

Prioritize the placement of save in the visualization editor #825

---

client/src/actions/dataset.js
client/src/components/charts/AsyncVisualisationViewer.jsx
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dataset/DatasetControls.jsx
client/src/components/library/LibraryListing.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Raster.jsx
client/src/containers/Visualisation.jsx
client/src/reducers/datasets.js

Introduce a spinner when data is loading #1250

---

client/src/index-pub.jsx

shared dashboards and visualizations dont show with an Intl error #1338

---

backend/src/akvo/lumen/lib/public_impl.clj

[#1340] Add non-row dataset data to share endpoints

---

client/src/components/common/Header.scss
client/src/components/dashboard/DashboardHeader.jsx
client/src/containers/Dashboard.jsx

[#1351] Disable save button when dashboard has no title

---

client/src/polyfill/polyfill.js

Object.values undefined on old browsers #1346

---

ci/deploy.sh
ci/flip-blue-green-deployment.sh

updated cluster name in ci scripts

Deploy to new Prod cluster

---

backend/project.clj

Update backend deps

---

keycloak/Dockerfile

Changed dev KeyCloak image to 3.4.3. No code changes needed.

[#1385] Upgrade Keycloak to 3.4.3 version

---

backend/src/akvo/lumen/transformation/change_datatype.clj
backend/src/akvo/lumen/transformation/combine.clj
backend/src/akvo/lumen/transformation/delete_column.clj
backend/src/akvo/lumen/transformation/derive.clj
backend/src/akvo/lumen/transformation/engine.clj
backend/src/akvo/lumen/transformation/filter_column.clj
backend/src/akvo/lumen/transformation/rename_column.clj
backend/src/akvo/lumen/transformation/text.clj
backend/src/akvo/lumen/update.clj
backend/test/akvo/lumen/transformation/engine_test.clj

in relation of removing the pervasive use of try/catch code to manage control flow
https://www.google.es/search?q=exceptions+as+control+flow&oq=exceptions+as+control+flow+&aqs=chrome..69i57j69i60j0l4.9894j0j7&sourceid=chrome&ie=UTF-8

Centralize use of try-catch exception in engine/apply-operation

---

client/src/components/common/NavigationPrompt.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx

No prompt for unsaved changes #878

---

backend/test/akvo/lumen/import/csv_test.clj

wrapping in try/catch we avoid assert in exception case, so removing the try/cacth block :)

Update csv_test.clj, fix silent failing test case

---

client/e2e-test/script-test.js
client/src/actions/dashboard.js
client/src/actions/dataset.js
client/src/actions/visualisation.js
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/dataset/DatasetHeader.jsx
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/visualisation/ConfigMenu.jsx
client/src/components/visualisation/VisualisationHeader.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/constants/time.js
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx
client/src/translations/en.json

Renaming in maps editor #1087

---

client/e2e-test/script-test.js
client/src/components/charts/PivotTable.jsx

Autosave fixes #1087

---

client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Visualisation.jsx
client/src/reducers/visualisations.js

#1087 autosave race conditions fix

---

client/src/containers/Visualisation.jsx

#1087 fixed "create visualization" button in dataset

---

client/src/components/modals/CreateDataset.jsx

Disable 'Next' button until file was added #1409

---

client/src/components/common/ContextMenuItem.jsx
client/src/components/dataset/DatasetTable.jsx
client/src/components/dataset/context-menus/ColumnContextMenu.jsx

Dropdown options not visible for the last column in the dataset #976

---

client/src/index-pub.jsx

#1046 dashboard auth error message force rerender

---

client/src/components/visualisation/VisualisationEditor.jsx

[#1416] Fix base layer not updating

---

client/src/index-pub.jsx

when entering correct dashboard password, error alert flashes briefly #1433

---

backend/src/akvo/lumen/migrate.clj

**Tenant db-uri-connection is not properly retrieved**
`dev> (rollback)`
currently getting ...
```
SQLException No suitable driver found for MxTiCr0Vcw6m78X3ChEDoHbDk7GxOWf8eQBcJ69imThODU4jIPFkM6UxPZb7aUJtp+GSaumwPnTpDmRSPNrYDaE+yBgr6tdgMKWgoQJ6tkA=
java.sql.DriverManager.getConnection (DriverManager.java:689)
java.sql.DriverManager.getConnection (DriverManager.java:270)
clojure.java.jdbc/get-connection (jdbc.clj:320)
clojure.java.jdbc/get-connection (jdbc.clj:226)
clojure.java.jdbc/get-connection (jdbc.clj:281)
clojure.java.jdbc/get-connection (jdbc.clj:226)
ragtime.jdbc/get-table-names (jdbc.clj:28)
ragtime.jdbc/get-table-names (jdbc.clj:25)
ragtime.jdbc/table-exists? (jdbc.clj:32)
ragtime.jdbc/table-exists? (jdbc.clj:31)
ragtime.jdbc/ensure-migrations-table-exists (jdbc.clj:35) …
```

Fix rolback functionality

---

backend/project.clj

upgrade hikaricp dep version

---

backend/dev/resources/dev.edn
backend/resources/akvo/lumen/system.edn
backend/src/akvo/lumen/endpoint/env.clj
client/src/actions/dataset.js
client/src/auth.js
client/src/components/Library.jsx
client/src/components/modals/CreateDataset.jsx
client/src/components/modals/ShareEntity.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Raster.jsx
client/src/containers/Transformation.jsx
client/src/containers/Visualisation.jsx
client/src/index-pub.jsx
client/src/index.jsx
client/src/utilities/analytics.js

@iperdomo need to check Im doing things correctly on the backend for the env vars
@gabemart please check that you agree with how its been implemented

Setting up analytics (Piwik) #675

---

client/src/components/charts/MapVisualisation.jsx
client/src/components/charts/MapVisualisation.scss

[#1369] Suppress context menu for images in map popups

---

client/src/components/Library.jsx
client/src/components/common/Header.jsx
client/src/components/entity-editor/EntityTypeHeader.jsx
client/src/components/library/LibraryListingItem.jsx
client/src/containers/Dataset.jsx

[#1422] Use router.goBack for Header back button

---

setup-env.sh

This makes this step of the setup more easily automateable, e.g. from an IDE

Add setup-env.sh script o set HOST_UID/HOST_GID in .env

---

client/src/components/charts/PieChart.jsx

[#1454] Pie percentage labels

---

client/src/components/charts/ScatterChart.jsx

[#1459] Show nonzero origin ticks for scatter chart

---

client/src/components/visualisation/VisualisationEditor.jsx

[#1458] Fix bug where cannot switch viz type

---

client/src/components/charts/ScatterChart.jsx

[#1462] Scatter tooltip

---

client/src/components/charts/SimpleBarChart.jsx
client/src/components/charts/StackedBarChart.jsx

[#1471] Abbreviate numbers over 10k in bar chart axis

---

backend/src/akvo/lumen/lib/public_impl.clj

Fix`donut` visualisation dispatching value

---

client/src/containers/IntlWrapper.jsx

[#1485] Load locales for numeral

---

backend/src/akvo/lumen/lib/aggregation.clj
backend/src/akvo/lumen/lib/public_impl.clj

Remove aggregation/query `donut` support

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx

unresponsive map layer due to new UI translations #1483

---

client/src/components/charts/LineChart.jsx

[#1488] Fix line y axis abbr bug

---

client/src/components/charts/StackedBarChart.jsx

[#1492] increase margin for stacked bar x labels

---

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

[#1495] Fix typo

---

client/src/components/charts/StackedBarChart.jsx

[#1498] Show x axis label for stacked bar chart

---

client/src/components/visualisation/configMenu/LayerMenu.jsx
client/src/components/visualisation/configMenu/LayerMenuItem.jsx
client/src/components/visualisation/configMenu/LayerMenuItem.scss
client/src/components/visualisation/configMenu/MapConfigMenu.jsx

[#1328] Allow changing the order of map layers

---

backend/src/akvo/lumen/lib/dataset.clj
backend/src/akvo/lumen/lib/dataset_impl.clj
backend/src/akvo/lumen/lib/public_impl.clj

[#1505] Fetch dataset metadata more efficiently

---

backend/src/akvo/lumen/endpoint/dataset.clj
client/src/actions/dataset.js
client/src/actions/visualisation.js
client/src/containers/Dashboard.jsx
client/src/containers/Visualisation.jsx

[#1507] Add endpoint to fetch datasets without rows

---

client/src/components/charts/MapVisualisation.jsx

[#1509] Check layer metadata exists before access raster metadata

---

client/src/components/library/LibraryListingItem.jsx

#778 fixed library assets bug when dataset source null

---

client/src/domain/entity.js

#778 removed undefined author library meta

---

client/src/polyfill/polyfill.js

[#1525] New polyfills

---

client/src/components/library/LibraryListingItem.jsx
client/src/domain/entity.js
client/src/utilities/utils.js

#778 library meta fixes 3

---

client/src/components/library/LibraryListing.scss
client/src/components/library/LibraryListingItem.jsx
client/src/components/visualisation/configMenu/LayerConfigMenu.jsx

Hover area is not equal to hit area in the Lumen library #1401

---

client/src/components/common/LumenBranding.jsx
client/src/components/common/LumenBranding.scss

The product link should lead to an information page #1442

---

backend/src/akvo/lumen/lib/dataset_impl.clj

[#1534] Include rows in dataset api response

---

client/src/components/visualisation/configMenu/BarConfigMenu.jsx

User defined labels do not change for Bar charts #1516

---

client/src/components/dashboard/DashboardViewer.jsx

#1513 fixed dashboard sharing issue caused by new dashboard styling

---

client/src/polyfill/polyfill.js

IE10 polyfill issues #1525

---

backend/src/akvo/lumen/lib/dataset_impl.clj
client/src/polyfill/polyfill.js

Determine asset's metadata #778   fixes

---

client/src/components/charts/Chart.jsx
client/src/components/charts/MapVisualisation.jsx
client/src/components/charts/PivotTable.jsx
client/src/components/dashboard/DashboardViewer.jsx
client/src/components/dashboard/DashboardViewer.scss
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/utilities/chart.js

#1513 dashboard redesign fixes

---

client/src/polyfill/polyfill.js

#1525 debugging polyfills

---

client/src/components/charts/Chart.jsx
client/src/components/charts/MapVisualisation.jsx
client/src/components/charts/PivotTable.jsx
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardEditor.scss
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/components/dashboard/DashboardVisualisationList.jsx
client/src/components/dashboard/DashboardVisualisationList.scss
client/src/utilities/chart.js

Date should be the same across the dashboard editor #1554

---

client/src/components/dashboard/DashboardVisualisationList.jsx
client/src/components/library/LibraryListingItem.jsx

Inconsistency in updating assets metadata in library #1549

---

client/src/app.jsx
client/src/polyfill.js

#1525 cleaning up console.logs

---

NEW_TENANT.md
backend/src/akvo/lumen/admin/add_tenant.clj

Add documentation on how to create new tenant #1514

---

NEW_TENANT.md

Add more details about how retrieving values [#1514]

---

backend/src/akvo/lumen/transformation/combine.sql
backend/test/akvo/lumen/transformation_test.clj
backend/test/resources/name.csv

Solution related to https://github.com/akvo/akvo-lumen/issues/1517#issuecomment-407676335

Use `concat` instead of `||` in sql update. Close #1517

---

backend/resources/akvo/lumen/system.edn
backend/src/akvo/lumen/config.clj

Adapt backend env vars

---

backend/src/akvo/lumen/lib/visualisation/map_config.clj
backend/test/akvo/lumen/lib/visualisation/maps_test.clj

based on https://stackoverflow.com/a/7471183/1074389
and https://docs.oracle.com/javase/7/docs/api/java/awt/Color.html#RGBtoHSB(int,%20int,%20int,%20float[])

[#1590] Add proper color conversion impl

---

client/package.json
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardCanvasItemEditable.jsx
client/src/components/dashboard/DashboardEditor.jsx
client/src/translations/en.json
client/src/translations/es.json
client/src/translations/fr.json

Canvas: select & bring recently added item into view #940

---

client/package.json

#1594 bumped version react window size

---

client/src/components/charts/Legend.jsx
client/src/components/charts/StackedBarChart.jsx

Colour for 'no data' in legend and graph itself do not match #1537

---

backend/src/akvo/lumen/transformation/change_datatype.clj
backend/src/akvo/lumen/transformation/combine.clj
backend/src/akvo/lumen/transformation/delete_column.clj
backend/src/akvo/lumen/transformation/derive.clj
backend/src/akvo/lumen/transformation/engine.clj
backend/src/akvo/lumen/transformation/filter_column.clj
backend/src/akvo/lumen/transformation/geo.clj
backend/src/akvo/lumen/transformation/merge_datasets.clj
backend/src/akvo/lumen/transformation/rename_column.clj
backend/src/akvo/lumen/transformation/reverse_geocode.clj
backend/src/akvo/lumen/transformation/sort_column.clj
backend/src/akvo/lumen/transformation/text.clj
backend/src/akvo/lumen/update.clj

Change defmulti transformation.engine/apply-operation first argument to map type

---

client/src/components/dashboard/DashboardCanvasItemEditable.jsx
client/src/components/dashboard/DashboardCanvasItemEditable.scss

#1576 dashboard rich text fixes

---

client/e2e-test/Dockerfile

Reduce the verbosity of Cypress install #1582

---

client/package-lock.json
client/src/components/charts/PivotTable.jsx

Update Lodash client deps #1601

---

client/src/components/dashboard/DashboardEditor.jsx

Canvas: handle empty spaces after moving elements around #1578

---

client/src/app-pub.jsx
client/src/components/AdminNav.scss
client/src/components/Library.scss
client/src/components/WorkspaceNav.scss
client/src/components/charts/MapVisualisation.scss
client/src/components/charts/Tooltip.scss
client/src/components/common/ContextMenu.scss
client/src/components/common/Header.scss
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardCanvasItemEditable.jsx
client/src/components/dashboard/DashboardCanvasItemEditable.scss
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardEditor.scss
client/src/components/dashboard/DashboardViewerItem.scss
client/src/components/dashboard/DashboardVisualisationList.scss
client/src/components/dataset/sidebars/TransformationLog.scss
client/src/components/entity-editor/EntityTypeHeader.scss
client/src/components/library/LibraryListing.scss
client/src/components/visualisation/ConfigMenu.scss
client/src/components/visualisation/configMenu/ColorLabels.scss
client/src/components/visualisation/configMenu/FilterMenu.jsx
client/src/components/visualisation/configMenu/FilterMenu.scss
client/src/components/visualisation/configMenu/LayerConfigMenu.scss
client/src/components/visualisation/configMenu/LayerMenu.scss
client/src/components/visualisation/configMenu/UniqueValueMenu.scss
client/src/components/workspace-nav/CollectionsList.jsx
client/src/components/workspace-nav/CollectionsList.scss
client/src/styles/reset.global.scss

#1576 dashboard rich text fixes 2

---

client/src/translations/en.json

fix english translation

---

backend/src/akvo/lumen/lib/multiple_column.clj
backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj

Improvements on  extract-multiple-values functionality [backend]

---

backend/src/akvo/lumen/lib/multiple_column.clj

Add "unit" to caddisfly "name" response [#1626]

---

client/src/components/charts/MapVisualisation.jsx

Use proper visualisable metadata in legend [client] [#1579]

---

client/src/components/library/LibraryListingItem.jsx
client/src/domain/entity.js

Add UI fixes to LibraryListingItems 

---

client/src/components/dashboard/DashboardCanvasItemEditable.jsx
client/src/components/dashboard/DashboardCanvasItemEditable.scss
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/dashboard/DashboardViewerItem.jsx
client/src/components/dashboard/DashboardViewerItem.scss

rich text editor fixes #1576

---

client/src/components/common/LumenBranding.scss

Increment z-index over maximum found in lumen css

---

client/src/components/dashboard/DashboardViewerItem.jsx

Maps show small on shared link #1632

---

client/src/domain/entity.js

Revert isUpdatable logic [#1562]

---

client/src/domain/entity.js

Revert isUpdatable logic [#1636]

---

windshaft/Dockerfile

[#1642] Upgrade to latest Windshaft image

---

backend/src/akvo/lumen/dataset.sql

Relates #1638 
Setting up changes for dark-live deployments (to be merged before https://github.com/akvo/akvo-lumen/pull/1644 )

Select data_source.spec instead of dataset.source [#1638]

---

backend/src/akvo/lumen/dataset.sql

Fix query [#1638]

---

client/src/domain/entity.js

Disable *again* update for datasets coming from Data files [#1562]

---

client/src/components/dataset/DatasetTable.jsx

Dataset initial view has a right blank empty rectangle #1658

---

client/src/components/dashboard/DashboardCanvasItemEditable.scss

Enhance text editor for dashboards #1576

---

client/src/components/charts/PieChart.jsx

Pie chart label not shown #1558

---

backend/src/akvo/lumen/transformation/derive.clj
backend/test/akvo/lumen/transformation/derive_test.clj

Support hyphens in row names in update dataset

---

backend/project.clj
backend/src/akvo/lumen/transformation/derive.clj
backend/test/akvo/lumen/transformation/derive_test.clj

Improve derive/parse-row-object-references impl and test coverage

---

client/src/components/charts/Chart.jsx
client/src/components/visualisation/configMenu/BarConfigMenu.jsx

#1655 bar labels toggle fixes

---

client/src/components/charts/SimpleBarChart.jsx

bar labels toggle fixes 4 #1655

---

client/src/components/visualisation/VisualisationEditor.jsx
client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/containers/Visualisation.jsx

Changing dataset on existing chart crashes app #1679

---

client/package.json
client/src/components/charts/Chart.stories.jsx
client/src/components/charts/SimpleBarChart.jsx
client/src/containers/Visualisation/barSpecTemplate.js
client/src/utilities/color.js

Add Show labels toggle for bar charts #1655

---

client/src/components/charts/Chart.jsx
client/src/components/charts/Chart.stories.jsx
client/src/components/charts/SimpleBarChart.jsx
client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/containers/Visualisation/barSpecTemplate.js

Bar chart value labels do not fit in the bar #1682

Bar chart Show label toggle turned on for existing bars #1685

---

backend/src/akvo/lumen/component/caddisfly.clj

Fix hardcoded url in caddisfly-dev component 

---

backend/src/akvo/lumen/component/caddisfly.clj

Cast to boolean pre-conditions

---

client/src/components/charts/LineChart.jsx
client/src/components/charts/MapVisualisation.jsx
client/src/components/charts/PieChart.jsx
client/src/components/charts/PivotTable.jsx
client/src/components/charts/ScatterChart.jsx
client/src/components/charts/SimpleBarChart.jsx
client/src/components/charts/StackedBarChart.jsx
exporter/index.js

#952 download option fixes 1

---

client/e2e-test/cypress/integration/index.spec.js
client/src/components/charts/PivotTable.jsx
client/src/components/common/ConfigMenu/ConfigMenuSectionOptionSelect.jsx
client/src/components/dataset/DatasetTable.jsx
client/src/components/visualisation/configMenu/DatasetMenu.jsx
client/src/containers/Visualisation.jsx

"Create visualization" button in dataset page is broken #1700

---

client/package.json
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/visualisation/VisualisationHeader.jsx

#952 hide export button

---

client/src/components/charts/Chart.jsx
client/src/components/charts/Chart.scss
client/src/components/charts/ChartLayout.jsx
client/src/components/visualisation/VisualisationViewerContainer.scss
client/src/translations/en.json

Shared visualisations load incrementally #1706

---

client/src/components/visualisation/VisualisationViewerContainer.jsx

Shared maps do not load in test #1705

---

exporter/Dockerfile
exporter/index.js

Upgrade puppeteer to 1.9.0 and use disable-dev-shm-usage

---

ci/k8s/deployment.yaml.template
windshaft/config/prod/environment.js

Add prometheus stats for maps (connect #1701)

---

exporter/index.js

Revert exporter --shm-size option

---

backend/src/akvo/lumen/transformation/merge_datasets.clj

Relates to #1715 
Tested locally using flow `uat1` test instance and its caddifly tests

Dispatch on "multiple" type in merge dataset [#1715]

---

exporter/index.js

Adapt filename title to ASCI (Connect #1723) 

---

backend/src/akvo/lumen/update.clj
client/src/components/library/LibraryListingItem.jsx

Data last updated date does not update [ui] (Connect #1678)

---

backend/resources/akvo/lumen/config.edn
backend/src/akvo/lumen/component/tenant_manager.clj

Tweak connection pools settings

---

exporter/.eslintrc
exporter/index.js
exporter/package-lock.json
exporter/package.json

Logging in and out makes exports fail #1717

---

backend/src/akvo/lumen/auth.clj

Remove logs

---

backend/dev/resources/dev.edn
backend/dev/src/dev.clj
backend/resources/akvo/lumen/config.edn
backend/src/akvo/lumen/component/emailer.clj
backend/src/akvo/lumen/config.clj
backend/src/akvo/lumen/main.clj
ci/k8s/deployment.yaml.template

Fix the misconfigured email component and also do some clean up.
Removed unused configs, renamed component from MailjetEmailer to
MailjetV3Emailer to make it more obvious that it is built for the v3
API.

[#1742] Mailjet v3 emailer

---

client/src/containers/Dataset.jsx

Discard failing transformations in history transformation log [client]

---

backend/project.clj
backend/src/akvo/lumen/component/hikaricp.clj

[#1276] Update eastwood and fix warnings

---

backend/src/akvo/lumen/transformation/split_column.clj
backend/test/akvo/lumen/transformation_test.clj
backend/test/resources/split_column.csv

Adapt nil values [#797]

---

backend/src/akvo/lumen/dataset.clj
backend/src/akvo/lumen/endpoint/dataset.clj
backend/src/akvo/lumen/import.clj
backend/src/akvo/lumen/update.clj

- Fix issue with exceptions and rollbacks from inside a JDBC transaction
- Add logging and error reporting in the update future

[#1762] Handle update errors properly

---

client/src/components/charts/ScatterChart.jsx
client/src/containers/Main.scss
client/src/styles/style.global.scss

#1734 scatter improvements fixes

---

client/src/components/charts/Chart.jsx
client/src/components/charts/Legend.jsx
client/src/components/charts/ScatterChart.jsx

#1734 scatter colorpicker improvements

---

backend/src/akvo/lumen/transformation/engine.clj

Improve error messages on undoing transformations

---

backend/src/akvo/lumen/transformation/engine.clj

Adapt engine/next-column-index to  keywordized column

---

backend/src/akvo/lumen/transformation/engine.clj
backend/src/akvo/lumen/transformation/split_column.clj

Stringify columns keys [#797]

---

backend/src/akvo/lumen/import/flow_v2.clj

Add support for "SCAN" flow type values [#1778]

---

backend/.dir-locals.el
docker-compose.override.yml

Make dev work on OS X (Connect #1781)

---

backend/src/akvo/lumen/postgres.clj
backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj
backend/src/akvo/lumen/transformation/split_column.clj
backend/test/akvo/lumen/transformation_test.clj
backend/test/resources/split_column_1785.csv

Fix failing SQL update with single quote or dollar sign values (Connect #1785)

---

backend/src/akvo/lumen/dataset.sql

Filter library and dataset responses (Connect #1776)

---

backend/src/akvo/lumen/lib/export.clj
exporter/index.js

Just to be deployed to develop, once we gather more data about what is happening then this PR will be reverted

Debugging exporter-service http call

---

backend/dev/src/dev.clj
backend/src/akvo/lumen/endpoint.clj
backend/src/akvo/lumen/endpoint/aggregation.clj
backend/src/akvo/lumen/endpoint/commons.clj
backend/src/akvo/lumen/endpoint/commons/http.clj
backend/src/akvo/lumen/endpoint/commons/variant.clj
backend/src/akvo/lumen/endpoint/healthz.clj
backend/src/akvo/lumen/endpoint/invite.clj
backend/src/akvo/lumen/endpoint/library.clj
backend/src/akvo/lumen/endpoint/user.clj
backend/src/akvo/lumen/main.clj
backend/test/akvo/lumen/endpoint/collection_test.clj
backend/test/akvo/lumen/endpoint/dashboard_test.clj
backend/test/akvo/lumen/endpoint/public_test.clj
backend/test/akvo/lumen/endpoint/share_test.clj
backend/test/akvo/lumen/lib/user_test.clj

Tidy up namespaces related to a.l.endpoint ns (Connect #1796)

---

exporter/index.js

Exporter retry functionality fixes #1717

---

backend/src/akvo/lumen/lib/dataset.clj
backend/src/akvo/lumen/lib/raster_impl.clj
backend/src/akvo/lumen/lib/update.clj
backend/src/akvo/lumen/transformation/derive.clj
backend/test/akvo/lumen/lib/update_test.clj
backend/test/akvo/lumen/transformation/derive_test.clj

[#1796]Move akvo.lumen.update ns to akvo.lumen.lib.update

---

backend/src/akvo/lumen/lib/update.clj

relates #1808 
add `multiple` details in `update` operation

[#1808] Ensure multiple-type and multiple-id

---

backend/project.clj

Update `akvo/resumed`
See: https://github.com/akvo/resumed/issues/8

[#1203] Fixes handling of Host, Origin http headers

---

backend/src/akvo/lumen/lib/aggregation/bubble.clj
backend/src/akvo/lumen/lib/public.clj
client/src/components/visualisation/VisualisationEditor.jsx
client/src/components/visualisation/VisualisationPreview.jsx
client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx

#1787 bubble vis fixes

---

backend/project.clj
backend/src/akvo/lumen/lib/dataset.clj
backend/src/akvo/lumen/lib/import.clj
backend/src/akvo/lumen/lib/import/common.clj
backend/src/akvo/lumen/lib/import/flow.clj
backend/src/akvo/lumen/lib/import/flow_common.clj
backend/src/akvo/lumen/lib/import/flow_v2.clj
backend/src/akvo/lumen/lib/import/flow_v3.clj
backend/src/akvo/lumen/lib/job-execution.sql
backend/src/akvo/lumen/postgres.clj
backend/test/akvo/lumen/endpoint/collection_test.clj
backend/test/akvo/lumen/lib/import/csv_test.clj
backend/test/akvo/lumen/lib/pie_test.clj
backend/test/akvo/lumen/lib/pivot_test.clj
backend/test/akvo/lumen/lib/transformation_test.clj
backend/test/akvo/lumen/test_utils.clj

Refactor akvo.lumen.import code (Connect #1796)

---

backend/src/akvo/lumen/lib/import.clj
backend/src/akvo/lumen/lib/import/common.clj
backend/src/akvo/lumen/lib/import/csv.clj
backend/src/akvo/lumen/lib/import/flow_v3.clj
backend/src/akvo/lumen/lib/transformation/geo.clj
backend/src/akvo/lumen/lib/update.clj
backend/src/akvo/lumen/postgres.clj

Move akvo.lumen.import.common postgres generic code to a.l.postgres (Connect #1796)

---

backend/src/akvo/lumen/lib/import/csv.clj
backend/src/akvo/lumen/lib/raster.clj
backend/src/akvo/lumen/util.clj

Decoupling a.l.lib.raster from a.l.lib.import

Move a.l.import.common/get-path to a.l.util namespace (Connect #1796 )

---

backend/src/akvo/lumen/lib/import/flow_common.clj
backend/src/akvo/lumen/lib/import/flow_v2.clj
backend/src/akvo/lumen/lib/import/flow_v3.clj
backend/src/akvo/lumen/lib/transformation/engine.clj
backend/src/akvo/lumen/util.clj

Reuse function in import and transformation

[#1796] Move index-by to akvo.lumen.util

---

backend/src/akvo/lumen/lib/transformation/engine.clj

Remove unreachable code

---

client/src/components/charts/MapVisualisation.jsx
client/src/components/modals/CreateDataset.jsx
client/src/components/modals/ShareEntity.jsx
client/src/components/visualisation/configMenu/MapConfigMenu.jsx
client/src/components/visualisation/configMenu/VisualisationTypeMenu.jsx
client/src/constants/analytics.js
client/src/containers/Dashboard.jsx
client/src/containers/Dataset.jsx
client/src/containers/Transformation.jsx
client/src/containers/Visualisation.jsx

Track visualisation types used with matomo #1818

---

backend/src/akvo/lumen/lib/import/common.clj
backend/src/akvo/lumen/lib/import/flow_v3.clj

Fix extract multiple data (Connect #1808)

---

client/src/translations/en.json

simplify dashboard's text element adding button #837

---

client/src/components/charts/LineChart.jsx

X and Y axis should meet at zero #711

---

client/src/constants/Visualisation/visualisationColumnMappings.js

error thrown when switching from bubble chart to scatter #1841 2

---

backend/src/akvo/lumen/lib/import/flow_common.clj
backend/src/akvo/lumen/lib/import/flow_v2.clj
backend/src/akvo/lumen/lib/import/flow_v3.clj

[#1796] Refactor common flow functionality

---

client/src/components/charts/ScatterChart.jsx

bubble legend for scatter #1790

---

backend/specs/akvo/lumen/specs/import.clj
backend/src/akvo/lumen/postgres.clj
backend/test/akvo/lumen/import_test.clj

Add support for import data sampling (Connect #1450)

---

backend/specs/akvo/lumen/specs/import.clj
backend/src/akvo/lumen/lib/job-execution.sql
backend/src/akvo/lumen/postgres.clj
backend/test/akvo/lumen/import_test.clj
backend/test/akvo/lumen/lib/import/clj_data_importer.clj
backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj
backend/test/akvo/lumen/test_utils.clj

Relates to #1853 
Depends on #1852

Add clj data importer with update test support (Connect #1853)

---

client/src/components/charts/BubbleLegend.jsx
client/src/components/charts/BubbleLegend.scss
client/src/components/charts/ChartLayout.jsx
client/src/components/charts/PolarAreaChart.jsx
client/src/components/charts/ScatterChart.jsx
client/src/components/library/LibraryListingItem.jsx
client/src/translations/en.json
client/src/translations/es.json
client/src/translations/fr.json
client/src/utilities/aggregationOnlyVisualisationTypes.js

New charts small bugs #1854

---

client/src/constants/Visualisation/visualisationSpecMappings.js

#1854 switching between chart types produces errors

---

backend/src/akvo/lumen/lib/dataset_version.sql
backend/src/akvo/lumen/lib/import.clj
backend/src/akvo/lumen/lib/job-execution.sql
backend/src/akvo/lumen/lib/transformation.sql
backend/src/akvo/lumen/lib/transformation/engine.clj
backend/test/akvo/lumen/endpoint/share_test.clj

Unify db calls related to new-dataset-version (Connect #1796)

---

client/src/components/charts/BubbleChart.jsx
client/src/components/charts/Tooltip.jsx

'No data' in bubble tooltip #1867

---

client/src/containers/Dashboard.jsx

@janagombitova I couldnt reproduce but from the error message I think this will fix it

Deleting a visualisation breaks a dashboard #1869

---

client/src/components/visualisation/configMenu/VisualisationTypeMenu.jsx
client/src/constants/images.js
client/src/containers/Dashboard.jsx
client/src/domain/entity.js

Misc vis fixes 1

---

client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx

bubble bucket limiting is random and problematic #1874

---

backend/src/akvo/lumen/lib/public.clj
client/src/components/dashboard/DashboardViewerItem.jsx

[#1877] Wrap fetch visualisation calls in /public/shared in a try/catch block

---

backend/src/akvo/lumen/lib/import/flow.clj

[#1890] Add ex-info message if original `cause` ex-data is nil

---

backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
backend/test/akvo/lumen/lib/transformation/merge_datasets_test.clj

expected args type and value were wrong

Fix a.l.l.transformation.merge-datasets/distinct-columns

---

backend/src/akvo/lumen/lib/transformation/merge_datasets.clj

Fixed type wich -> which in error message (Connect #1896)

---

doc/integration/InputFormat.md

Update InputFormat.md [doc] (Connect #886)

---

client/e2e-test/cypress/integration/index.spec.js
client/e2e-test/sample-data-1.csv
client/src/components/visualisation/configMenu/BarConfigMenu.jsx
client/src/components/visualisation/configMenu/LineConfigMenu.jsx
client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx
client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx

Cypress tests for changing visualisation types #1866

---

client/e2e-test/cypress/integration/index.spec.js

#1866 updated cypress test data url

---

client/e2e-test/cypress/integration/index.spec.js
client/src/components/common/ScrollBar.jsx

#1866 Scrollbar componnet clean up recalc hanlder on unmount

---

client/src/utilities/aggregation.js

Bar visualisation client UI doesn't call aggregation backend API #1900

---

client/.babelrc

Lumen blank in Internet Explorer WIP #1902

---

client/.babelrc
client/e2e-test/cypress/integration/index.spec.js
client/src/components/common/ScrollBar.jsx
client/src/utilities/aggregation.js

This PR is an attempt to rebuild commits in a separate branch and then merge again in develop

Fix travis build

---

client/e2e-test/cypress/integration/index.spec.js

Comment cypress problem [client] [tests]

---

client/.babelrc
client/e2e-test/cypress/integration/index.spec.js
client/package-lock.json
client/package.json
client/src/app.jsx
client/src/auth.js
client/src/components/dashboard/DashboardHeader.jsx
client/src/components/visualisation/VisualisationHeader.jsx
client/webpack.config.dev.js
client/webpack.config.prod.js

#1902 ie11 blank

---

client/e2e-test/cypress/integration/index.spec.js

uncomment changing vis type cypress tests #1902

---

backend/specs/akvo/lumen/specs/transformation.clj
backend/test/akvo/lumen/lib/transformation_test.clj

Change to optional: transformation.change-datatyoe/parseFormat spec

---

backend/src/akvo/lumen/lib/aggregation.clj
backend/src/akvo/lumen/lib/dataset.sql

Speed up aggregation dataset query

---

client/src/polyfill.js

#1902 added string polyfills

---

backend/src/akvo/lumen/lib/import/common.clj

Adapt multiple condition question type to string values (Connect #1924)

---

client/e2e-test/cypress/integration/index.spec.js
client/src/components/charts/BubbleChart.jsx
client/src/components/charts/LineChart.jsx
client/src/components/charts/PieChart.jsx
client/src/components/charts/PolarAreaChart.jsx
client/src/components/charts/ScatterChart.jsx
client/src/components/charts/SimpleBarChart.jsx
client/src/components/charts/SimpleBarChartHorizontal.jsx
client/src/components/charts/StackedBarChart.jsx
client/src/components/charts/StackedBarChartHorizontal.jsx

#1866 cypress test fixes

---

client/src/components/visualisation/configMenu/FilterMenu.jsx

#1779 Show Keep/Remove with filter in visualisation editor

---

client/src/components/charts/SimpleBarChart.jsx
client/src/components/charts/SimpleBarChartHorizontal.jsx
client/src/containers/Dashboard.jsx
client/src/containers/Notification.scss

#1738 remove help button from exports

---

client/src/components/charts/MapVisualisation.jsx
client/src/components/dashboard/DashboardCanvasItem.jsx
client/src/components/dashboard/DashboardEditor.jsx
client/src/components/visualisation/VisualisationEditor.jsx
client/src/components/visualisation/VisualisationPreview.jsx

#1739 Remove zoom buttons when exporting maps

---

backend/src/akvo/lumen/lib/aggregation/commons.clj

Fix scatter bug

---

backend/src/akvo/lumen/lib/aggregation/commons.clj
backend/src/akvo/lumen/lib/visualisation/map_config.clj
backend/src/akvo/lumen/lib/visualisation/maps.clj
backend/src/akvo/lumen/postgres/filter.clj

Align last master hot fixes with develop

---

backend/src/akvo/lumen/postgres/filter.clj

Hot-fix for postgres filter

---

backend/test/akvo/lumen/endpoint/public_test.clj
backend/test/akvo/lumen/endpoint/share_test.clj
backend/test/akvo/lumen/lib/aggregation_test.clj

Avoid use of raw sql and adapt the seed data to domain logic (in other words conform seed data with specs)

Use existent test functions to seed data 

---

backend/src/akvo/lumen/lib/aggregation.clj

Fix donut vis in shares

---

.gitignore
backend/src/akvo/lumen/lib/aggregation.clj

Fix donut vis in shares 

---

backend/project.clj
backend/resources/akvo/lumen/config.edn
backend/specs/akvo/lumen/specs/hooks.clj
backend/src/akvo/lumen/config.clj
backend/src/akvo/lumen/main.clj
backend/test/akvo/lumen/test_utils.clj
ci/k8s/deployment.yaml.template

Conforming specs in `test` deployments

---

backend/src/akvo/lumen/main.clj

Debug config

---

backend/dev/resources/dev.edn
backend/dev/src/dev.clj
backend/resources/akvo/lumen/config.edn
backend/src/akvo/lumen/upload.clj

Configs were merged in wrong order
Also rename akvo.lumen.upload to akvo.lumen.upload/data to fit
duct.core requirements

Fix windshaft config value

---

backend/specs/akvo/lumen/specs/db/dataset_version.clj

Fix spec problem

---

backend/dev/resources/dev.edn
backend/src/akvo/lumen/lib/import/common.clj
backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj

Multiple values types should be strings instead of keywords (Connect #1966)

---

client/e2e-test/cypress/integration/index.spec.js

This wont solve the problem its just to enable us to see the error being thrown.

cypress tests failing intermittently #1969

---

client/src/components/Resources.jsx

Resources tab does not load #1974

---

backend/specs/akvo/lumen/specs/postgres.clj
backend/specs/akvo/lumen/specs/visualisation/maps.clj
backend/specs/akvo/lumen/specs/visualisation/maps/layer.clj
backend/src/akvo/lumen/endpoint/visualisation.clj
backend/src/akvo/lumen/lib/public.clj
backend/src/akvo/lumen/lib/visualisation/map_config.clj
backend/src/akvo/lumen/lib/visualisation/map_metadata.clj
backend/src/akvo/lumen/lib/visualisation/maps.clj
backend/test/akvo/lumen/endpoint/public_test.clj
backend/test/akvo/lumen/lib/visualisation/maps_test.clj

Add 2 new specs namespaces 
- `akvo.lumen.specs.visualisation.maps.layer`
- `akvo.lumen.specs.visualisation.maps`
and keywordize `akvo.lumen.lib.visualisation.maps` and nested nss

Add visualisation maps specs

---

client/src/components/charts/StackedBarChart.jsx

Show percentage labels for percentage stack bars #1978
