akvo/akvo-lumen

client/src/components/dashboard/DashboardViewerItem.jsx
=> #1770 Margin alignment on shared dashboards

backend/specs/akvo/lumen/specs/postgres.clj
=> [#1979] akvo..postgres.filter/value spec support dates(numbers)

client/src/components/charts/StackedBarChart.jsx
=> Percentage stacked bars give NaN when hovering #1977

client/src/components/charts/StackedBarChart.jsx, client/src/components/charts/StackedBarChartHorizontal.jsx
=> Cypress tests failing intermittently #1969 3

windshaft/Dockerfile
=> Update akvo-maps image (Connect #1976)

client/src/components/charts/Legend.scss
=> #1991 centered top and bottom legends

client/src/components/charts/ChartLayout.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx, client/src/constants/Visualisation/scatterSpecTemplate.js
=> Legend  position adds extra scrolling #1989 quick fix

client/src/reducers/dashboards.js
=> Deleting anything gives an error but works #1971

backend/src/akvo/lumen/component/handler.clj
=> Log 500 errors

backend/src/akvo/lumen/main.clj
=> Change :akvo.lumen.specs to :akvo.lumen.specs/specs (connect #2006)

ci/k8s/deployment.yaml.template, exporter/.eslintrc, exporter/index.js, exporter/package-lock.json, exporter/package.json
=> Enable Sentry for Exporter (Connect #2014)

ci/k8s/deployment.yaml.template
=> [#2014] Fix yaml in deployment

client/package-lock.json, client/src/components/charts/SimpleBarChartHorizontal.jsx, client/src/utilities/visualisation.js
=> [#2012] Horizontalbarcharts supports exporting

client/src/components/charts/StackedBarChartHorizontal.jsx
=> [#2012] Fixed stacked horizontal bars

ci/k8s/deployment.yaml.template, client/src/containers/Dashboard.jsx, exporter/index.js
Also start on adding a header to exported Dashboards.
=> [#1694] Use default Sentry env vars

ci/k8s/deployment.yaml.template, exporter/index.js
=> [#1694] Refactor env vars in exporter

exporter/index.js
=> [#1694] Remove debugg statements

backend/dev/resources/dev.edn, backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/handler.clj, backend/test/resources/endpoints-test.edn
=> Comments reviewed

client/src/components/charts/ScatterChart.jsx
=> #1973 Colour picker showing in shared dashboards/visuals

client/src/components/charts/StackedBarChart.jsx, client/src/components/charts/StackedBarChartHorizontal.jsx
=> #2008 Stacked/Split bar's legend position does not change

client/src/components/charts/StackedBarChartHorizontal.jsx
=> #1997 Horizontal percentage stacked bars

client/src/components/charts/LineChart.jsx
=> Line chart misses y axis (Connect #1982)

backend/dev/src/dev.clj
=> Ensure edn files are reloaded with dev/go (connect #2032)

backend/dev/resources/dev.edn, backend/dev/src/dev/commons.clj, backend/dev/src/dev/endpoints.clj, backend/dev/src/dev/endpoints/transit.clj, backend/project.clj, backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/handler.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/endpoints_test/commons.clj, backend/test/akvo/lumen/test_utils.clj, backend/test/resources/endpoints-test.edn, backend/test/resources/test.edn
```
dev env use test.edn
and test env doesn't use dev.edn config
``` 
Example:
http://t1.lumen.local:3000/spec/describe/:akvo.lumen.lib.aggregation/dataset
Example: http://t1.lumen.local:3000/spec/sample/:akvo.lumen.lib.aggregation/dataset
=> Add spec dev endpoints  /spec/action/:spec-ns/:spec-id (Connect  #1876)

client/src/components/charts/StackedBarChartHorizontal.jsx
=> Horizontal percentage stacked bars #1997

backend/dev/resources/dev.edn
=> Fix migrate data in `dev` env

ci/k8s/deployment.yaml.template, windshaft/Dockerfile
=> Fix maps vulnerability

client/src/components/charts/MapVisualisation.jsx, exporter/index.js
=> Exporting map to pdf gives loading spinner in the file #2036

ci/live-color.sh
=> [#2048] Remove not needed flag

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/test/resources/test.edn
Define a flow component that takes care of flow api details such as keycloak auth
Config edn is adapted to (and improved with)  this new component
=> [#1949] Define a flow component

client/src/components/charts/BubbleChart.jsx, client/src/components/charts/ChartLayout.jsx, client/src/components/charts/Legend.scss, client/src/components/charts/ScatterChart.jsx, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx, client/src/utilities/visualisation.js
=> Legend position adds extra scrolling #1989

backend/src/akvo/lumen/lib/auth.clj
=> Align with develop

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/dataset.sql, backend/src/akvo/lumen/lib/public.clj, backend/src/akvo/lumen/protocols.clj, backend/test/akvo/lumen/endpoint/collection_test.clj
=> [#1949] Authorise dataset endpoints

backend/src/akvo/lumen/lib/visualisation/maps.clj
=> Remove unused function arg dataset-id in a.l.l.v.maps/do-create

backend/specs/akvo/lumen/specs/aggregation.clj, backend/specs/akvo/lumen/specs/dataset.clj, backend/specs/akvo/lumen/specs/protocols.clj, backend/specs/akvo/lumen/specs/visualisation.clj, backend/specs/akvo/lumen/specs/visualisation/maps.clj
=> [#1949] Refine/Add vis related specs

backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/lib/auth.clj
=> Align with flow-api /check_permissions changes

backend/src/akvo/lumen/lib/visualisation/maps.clj
=> Refactor akvo.lumen.lib.visualisation.maps

backend/specs/akvo/lumen/specs/auth.clj, backend/specs/akvo/lumen/specs/protocols.clj, backend/specs/akvo/lumen/specs/visualisation.clj, backend/src/akvo/lumen/endpoint/library.clj, backend/src/akvo/lumen/endpoint/visualisation.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/visualisation.clj, backend/src/akvo/lumen/lib/visualisation.sql, backend/test/akvo/lumen/test_utils.clj
=> [#1949] Auth "GET /library" visualisations & "GET /visualisations"

backend/specs/akvo/lumen/specs/visualisation.clj, backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/endpoint/visualisation.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/public.clj, backend/src/akvo/lumen/lib/visualisation.clj, backend/src/akvo/lumen/protocols.clj, backend/test/akvo/lumen/endpoint/collection_test.clj
(Important Things Inside) ...
- rename AuthService/auth? to AuthService/auth
- use middleware to auth visualisation-id in `/visualisations/:visualisation-id` `GET, PUT, DEL` endpoints
- move lib/ok or lib/not-found ... http details to endpoint namespace
=> [#1949] Auth endpoint.visualisation

client/src/components/charts/SimpleBarChartHorizontal.jsx, client/src/components/charts/StackedBarChartHorizontal.jsx, client/src/constants/chart.js, client/src/utilities/chart.js
=> X axis labels get cut off in horizontal bars #2062

backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/auth.clj, backend/specs/akvo/lumen/specs/dashboard.clj, backend/specs/akvo/lumen/specs/visualisation.clj, backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/endpoint/library.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/dashboard.clj, backend/src/akvo/lumen/lib/dashboard.sql, backend/test/akvo/lumen/test_utils.clj
=>  [#1949] Auth "GET /api/dashboards"

backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/lib/dashboard.clj, backend/src/akvo/lumen/lib/public.clj, backend/test/akvo/lumen/endpoint/collection_test.clj, backend/test/akvo/lumen/endpoint/dashboard_test.clj, backend/test/akvo/lumen/endpoint/share_test.clj
=> Refactor: Keywordize /api/dashboards body payloads

backend/specs/akvo/lumen/specs.clj
=> Catch error when calling core/uuid?

backend/specs/akvo/lumen/specs/dashboard.clj, backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/dashboard.clj, backend/src/akvo/lumen/lib/public.clj, backend/test/akvo/lumen/endpoint/dashboard_test.clj
=>  [#1949] Auth "POST /api/dashboards" & "PUT /api/dashboards/:id" payloads

backend/specs/akvo/lumen/specs/auth.clj, backend/specs/akvo/lumen/specs/collection.clj, backend/src/akvo/lumen/endpoint/collection.clj, backend/src/akvo/lumen/endpoint/library.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/collection.clj, backend/src/akvo/lumen/lib/collection.sql, backend/test/akvo/lumen/lib/auth_test.clj, backend/test/akvo/lumen/test_utils.clj
- Auth "GET /api/collections" and "GET /api/library" collections
- Auth col-id in "* /api/collections/:id" with middleware
=> [#1949] Auth collections

backend/src/akvo/lumen/lib/collection.sql
=> Fix auth-collection-ids sql to return empty colls

backend/specs/akvo/lumen/specs/visualisation/maps/layer.clj
Relates to https://sentry.io/organizations/akvo-foundation/issues/990246410/?project=157356&referrer=alert_email
=>  Fix :a.l.specs.visualisation.maps.layer.point-color-mapping/value

client/src/actions/collection.js
=> import id sent when adding entities to collection #2085

backend/src/akvo/lumen/lib/auth.clj, backend/test/akvo/lumen/test_utils.clj
=> [#1949] Add rasters ids to optimistic-allow internal logic

backend/src/akvo/lumen/lib/auth.clj, backend/test/akvo/lumen/lib/auth_test.clj
- We're not interested in validating data but just getting ids
- Add more tests
=> [#1949] Refactor akvo.lumen.lib.auth/ids

backend/src/akvo/lumen/lib/collection.sql
=> [#1949] Fix sql in case of empty collection args

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/monitoring.clj
=> Monitoring flow-api/check-permissions call (Connect #2091)

backend/src/akvo/lumen/lib/auth.clj
=> [#1949] Fix akvo.lumen.lib.auth/auth-visualisations impl

backend/resources/akvo/lumen/config.edn, backend/specs/akvo/lumen/specs/caddisfly.clj, backend/src/akvo/lumen/component/caddisfly.clj, backend/src/akvo/lumen/lib/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/test/akvo/lumen/component/caddisfly_test.clj, backend/test/akvo/lumen/fixtures.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/resources/caddisfly/caddisfly-tests-v2.json, backend/test/resources/test.edn
=> Upgrade caddisfly test schema version

backend/src/akvo/lumen/lib/visualisation/maps.clj
=> [#2097] Add logs

backend/src/akvo/lumen/lib/import/flow.clj
=> Add more logs on import  error case

backend/src/akvo/lumen/lib/auth.clj
=> Ignore nil id values in akvo.lumen.lib.auth/ids

backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/visualisation.sql
=> [#2099] Fix maps query impl in case there is no spec layer

client/src/components/Library.jsx, client/src/components/library/LibraryListing.jsx
=> #1951 library loader

backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/lib/update_test.clj
=> Add column name to Column mismatch error details

backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/update.clj
=> [#1926] Remove keyword use in data column values

backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj
=> [#1950] Improve logs

backend/src/akvo/lumen/component/flow.clj
=> [#1950] Refine logs

backend/src/akvo/lumen/lib/auth.clj
=> [#1950] Don't call flow-api/permissions if no data

backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/job-execution.sql, backend/src/akvo/lumen/lib/job_execution.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, client/src/actions/dataset.js, client/src/utilities/api.js
=> Improve error message when merging datasets 

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/dataset.sql, backend/test/akvo/lumen/endpoints_test.clj
=> [#2071] Add GET /datasets/[dataset-id]/sort/[columnName]?offset=x

backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj
https://github.com/akvo/akvo-lumen/issues/1879#issuecomment-490759897
=> [#1879] Remove brackets in error messages

client/src/components/modals/createDataset/SourceSelection.jsx, client/src/reducers/datasetImport.js
=> [#1672] Set flow as first import dataset option

backend/src/akvo/lumen/endpoint/transformation.clj, backend/src/akvo/lumen/monitoring.clj, backend/test/akvo/lumen/endpoints_test.clj, client/src/containers/Dataset.jsx
=> Include op in transformation metrics (Connect #2135)

backend/src/akvo/lumen/lib/import/flow_common.clj
=> [#1926] Fix flow update column mismatch problem

client/src/containers/Transformation.jsx
=> [#2135] Fix: Add transformation op in POST api

client/src/containers/Transformation.jsx
=> Unblock UI when transformation fails

ci/build.sh
revert cb9f7322891e02ff39c129a95cdcfdedb040e835
=> Run tests against akvolumenci again

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj
=> [#2145] Fix loading spec in validation op-spec

backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj
https://github.com/akvo/akvo-lumen/issues/2071#issuecomment-494274875
=> [#2145] Validate input 

backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/update.clj, backend/src/akvo/lumen/postgres.clj
=> Store geoshape vals 

backend/specs/akvo/lumen/specs/import/column.clj, backend/specs/akvo/lumen/specs/import/values.clj, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj, backend/src/akvo/lumen/postgres.clj, backend/test/akvo/lumen/lib/transformation_test.clj, client/src/components/dataset/sidebars/ExtractMultiple.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
Relates [#2125]
UI functionality behind feature flag `?show-multiple-geoshape=1`
UI Example using flow data from: `greencoffee` > `Baseline` > `M&E baseline` > `M&E baseline`
=> [#2125] Add Geo-shape multiple json features 

backend/specs/akvo/lumen/specs/transformation.clj, client/src/components/dataset/sidebars/CombineColumns.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#710] Add hyphen option to transformation/combine

backend/src/akvo/lumen/lib/transformation/derive/js_engine.clj
=> [#712] Round to 3 decimals the number result in derive tx

backend/project.clj, backend/specs/akvo/lumen/specs/import.clj, backend/src/akvo/lumen/lib/import.clj, backend/test/akvo/lumen/lib/import/clj_data_importer.clj, backend/test/akvo/lumen/test_utils.clj, backend/test/resources/endpoints-test.edn, backend/test/resources/test.edn
=> Give some love to travis build (avoid errors and improve performance)

backend/src/akvo/lumen/lib/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj
=> [#2125] Set Caddisfly default null value as empty string

backend/src/akvo/lumen/component/caddisfly.clj
https://github.com/akvo/akvo-caddisfly/commit/5c8171c4b4a3af1967a36bc22cf06470ed4d877e#diff-f83c183214e694d06e5c6be80c43ad31
=> Align with https://github.com/akvo/akvo-caddisfly/issues/230

backend/project.clj, backend/src/akvo/lumen/component/caddisfly.clj, backend/test/akvo/lumen/component/caddisfly_test.clj
=> Upgrade reitit dep

backend/wait-for-dependencies.sh
=> Align cacerts_file path with openjdk:8-jre-stretch

backend/project.clj, backend/specs/akvo/lumen/specs/collection.clj, backend/specs/akvo/lumen/specs/dashboard.clj, backend/specs/akvo/lumen/specs/dataset.clj, backend/specs/akvo/lumen/specs/visualisation.clj, backend/src/akvo/lumen/postgres/filter.clj, backend/test/akvo/lumen/component/caddisfly_test.clj
=> Update org.clojure/clojure to 1.10

client/src/components/transformation/derive-category/DeriveCategoryMappingText.jsx
=> Handle null values - Category Derived column

client/package-lock.json, client/src/components/dashboard/DashboardEditor.scss
=> [1740] Remove borders on items in exported dashboards

backend/src/akvo/lumen/admin/util.clj
=> Add ssl args to db url connection in admin scripts 

client/package-lock.json, client/package.json
=> Fix client js-yaml vulnerability

exporter/package-lock.json, exporter/package.json
=> [#2194] Updated JSLint to version without security issue

docker-compose.yml
=> [#2188] Update E2E container

backend/dev/src/dev/commons.clj
=> [#2198] When available load local config

backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/test/akvo/lumen/lib/transformation_test.clj, client/src/components/dataset/sidebars/TransformationLog.jsx, client/src/translations/en.json
=> [#2181] Fix column type and improve transformation log

client/src/components/transformation/DeriveCategoryTransformation.jsx
=> [#2181] Fix duplicated cat names error in number cat derivation [client]

backend/specs/akvo/lumen/specs/transformation.clj, client/src/components/transformation/DeriveCategoryTransformation.jsx, client/src/components/transformation/derive-category/DeriveCategoryMappingsNumber.jsx, client/src/components/transformation/derive-category/RowLogicRule.jsx, client/src/translations/en.json
=> [#2181] Category derived number column

client/src/components/transformation/derive-category/DeriveCategoryMappingNumber.scss, client/src/components/transformation/derive-category/DeriveCategoryMappingsNumber.jsx, client/src/components/transformation/derive-category/DeriveCategoryMappingsText.jsx, client/src/components/transformation/derive-category/EmptyRowLogicRule.jsx, client/src/components/transformation/derive-category/RowLogicRule.jsx
=> [#2181] Derived cat number improvements

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/test_utils.clj
=> [#1303] Add tenant name to flow import exception data message

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/test_utils.clj
=> Revert "[#1303] Add tenant name to flow import exception data message"

backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj
=> [#1303] Add instance name to flow import exceptions

backend/src/akvo/lumen/endpoint/env.clj, backend/test/akvo/lumen/endpoints_test.clj, client/src/components/workspace-nav/OrganizationMenu.jsx, client/src/utilities/auth.js
=> [#2218] Refactor env entrypoint response payload

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/test/resources/test.edn
=> [#2218] Call only once http open-id certs for each auth system

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/auth0.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/resources/test.edn
=>  [#2211] Return dynamic auth details from api/env

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/auth0.clj, backend/test/resources/test.edn
... A provisional solution to support 2 auth providers
=>  [#2211] Use auth0-rsa-verifier when keycloak-rsa-verifier fails

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/auth0.clj, backend/test/akvo/lumen/auth_test.clj, backend/test/resources/test.edn
=> [#2211] Provisional solution to authorise @akvo users with auth0 

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/test/akvo/lumen/lib/transformation/derive_test.clj
=> [#2249] Select js row template depending js column naming style

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/test/akvo/lumen/lib/transformation/derive_test.clj
=> [#2249]Select js row template depending js column naming style

backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/endpoint/user.clj, backend/src/akvo/lumen/lib/user.clj, backend/src/akvo/lumen/protocols.clj, client/src/app.jsx, client/src/components/Users.jsx
=> Get/use user-profile admin value from authorisation-service 

backend/src/akvo/lumen/admin/add_tenant.clj, backend/src/akvo/lumen/admin/remove_tenant.clj, backend/src/akvo/lumen/admin/util.clj, backend/src/akvo/lumen/component/auth0.clj, backend/src/akvo/lumen/component/caddisfly.clj, backend/src/akvo/lumen/component/emailer.clj, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/http/client.clj, backend/src/akvo/lumen/lib/export.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj
=> Add explicit value socket-timeout on http.client calls

backend/resources/akvo/lumen/config.edn, backend/resources/akvo/lumen/email/create_new_account_and_invite_to_tenant.txt, backend/resources/akvo/lumen/email/invite_to_tenant.txt, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/endpoint/invite.clj, backend/src/akvo/lumen/lib/user.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/user_test.clj
=> [#2247] Add feature flag to invitation link

backend/src/akvo/lumen/admin/remove_tenant.clj, backend/src/akvo/lumen/admin/util.clj
Also [#2264] Adapt tenant name to postgres entity naming
=> Adapt akvo.lumen.admin socket-timeout http calls

backend/src/akvo/lumen/lib/job-execution.sql, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/test_utils.clj
=> Add (functional) tests. Connect #2254

backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/transformation/rename_column.clj, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/lib/transformation_test.clj
=> Align master 02 08 19

client/src/components/workspace-nav/user-menu/UserMenu.jsx, client/src/components/workspace-nav/user-menu/UserMenuPopUp.jsx
=> [#2245] Close menu if user clicks outside

backend/src/akvo/lumen/lib/import/flow.clj, client/src/actions/dataset.js, client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx, client/src/utilities/auth.js, client/src/utilities/auth0.js, client/src/utilities/keycloak.js
=> Remove refresh-token support in client side

backend/src/akvo/lumen/auth.clj, backend/test/akvo/lumen/auth_test.clj, client/src/components/workspace-nav/NavWorkspaceSwitch.jsx, client/src/utilities/api.js
=> Adapt backend auth responses to json types

client/src/components/dataset/DatasetControls.jsx
=> Remove Search option from dataset view

client/src/components/dataset/DatasetTable.jsx
=> Align number values to the right [client]

client/src/components/workspace-nav/user-menu/UserMenu.jsx, client/src/components/workspace-nav/user-menu/UserMenuPopUp.jsx
=> [#2289] Make the user menu close on button click.

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/auth0.clj, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/src/akvo/lumen/endpoint/invite.clj, backend/src/akvo/lumen/endpoint/user.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/protocols.clj, backend/test/akvo/lumen/auth_test.clj, backend/test/akvo/lumen/component/keycloak_test.clj, backend/test/akvo/lumen/lib/user_test.clj, backend/test/akvo/lumen/test_utils.clj, backend/test/resources/endpoints-test.edn, backend/test/resources/test.edn
and keycloak/keycloak to p/authorizer
Relates #2296
=> Rename "auth0" to "auth0-public-client" and "keycloak" to "keycloak-public-client"

client/src/components/users/Users.jsx
=> [#2304] Sort fn now handles non existing keys

backend/resources/akvo/lumen/email/auth0/create_new_account_and_invite_to_tenant.txt, backend/resources/akvo/lumen/email/auth0/invite_to_tenant.txt
=> [#2308] Improved email text

backend/src/akvo/lumen/auth/jwt_authentication.clj, backend/src/akvo/lumen/auth/jwt_authorization.clj, backend/src/akvo/lumen/component/auth0.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/util.clj, backend/test/akvo/lumen/component/auth0_test.clj
=> Review/Changes on #2313

backend/resources/akvo/lumen/config.edn
=> [#2309] Coerce to Float

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/main.clj
=> [#2309] Coerce to Double

backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/lib/auth.clj
=> [#1949][#2215] Adapt to auth0 in flow-api/check_permissions

ci/k8s/deployment.yaml.template
=> [#2215] Connect auth0 client url and id env vars

ci/k8s/deployment.yaml.template
=> [#2323] authz-api as config

ci/auto-flip-test-blue-green-deployment.sh, ci/build.sh, ci/deploy.sh, ci/helpers/wait-for-k8s-deployment-to-be-healthy.sh, ci/promote-test-to-prod.sh
=> Promote test builds to production

ci/auto-flip-test-blue-green-deployment.sh, ci/deploy.sh
=> Flip TEST after end to end tests

client/src/containers/Main.jsx
=> [#2324] Don't pop up user edit modal on export

ci/flip-blue-green-deployment.sh
=> Echo github diff url in flip script

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, client/src/components/dataset/sidebars/TransformationLog.jsx, client/src/components/transformation/DeriveCategoryTransformation.jsx
=> Augment core/derive-category spec with source.column.title 

client/src/components/users/ConfirmUserAction.jsx
fix the user details when trying to remove a user ...
=> Fix ConfirmUserAction username value

backend/Dockerfile, docker-compose.override.yml
This PR is only for the production docker-container. The dev one is using
https://github.com/akvo/akvo-dockerfiles/blob/master/lumen-backend-dev/Dockerfile#L3
-> 
https://hub.docker.com/layers/clojure/library/clojure/lein-2.9.1/images/sha256-0abe12c86b7eb9767c69b656a5fcc237fb385cb5e733318ed8f1288bef6235f9
=> [#2362] Uppdate to Java 11

backend/src/akvo/lumen/lib/import/flow_common.clj
Relates #2252 and https://sentry.io/organizations/akvo-foundation/issues/1252582163/?project=157354&referrer=slack
=> Increase socket-timeout in flow calls

backend/src/akvo/lumen/admin/add_tenant.clj, backend/test/akvo/lumen/admin/add_tenant_test.clj
=> Allow numeric first character as tenant label [admin]

client/src/components/error/EmailVerificationError.jsx
=> [#2360] Remove yikes

backend/project.clj, backend/src/akvo/lumen/migrate.clj, backend/test/akvo/lumen/fixtures.clj
=> Update ragtime and silent output

backend/src/akvo/lumen/component/caddisfly.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/test/resources/logback-test.xml
=> Clean test output

backend/src/akvo/lumen/endpoint/env.clj, ci/build.sh, ci/deploy.sh, ci/e2e-test.sh, client/e2e-test/cypress/integration/index.spec.js, docker-compose.ci.yml, docker-compose.yml
=> [#2378] Use auth0 as default

backend/test/akvo/lumen/component/keycloak_test.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/auth_test.clj, backend/test/akvo/lumen/lib/user_test.clj, docker-compose.yml
=> Adapt email test accounts to auth0 restrictions

backend/src/akvo/lumen/lib/visualisation/maps.clj
=> [#2376] Remove logs

backend/src/akvo/lumen/lib/auth.clj
Fix condition to call flow-api/check_permissions
=> [#2384] Only load-auth-data if match-by-template-and-method

backend/src/akvo/lumen/lib/import/flow_common.clj
=> [#2385] Use defaults for Flow form instance import

client/src/components/visualisation/configMenu/BarConfigMenu.jsx, doc/spec/visualisations.md
=> [#2389] Only allow text columns as sub bucket col

backend/src/akvo/lumen/lib/auth.clj, ci/deploy.sh, ci/k8s/grafana/lumen-flow-api-authz.yml
=> [#2376] Authz graphs

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
=> [#2394] Fix broken sub buckets

backend/src/akvo/lumen/lib/auth.clj
=> [#2399] Make authz middleware allow collection requests

ci/k8s/grafana/lumen-flow-api-authz.yml
=> [#2394] Add tenant variables to Grafana dashboard

backend/src/akvo/lumen/lib/user.clj
=> [#2402] Adapt response on a.l.lib.user/create-invite

backend/src/akvo/lumen/lib/dashboard.sql, backend/src/akvo/lumen/lib/dataset.sql, backend/src/akvo/lumen/lib/raster.sql, backend/src/akvo/lumen/lib/user.sql, backend/src/akvo/lumen/lib/visualisation.sql
=> Issue/2376 Filter author data to only necessary 

client/package-lock.json, client/package.json, client/src/app.jsx, client/src/components/Library.jsx, client/src/utilities/auth.js
=> Redirect to original url after authentication [client]

backend/src/akvo/lumen/lib/transformation/derive/js_engine.clj, backend/test/akvo/lumen/lib/transformation_test.clj
=> Derive column transformation to number type fails

docker-compose.ci.yml, docker-compose.override.yml, docker-compose.yml
=> CI tests to use the production exporter image

backend/src/akvo/lumen/lib/transformation/derive/js_engine.clj, backend/test/akvo/lumen/lib/transformation/derive/js_engine_test.clj, docker-compose.ci.yml
=> [2362] Remove Nashorn warnings on Java 11

backend/specs/akvo/lumen/specs/import/values.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj
Relates #2426 
https://github.com/akvo/akvo-flow-api/pull/191/commits/c48e8c9a17b13435f527c84488284d6595faee40
=> [#2426] Caddisfly image is fully constructed on flow-api now

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/test/akvo/lumen/lib/transformation_test.clj
=> Don't allow inconsistent js derivation code

backend/dev/src/dev/admin.clj, backend/dev/src/dev/commons.clj, backend/src/akvo/lumen/component/emailer.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/user_test.clj, backend/test/akvo/lumen/test_utils.clj, backend/test/akvo/lumen/utils/dev_emailer.clj, backend/test/resources/test.edn
=> [#2442] Move DevEmailer backend logic to test root folder

client/src/components/dataset/DatasetTable.jsx, client/src/utilities/utils.js
To have groups we need to "UPDATE" the older flow datasets or just "IMPORT" a new one
Relates #2452
=> [#2437] Fix dataset view in case we work with older flow datasets 

.semaphore/semaphore.yml
=> added S2 pipeline

RELEASE_INSTRUCTIONS.md, ci/build.sh, ci/deploy.sh
=> [#2358] Use master as integration branch

.semaphore/semaphore.yml, .travis.yml, ci/build.sh, ci/deploy.sh, ci/helpers/wait-for-k8s-deployment-to-be-ready.sh, docker-compose.ci.yml
=> [#2439] Make build scripts general

.semaphore/semaphore.yml
=> [#2439] Cache backend deps v2

.semaphore/semaphore.yml, backend/test/akvo/lumen/endpoints_test.clj
=> [#2439] Cache client deps

.semaphore/semaphore.yml
=> [#2439] Cache package-lock.json

ci/build.sh
Note that if the build if ok, nothing is logged. Maybe we will want to change this.
=> [#2465] Parallelize BE and FE builds

backend/src/akvo/lumen/component/authz_service.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/protocols.clj
Following same approach as https://github.com/akvo/akvo-lumen/blob/issue%2F2476-authz/backend/src/akvo/lumen/component/tenant_manager.clj#L122
=> [#2476] Spec a.l.component.auth-service-client

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/authz_service.clj, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/lib/auth.clj, backend/test/resources/test.edn
Created new component and moved the authz specific logic to it
We will still leave the authorisation code with the existing feature flags to check the performance in production
See [#2476]
=> Use Authz service instead of Flow API

backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/geo.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj, backend/src/akvo/lumen/lib/transformation/rename_column.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj
Relates to https://github.com/akvo/akvo-lumen/issues/2472#issuecomment-565969451
This PR doesn't contain changes related to merge datasets thus we need a different UI to specify the alternative titles
=> New (transformation) columns should have distinct titles

ci/deploy2.sh
=> [#2483] Add pod resources to new deployment script

ci/deploy.sh, ci/deploy2.sh
=> [#2483] Add ENVIRONMENT env var to test

backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj
=> Don't include groupName nor GroupId on new derived columns

backend/src/akvo/lumen/component/keycloak.clj
=> [#2489] Avoid request-header keycloak call if data exists in cache

backend/dev/src/dev/import.clj, backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/auth/api_authorization.clj, backend/src/akvo/lumen/component/error_tracker.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/test/akvo/lumen/fixtures.clj
=> Add error-tracker support on authorization middleware

ci/deploy2.sh
Fix https://github.com/akvo/akvo-lumen/issues/2488
=> Set pod resources requests/limits

backend/src/akvo/lumen/lib/dashboard.clj, client/src/components/dashboard/Dashboard.jsx
=> [#2374] Simplify client dashboard logic and adapt aggregated dashboard to map types

client/src/actions/dashboard.js, client/src/components/dashboard/Dashboard.jsx
=> [#2374] Show loading spinner if loading aggregated dashboard

client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/constants/analytics.js, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#2370] Dashboard Editor, filter viss by searchable dataset dropdown

ci/deploy2.sh, ci/k8s/deployment.yaml.template
In the process of reverting changes, we lost some of them. This PR cherry picks what's missing from https://github.com/akvo/akvo-lumen/pull/2483
Fix https://github.com/akvo/akvo-lumen/issues/2488
=> Restore container resources variables

client/src/components/library/LibrarySearch.jsx
=> [#2510] Search library on click 'enter' key

ci/deploy2.sh
=> Allow backend containers to consume more CPU

client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss, client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/components/dashboard/DashboardVisualisationList.scss, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json, client/src/utilities/chart.js
=> [#1656] Add Menu tabs and  improve visualization list item design

client/src/components/common/SelectMenu.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss, client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json, client/src/utilities/dataset.js
=> [#1656] Work on filter tab of dashboard with filters [client]

backend/dev/src/dev/admin.clj
=> [#2059] Adapt admin create/delete instance to system config changes

client/src/components/dashboard/DashboardEditor.jsx
=> [#1656] Reset filter.columns on filter.datasetId change

client/src/components/dashboard/Dashboard.jsx
when we request the dashboard view but coming from Library
Relates #2518
=> [#1656] Fix loading filter.column values on dashboard view

client/src/components/dashboard/Dashboard.jsx
=> [#1656] Fix loading filter.datasetId in Dashboard component

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/endpoint/public.clj, client/src/app-pub.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx
=> [#1656] Show filter columns dropdown in public dashboard (with flag)

client/src/actions/dashboard.js, client/src/app-pub.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/components/visualisation/configMenu/FilterMenu.jsx
filter: {dashboardId: 'x',
columns:[::postgres.filter/filter]}
=> [#1656] Send "query" query-params on GET api/dashboards/id with filter spec

client/src/actions/dashboard.js, client/src/actions/dataset.js, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx
=> [#1656] Fix loading dropdown values and more

backend/src/akvo/lumen/lib/aggregation.clj, client/src/components/dashboard/Dashboard.jsx
=> [#1656] Integration fixes

client/src/components/dashboard/Dashboard.jsx
=> [#1656] More client work

backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/endpoint/public.clj, backend/src/akvo/lumen/lib/public.clj, backend/test/akvo/lumen/endpoint/public_test.clj, backend/test/akvo/lumen/endpoint/share_test.clj, client/src/app-pub.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx
=> [#1656] Filter public dashboard

client/src/components/transformation/merge/SourceMergeOptions.jsx
=> [#2531] Adapt to null column

exporter/index.js
=> [#2534] Add specific wait for selector timeout [exporter]

exporter/index.js
=> Revert "[#2534] Add specific wait for selector timeout [exporter]"

backend/src/akvo/lumen/lib/export.clj, exporter/index.js
=> [#2534] Increase backend timeout

client/src/components/charts/MapVisualisation.jsx
=> [#2534] Use a js/Set to manage the layers loaded

client/src/actions/dashboard.js
=> [#1656] Don't persist filter value

client/src/components/dashboard/Dashboard.jsx
=> [#1656] Apply dashboard filter when adding new viz to the dashboard

client/src/components/dashboard/Dashboard.jsx
=> [#1656] Reload dashboard on removing filter

backend/src/akvo/lumen/lib/dashboard.clj, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss
=> [#1656] Improve css and fix backend db update tx 

backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/maps.clj, backend/src/akvo/lumen/lib/dashboard.clj, backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj, backend/test/akvo/lumen/lib/aggregation/map_test.clj, client/src/components/dashboard/Dashboard.jsx
=> Apply dashboard filters to map viz types

client/src/actions/dashboard.js, client/src/app.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/containers/App.jsx, client/src/containers/Root.dev.jsx, client/src/containers/Root.prod.jsx, exporter/index.js
=> [#1656] Use current dashboard filter value in exported result

client/src/components/dashboard/Dashboard.jsx
=> [#1656] Don't PUT dashboard if only changes filter value [client]

backend/src/akvo/lumen/endpoint/dashboard.clj
=> [#1656] Ignore filter with null column values [backend]

client/src/app-pub.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx, client/src/components/dashboard/shared/DashboardViewerItem.scss
related to the dropdown that lets the user select the column name (don't
confuse with the dropdown that selects the column value)
- Also adds an unfiltered icon in case of unfiltered viz
=> [#1656] Persist filter value on changing column [client]

client/src/actions/dashboard.js, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardCanvasItem.jsx, client/src/components/dashboard/DashboardCanvasItem.scss, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#1656] Show current dashboard filter values in exporter version

client/src/containers/App.jsx
=> [#1656] Fix props in export_pages route [exporter] [client]

client/.babelrc, client/package-lock.json, client/package.json
=> [#2560] Use babel-plugin-array-includes [client]

client/src/utilities/dataset.js
=> [#1656] Add all map.spec.layers.dataset to dataset filter dropdown

client/src/components/dashboard/DashboardEditor.scss
[yay.pdf](https://github.com/akvo/akvo-lumen/files/4213098/yay.pdf)
=> [#1656] Add border in DashboardCanvasItem, exporter version [css]

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/endpoint/public.clj, backend/src/akvo/lumen/monitoring.clj
=> [#1656] Add metrics :app/dashboard-apply-filter

client/package-lock.json, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss, client/src/components/dashboard/shared/DashboardViewerItem.scss
=> [#1656] WIP change UI to remove filter

client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/constants/analytics.js
=> [#1656] Rename analytics

client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/utilities/dataset.js
=> [#2570] Fix map viz types in dropdown filter vizs by dataset [client]

client/src/components/dashboard/DashboardVisualisationList.jsx
=> [#2573] Use same modified date logic as library uses [client]

client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/filter/FilterColumns.jsx
=> [#1656] Add padding between UI elements

client/src/components/dashboard/DashboardCanvasItem.jsx, client/src/components/dashboard/DashboardEditor.jsx
=> [#1656] Add mouseover on non filtered dashboard items

client/src/components/dashboard/Dashboard.jsx
=> [#2578] Refresh dashboard from redux on share actions

client/src/components/dashboard/Dashboard.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#2578] Add length password condition and i18n [client]

backend/src/akvo/lumen/lib/share.clj, client/src/app-pub.jsx, client/src/components/dashboard/Dashboard.jsx
=> [#2255] Allow disabling dashboard protection 

client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx
=> [#1656] Fix condition icon on shared dashboard version [client]

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/endpoint/public.clj, backend/src/akvo/lumen/lib/public.clj, client/src/app-pub.jsx
[backend] [client]
Following same share approach, that's to say by Password
=> [#1656] Protect /share/share-id/dataset/dataset-id/column/columnName

backend/src/akvo/lumen/endpoint/public.clj, client/src/app-pub.jsx
=> [#1656] Show filter in shared dashboard in case there is no viz affected by filter

client/src/components/dashboard/DashboardCanvasItem.jsx
=> [#1656] Show unfiltered message on exporter version

client/src/components/dashboard/DashboardCanvasItem.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx
=> [#1656] Minor fixes [client]

client/src/app-pub.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx
=> [#1656] Fix flashing unfiltered icon on filter change on shared version

client/src/app-pub.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/containers/App.jsx
BUT, you can keep disabling filters using false values
```
{
"lumen": {
"features": {
"apiAuthz": false,
"filteredDashboard": false
}
}
}
```
and/or `filter-dashboard=0`
=> [#1656] By default show filter dashboard

docker-compose.override.yml, exporter/Dockerfile, exporter/index.js, exporter/package.json
=> [#2591] Use nodemon for exporter development

ci/k8s/deployment.yaml.template, exporter/index.js
=> [#2594] Add liveness and readinessProbe, remove exitHandler logic to let k8s restart the service

client/src/index.ejs
=> [#2596] Try hotjar as a user feedback widget

client/src/index.ejs
=> [#2596] Try usersnap widget

client/src/app.jsx, client/src/index.ejs, client/src/utilities/feedback.js
=> [#2596] Use auth0 sub as usersnap visitor value

client/src/utilities/feedback.js
=> [#2596] Fix eslint problem

client/src/components/dashboard/Dashboard.jsx, client/src/index-pub.ejs, client/src/index.ejs
=> [#2596] Adapt to public and export views

client/src/components/Resources.jsx, client/src/components/charts/AsyncVisualisationViewer.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardCanvasItemEditable.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dataset/sidebars/ChangeDataType.jsx, client/src/components/dataset/sidebars/Filter.jsx, client/src/components/dataset/sidebars/RenameColumn.jsx, client/src/components/dataset/sidebars/TransformationLog.jsx, client/src/components/library/LibrarySearch.jsx, client/src/components/transformation/ReverseGeocodeTransformation.jsx, client/src/components/transformation/merge/TargetMergeOptions.jsx, client/src/components/users/Users.jsx, client/src/components/visualisation/VisualisationEditor.jsx, client/src/components/visualisation/configMenu/LayerMenuItem.jsx, client/src/components/workspace-nav/user-menu/UserMenuPopUp.jsx, client/src/containers/App.jsx, client/src/containers/Notification.jsx, client/src/containers/Transformation.jsx, client/src/containers/Visualisation.jsx
=> [#2569] Adapt UNSAFE_componentWillmount in lumen code

backend/src/akvo/lumen/lib/visualisation/maps.clj, client/package-lock.json, client/package.json, client/src/components/Library.jsx, client/src/components/charts/AsyncVisualisationViewer.jsx, client/src/components/charts/MapVisualisation.jsx, client/src/components/charts/PivotTable.jsx, client/src/components/charts/bar/StackedBarChart.jsx, client/src/components/charts/bar/StackedBarChartHorizontal.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/modals/ShareEntity.jsx, client/src/components/visualisation/VisualisationEditor.jsx, client/src/components/visualisation/configMenu/MapConfigMenu.jsx, client/src/components/visualisation/configMenu/UniqueValueMenu.jsx, client/src/containers/App.jsx, client/src/containers/Dataset.jsx, client/src/containers/IntlWrapper.jsx, client/src/containers/Notification.jsx, client/src/containers/Raster.jsx, client/src/containers/Visualisation.jsx, client/src/utilities/aggregation.js
- double check `hasTrackedPageView`
=> [#2569] Adapt UNSAFE_componentWillReceiveProps in lumen code

client/src/components/charts/AsyncVisualisationViewer.jsx, client/src/components/charts/MapVisualisation.jsx, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx
=> [#2569] Fix AsyncVisualisationviewer logic

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import.clj
=> [#2635] Remove token from dataset endpoint and don't persist it in dataset payload

client/src/components/charts/AsyncVisualisationViewer.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx
=> [#2629] Fix multiple filters values in shared dashboard

client/src/components/dashboard/DashboardEditor.jsx
=> [#2627] Show "only" used datasets in dashboard filter dropdown

backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/test/akvo/lumen/lib/aggregation_test.clj
Relates #2643 
before the change
after the change
=> [#2643] Sort subbucket bar viz data

backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/pivot.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/visualisation.clj, backend/src/akvo/lumen/lib/visualisation.sql, backend/test/akvo/lumen/lib/aggregation/commons_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj
Relates #2634 
- could be improved with specs the same way we do with authorization => created issue https://github.com/akvo/akvo-lumen/issues/2645
UI message after changes
=> [#2634] Allow delete dataset columns tx if there is no visualisations related

client/src/components/dashboard/DashboardCanvasItem.jsx
https://reactjs.org/docs/forwarding-refs.html
=> [#2569] Adapt Forwarding Refs

backend/src/akvo/lumen/lib/transformation/engine.clj
=> [#2650] Add :dataset-id to undo transformation spec payload

backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/db/dataset_version/column.clj, backend/specs/akvo/lumen/specs/postgres.clj, backend/specs/akvo/lumen/specs/transformation.clj, backend/specs/akvo/lumen/specs/visualisation.clj, backend/specs/akvo/lumen/specs/visualisation/maps.clj, backend/specs/akvo/lumen/specs/visualisation/maps/layer.clj, backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/pivot.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/test/akvo/lumen/lib/aggregation/commons_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj
=> [#2645] Use clojure.specs to retrieve visualisation spec column names

backend/resources/akvo/lumen/prod.edn, backend/src/akvo/lumen/admin/add_tenant.clj, backend/src/akvo/lumen/admin/system.clj
=> [#2296] Fix docker-compose call 

client/src/components/charts/MapVisualisation.jsx
=> [#2659] Use this.props in componentUpdate to get last props version

client/src/components/dashboard/DashboardCanvasItem.jsx
=> [#2661] Ensure vis is ready to render

ci/promote-test-to-prod.sh
=> Delivery metrics support

client/package-lock.json, client/src/actions/visualisation.js, client/src/containers/Visualisation.jsx, exporter/package-lock.json
Only send necessary data when sending a PUT request for visualization
=> [#2679] - only send necessary data on PUT visualisation

ci/promote-test-to-prod.sh
=> Fix Y/n logic on promote script

.gitignore, ci/flip-blue-green-deployment.sh, ci/helpers/record-flip.sh, ci/k8s/flip-record.yaml, ci/set-live-deployment.sh
=> Record production flip

backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj
=> [#2127] Refactor: reuse question-type->lumen-type in flow v2 and v3

backend/specs/akvo/lumen/specs/import/column.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/update.clj, backend/src/akvo/lumen/postgres.clj, backend/test/akvo/lumen/lib/import/flow_common_test.clj, client/src/components/dataset/context-menus/ColumnContextMenu.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
The review should be better if you go through the commits in order 🤓
=> Import one RQG column in flow import/update processes (with feature-flag)

backend/src/akvo/lumen/lib/import/flow_common.clj, backend/test/akvo/lumen/lib/import/flow_common_test.clj
=> [#2127] Use repeated question column title instead of column id

backend/project.clj, docker-compose.override.yml
The changes introduced in the development container can be found at:
https://github.com/akvo/akvo-dockerfiles/commit/f413ba345b96ed8c12b4c047e2a93ff538d4c52a
=> [#2037] Update to Clojure 1.10.1 and Lein 2.9.3

client/src/components/common/PendingSaving.jsx, client/src/components/dataset/DatasetHeader.jsx, client/src/containers/Dataset.jsx
Hooks approach are better to use so let's take this client RQG work as an opportunity
Also work on https://github.com/akvo/akvo-lumen/issues/2712 by https://github.com/akvo/akvo-lumen/commit/c80193cdfa95c969bcfb6d251d9fc05588210a61
=> [#2127] React hooks approach on Dataset view

client/src/components/common/PendingSaving.jsx, client/src/containers/Dataset.jsx
=> [#2711] Update pendingSaving.isUnsavedChages on dataset save

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/import/csv_test.clj, client/.eslintrc, client/src/actions/dataset.js, client/src/components/common/PendingSaving.jsx, client/src/components/dataset/DataTableSidebar.jsx, client/src/components/dataset/DatasetHeader.jsx, client/src/components/dataset/DatasetTable.scss, client/src/components/dataset/DatasetTableV2.jsx, client/src/components/dataset/sidebars/GroupsList.jsx, client/src/components/dataset/sidebars/GroupsList.scss, client/src/components/dataset/sidebars/SidebarHeader.jsx, client/src/components/dataset/wrappers/DefaultDatasetWrapper.jsx, client/src/components/dataset/wrappers/NewDatasetWrapper.jsx, client/src/containers/Dataset.jsx, client/src/translations/en.json, client/src/utilities/column.js
=> [#2705] Rebase with master

client/src/components/dataset/DatasetTableV2.jsx, client/src/components/dataset/wrappers/NewDatasetWrapper.jsx, client/src/containers/Dataset.jsx, client/src/utilities/dataset.js
Preserving functionality using react hooks
This step could be considered a first step towards a better design to not have 600 LOC in DatasetTable(V2) logic 😅 
after this [commit ](https://github.com/akvo/akvo-lumen/pull/2720/commits/5856ce327d0804f0ca5b77a081843f94dbd0b2a6): 600 => 488 LOC
=> [#2127] Use react hooks

backend/src/akvo/lumen/lib/dataset.clj
=> [#2127] Fix function name call

client/src/translations/es.json, client/src/translations/fr.json
=> [#2705] - add translations for french and spanish

client/src/translations/fr.json
=> [#2726] Fix french translation string

client/src/components/dataset/DatasetTableV2.jsx
=> [#2705] Fix stale state problem introduced in DatasetTableV2 hooks version

client/src/components/common/PendingSaving.jsx, client/src/components/common/SelectMenu.jsx, client/src/components/dataset/DatasetTable.scss, client/src/components/dataset/DatasetTableV2.jsx, client/src/components/dataset/sidebars/GroupsList.jsx, client/src/components/dataset/sidebars/GroupsList.scss, client/src/containers/Dataset.jsx
=> [#2705] - tested issues with side navigation

backend/src/akvo/lumen/lib/transformation/engine.clj
Transformation engine is executed in another thread, that only needs to
take care of talking to the DB
=> [#2127] Don't return value on execute transformation (& undo-tx)

client/src/components/dataset/DatasetTableV2.jsx
Fix bug that causes transformation log to break (https://github.com/akvo/akvo-lumen/issues/2705#issuecomment-651061835)
=> [#2705] - fix transformation log

client/src/components/dataset/ColumnHeader.jsx, client/src/components/dataset/ColumnHeader.scss, client/src/components/dataset/DatasetTable.jsx, client/src/components/dataset/DatasetTable.scss, client/src/components/dataset/DatasetTableV2.jsx
=> [#2735] - simplify dataset grid UI

backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/public.clj, backend/src/akvo/lumen/util.clj
=> [#2765] Debug

backend/src/akvo/lumen/lib/transformation/engine.clj
=> [#2755] Simplify error message for dataset update

client/package-lock.json, client/package.json, client/src/components/dataset/DatasetHeader.jsx, client/src/components/dataset/DatasetTableV2.jsx, client/src/components/dataset/sidebars/GroupsList.jsx, client/src/components/dataset/sidebars/GroupsList.scss, client/src/index.ejs, client/src/styles/style.global.scss, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> #2749 -  Add walkthrough for new dataset ui using introJS

backend/src/akvo/lumen/lib/import/flow.clj
=> [#2772] Adapt error message with no auth

backend/src/akvo/lumen/lib/import/flow.clj
=> [#2772] Adapt message

backend/src/akvo/lumen/lib/dataset.clj
=> [#2770] Add source to /api/datasets/<dataset-id>/groups

client/src/components/dataset/DatasetTableV2.jsx
=> [#2767] - make dataset table fully expanded

backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj
=> [#2127] Add "metadata" as a groupId and groupName in flow data

client/e2e-test/cypress/integration/index.spec.js, client/src/components/visualisation/configMenu/LineConfigMenu.jsx
=> [#2689] - change config for line and area charts

client/e2e-test/cypress/integration/index.spec.js, client/src/components/common/SelectMenu.jsx, client/src/components/visualisation/configMenu/BarConfigMenu.jsx
=> [#2780] - allow clearable select menu

client/src/components/visualisation/configMenu/BarConfigMenu.jsx, client/src/components/visualisation/configMenu/SeriesMenu.jsx
=> [#2780] - allow series metric column to be clearable

backend/src/akvo/lumen/lib/transformation.clj, backend/src/akvo/lumen/lib/transformation.sql
=> [#2798] Don't allow new transformation when running update

backend/src/akvo/lumen/component/caddisfly.clj, backend/test/resources/caddisfly/caddisfly-tests-v2.json
=> [#2807] Update local caddisfly file and test number expectations

backend/src/akvo/lumen/lib/import/flow_common.clj
Relates to https://github.com/akvo/akvo-lumen/pull/2784
=> [#2809] Adapt RQG to null responses

backend/specs/akvo/lumen/specs/import/column.clj
=> [#2620] Add column OPTION specs [specs]

backend/src/akvo/lumen/lib/update.clj
=> [#2812] Fix failing update logic flow

backend/src/akvo/lumen/lib/update.clj
=> [#2620] Use feature flag on update process

client/package-lock.json, client/src/components/visualisation/configMenu/BarConfigMenu.jsx, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/FilterMenu.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/components/visualisation/configMenu/LineConfigMenu.jsx, client/src/components/visualisation/configMenu/PieConfigMenu.jsx, client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
=> [#2620] -  add option type to visualizations with text type

backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, client/src/components/dataset/context-menus/ColumnContextMenu.jsx, client/src/components/dataset/sidebars/CombineColumns.jsx, client/src/components/dataset/sidebars/SplitColumn.jsx, client/src/components/transformation/DeriveCategoryTransformation.jsx, client/src/components/transformation/derive-category/SourceDeriveCategoryOptions.jsx, client/src/containers/Transformation.jsx
Relates https://github.com/akvo/akvo-lumen/issues/2620#issuecomment-673398172
=> Adapt transformations to new OPTION type

client/package-lock.json, client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/MapVisualisation.jsx, client/src/components/charts/ScatterChart.jsx, client/src/components/charts/bar/CommonBarChart.js, client/src/components/charts/bar/StackedBarChart.jsx, client/src/components/charts/bar/StackedBarChartHorizontal.jsx, client/src/components/visualisation/configMenu/BarConfigMenu.jsx, client/src/components/visualisation/configMenu/ConfigMenu.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/components/visualisation/configMenu/MapConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx, client/src/utilities/aggregation.js
Also fulfilling  https://github.com/akvo/akvo-lumen/issues/625#issuecomment-674765942
=> Add ordered legend support to scatter and map vizs

backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj
=> [#2620] Adapt backend aggregation of pie, polar, donut, bubble and scatter types

client/package-lock.json, client/src/components/visualisation/VisualisationViewerContainer.jsx
=> [#625] - fix env

backend/src/akvo/lumen/postgres/filter.clj, client/src/components/visualisation/configMenu/FilterMenu.jsx
Relates https://github.com/akvo/akvo-lumen/issues/2620#issuecomment-675462354
=> [#2620] Add option column filter in visualisation [fix]

client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/MapVisualisation.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
=> [#625] Fix order legend in map viz

backend/src/akvo/lumen/lib/aggregation/scatter.clj, client/src/components/charts/ScatterChart.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
=> [#625] Fix order legend scatter impl

backend/src/akvo/lumen/lib/aggregation/bubble.clj, client/src/components/charts/BubbleChart.jsx, client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/PieChart.jsx, client/src/components/charts/bar/SimpleBarChart.jsx, client/src/components/charts/bar/SimpleBarChartHorizontal.jsx, client/src/components/charts/bar/StackedBarChart.jsx
=> [#625] Fix order-legend impl

backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/src/akvo/lumen/lib/visualisation/map_metadata.clj
=> [#2620] Adapt maps to Option pointColorColumn

backend/src/akvo/lumen/lib/visualisation/map_config.clj
=> [#2620] Allow select same column in popup and point-color

backend/src/akvo/lumen/lib/aggregation/pivot.clj
=> [#2835] Adapt pivot chart to OPTION column

backend/src/akvo/lumen/lib/aggregation/bar.clj
=> [#2837] Adapt subbucket-column bar chart to OPTION column type

client/src/components/charts/BubbleChart.jsx, client/src/components/charts/PieChart.jsx, client/src/components/charts/PolarAreaChart.jsx, client/src/components/charts/ScatterChart.jsx, client/src/components/charts/bar/SimpleBarChart.jsx, client/src/components/charts/bar/SimpleBarChartHorizontal.jsx, client/src/components/charts/bar/StackedBarChart.jsx, client/src/components/charts/bar/StackedBarChartHorizontal.jsx, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/components/visualisation/configMenu/PieConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
Relates #2840 and https://github.com/akvo/akvo-lumen/issues/2840#issuecomment-679235530
=> [#625] Release orderLegend feature

backend/src/akvo/lumen/lib/update.clj
=> [#1361] Adapt vector of vectors to vector

backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/update.clj
=> [#2620] Remove feature-flag

client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/components/dashboard/filter/FilterColumns.jsx, client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx
=> [#2845] Refator isClearable to clearable [client]

client/src/app-pub.jsx
=> [#2851] Fix public shared dashboard

ci/deploy.sh, ci/k8s/config-prod.yaml, ci/k8s/config-test.yaml, ci/k8s/deployment.yaml.template
Adding Google SQL Proxy but not using it yet. 
To use it, we will switch the JDBC url configuration
Part of #2855
=> Add Google cloud sql

backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj
=> [#2127] Fix: keep meta flow_v*/formdata

backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/dataset.sql
To be merged in https://github.com/akvo/akvo-lumen/tree/issue-2858
#2859
=> [#2859] Adapt dataset fetch logic to N dataset_versions

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
=> [#2760] Show data groups in subbucket dropdown

backend/specs/akvo/lumen/specs/transformation.clj, backend/test/akvo/lumen/lib/transformation_test.clj
Relates #2858 & #2874 
to be merged into master
=> [#2858] Add namespace to transformation [specs]

client/src/containers/Modal.jsx
Make the Create Dataset modal height auto to accommodate long Select lists
=> [#2881] - make create dataset modal height auto

backend/resources/akvo/lumen/migrations/tenants/025-dataset-version-fully-remove-dataset-id-version-key.up.sql
=> [#2127 #2888] Fully remove dataset-id-version fk [db][migrations]

backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/geo.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/endpoints_test/commons.clj, backend/test/akvo/lumen/lib/transformation_test.clj
relates to #2880
and also:
-> [#2861] Add namespace on derived columns
-> [#2862] Fix retrieving namespace from columns
=> [#2880] Improve fetch dataset 

backend/src/akvo/lumen/lib/visualisation/map_config.clj
=> [#2860] Refactor sql

backend/specs/akvo/lumen/specs/aggregation.clj, backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/pivot.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/dataset/utils.clj, backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/src/akvo/lumen/lib/visualisation/map_metadata.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj
to be merged on https://github.com/akvo/akvo-lumen/tree/issue-2858 branch
it includes also https://github.com/akvo/akvo-lumen/pull/2896
=> [#2860] Add aggregation support with N dataset-versions 

backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj
=> [#2895] Remove table-name not used arg

client/src/utilities/chart.js
=> [#2761] Show pivot total for when only row is selected

backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/transformation.clj, backend/src/akvo/lumen/lib/transformation/change_datatype.clj, backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/filter_column.clj, backend/src/akvo/lumen/lib/transformation/geo.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/geo_shape_features.clj, backend/src/akvo/lumen/lib/transformation/rename_column.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj, backend/src/akvo/lumen/lib/transformation/sort_column.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj, backend/src/akvo/lumen/lib/transformation/text.clj, backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/test/akvo/lumen/lib/transformation_test.clj
to be merged on issue-2858 branch
=> [#2127] Derive `namespace` from transformation selected-column payload

client/package-lock.json
Update dev dependency:  `caniuse-lite`
After update:
```
client_1        | [Browsersync] Serving files from: src
client_1        | [Browsersync] Watching files...
client_1        | webpack built df92225089dffe0b6e46 in 42945ms
```
=> [#2906] Update caniuse-lite version

client/src/components/dataset/DatasetTableV2.jsx
=> [#2891] - don't exit intro on unmount

client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#2891] Add lost sentence to intro guide

client/src/constants/analytics.js, client/src/containers/Dataset.jsx
=> [#2891] Add tracking to data groups switch view

client/src/components/dataset/DatasetTableV2.jsx
=> [#2741] - allows to select all column during combine columns and generate geopoints

client/src/components/dataset/DatasetTableV2.jsx
=> [#2767] - handle resize after switching view

backend/resources/akvo/lumen/migrations/tenants/026-data-group.down.sql, backend/resources/akvo/lumen/migrations/tenants/026-data-group.up.sql
Introduce `data_group` table.
Co-Authored-By @kardan
Co-Authored-By @tangrammer
=> [#2925] data_group table migrations

backend/src/akvo/lumen/component/caddisfly.clj, backend/test/resources/caddisfly/caddisfly-tests-v2.json
=> [#2928] Adapt caddisfly count test expectations

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
=> [#2927] - remove feature flag from bar chart

client/src/components/dataset/sidebars/GenerateGeopoints.jsx
=> [#2933] Proper handling of classic|new grid column definitions

client/src/components/dataset/DatasetTableV2.jsx
=> [#2933] Use all columns in sidebarProps

client/src/components/visualisation/configMenu/BarConfigMenu.jsx
this change update viz spec to client default value https://github.com/akvo/akvo-lumen/blob/master/client/src/components/charts/bar/CommonBarChart.js#L91
=> [#2944] Send showLegend=true in case of bar sub-bucket

client/src/utilities/utils.js
=> [#2952] Guard against a potential null value

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
=> [#2841] - add filters to geoshape maps

backend/src/akvo/lumen/lib/aggregation/bar.clj
=> [#2925] Adapt sql view name to ds table name spec

backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/postgres/filter.clj
=> [#2964] Adapt option value to NULL and '' values (and filtering too)

client/src/components/charts/LegendsSortable.jsx
So bar config left side menu show this value when null is returned by
the backend
=> [#2944] Show displayTextForNullValues in LegendsSortable

client/src/components/dataset/ColumnHeader.jsx, client/src/components/dataset/context-menus/DataTypeContextMenu.jsx, client/src/constants/images.js, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
no more nginx config needed just adding the required webpack & jsx logic to include and read the files
=> [#2707] Require svg images and adapt "multiple" i18n

client/src/components/dataset/sidebars/CombineColumns.jsx, client/src/components/dataset/sidebars/GenerateGeopoints.jsx
=> [#2950] -  fix issue with function name

client/src/app-pub.jsx, client/src/components/PrivacyGate.jsx, client/src/containers/PublicDashboard.jsx
=> Issue 2793/loader on public dashboard

client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/ScatterChart.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
this only fix when bucket column is selected
=> [#2945] - fix legend color on scatter plots

client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/ScatterChart.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
=> Revert "[#2945] - fix legend color on scatter plots"

backend/dev/src/dev.clj, backend/src/akvo/lumen/db/env.clj, backend/src/akvo/lumen/lib/env.sql
=> [#2985] Add feature-flag dev helpers

ci/k8s/grafana/lumen.yml
* This changeset is bigger because I included a new "panel" `Memory
(MiB)`
* Instead of manually hand-picking and "merging" the changes of the
JSON serialized version, this time I copy/pasted due to the new
panel
=> [#2361] Update Grafana dashboard

client/src/components/common/SelectMenu.jsx, client/src/components/common/SelectMenu.scss, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dataset/DataTableSidebar.scss, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/FilterMenu.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/components/visualisation/configMenu/LineConfigMenu.jsx, client/src/components/visualisation/configMenu/PieConfigMenu.jsx, client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
=> Issue 2960/show data groups for all dropdown

backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj
Use [same approach](https://github.com/akvo/akvo-lumen/blob/issue-2925-aggregation-line/backend/src/akvo/lumen/lib/aggregation.clj#L32-L44) for dispatching on vis-type
=> [#2925] Add data-groups support to aggregation line and pie

client/package-lock.json, client/package.json, client/src/components/charts/MapVisualisation.jsx, client/src/components/dashboard/DashboardEditor.scss
=> Revert "Issue/2795 map scroll trigger"

backend/dev/src/dev.clj, backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/import.clj, backend/src/akvo/lumen/db/data_group.clj, backend/src/akvo/lumen/db/dataset_version.clj, backend/src/akvo/lumen/lib/data_group.sql, backend/src/akvo/lumen/lib/dataset_version.sql, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/data_groups.clj, backend/src/akvo/lumen/lib/transformation.sql, backend/test/akvo/lumen/fixtures.clj, backend/test/akvo/lumen/import_test.clj, backend/test/akvo/lumen/lib/import/clj_data_importer.clj, backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj
For the review, better if going through the commit history
=> [#2925] CSV and FLOW dataset test support with data-groups

.semaphore/semaphore.yml, backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj
before we used tenant-conn but should use tenant-tx-conn
=> [#2925] Refactor and add datagroups aggregation support to maps

backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/pivot.clj, ci/flip-blue-green-deployment.sh, ci/promote-test-to-prod.sh
=> [#2925] Complete data-groups support to all visualisation types

client/src/components/common/SelectMenu.jsx, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/FilterMenu.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/components/visualisation/configMenu/LineConfigMenu.jsx, client/src/components/visualisation/configMenu/PieConfigMenu.jsx, client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json, client/src/utilities/column.js
=> [#3002] - show selected option in data groups dropdown

client/e2e-test/cypress/integration/index.spec.js, client/e2e-test/cypress/support/index.js, client/src/containers/Visualisation.jsx
Using the lodash.debouce function. I made the visualizationSpec save
callback only run after 500ms
Closes #2988
Closes #2990
=> [#2988] - set a 500ms timeout before making changes in visualization

backend/src/akvo/lumen/lib/import/data_groups.clj
https://github.com/akvo/akvo-lumen/issues/2756#issuecomment-718791692
=> [#2756] Fix order of data groups with data-groups=true

backend/src/akvo/lumen/lib/transformation/derive_category.clj
=> [#2417] Stop using read-string & eval

.gitignore
=> [#3013] Adapt .gitignore

backend/resources/akvo/lumen/migrations/tenants/028-data-group-group-order.down.sql, backend/resources/akvo/lumen/migrations/tenants/028-data-group-group-order.up.sql, backend/src/akvo/lumen/lib/data_group.sql, backend/src/akvo/lumen/lib/dataset.sql, backend/src/akvo/lumen/lib/import/data_groups.clj
```
select  id, group_id, group_name, repeatable,  group_order  from data_group where dataset_version_id='$dv_id' order by group_order
| id                                   |  group_id | group_name                        | repeatable | group_order |
|--------------------------------------+-----------+-----------------------------------+------------+-------------|
| 5f9c0e07-1ad8-47c4-9433-6a7c4773e8b0 |  metadata | metadata                          | f          |           0 |
| 5f9c0e07-04b4-4a35-bc8c-e70ccc8bf9d3 | 578759117 | Questions defining the data point | f          |           1 |
| 5f9c0e07-7892-439f-893c-f2c388baead9 | 601519116 | Group 2                           | f          |           2 |
| 5f9c0e07-e4d6-400e-9eca-e011ee917053 | 584949117 | For those working on Saturday …
```
=> Issue 2756 data groups

client/src/components/dataset/DatasetTable.jsx, client/src/components/dataset/DatasetTableV2.jsx, client/src/containers/Dataset.jsx
=> [#3007] Read rowsCount only from metadata or main groups

client/src/components/dataset/DatasetTable.jsx
=> [#3007] Fix reference call

backend/src/akvo/lumen/lib/visualisation/map_metadata.clj
Co-authored-by: Daniel Sunnerek <daniel@akvo.org>
=> [#2925] Use column definition from data_group

client/src/components/dataset/DatasetTableV2.jsx, client/src/vendor/intro.js
=> [#2963] Extract specific react introjs internals to vendor folder

client/src/components/dataset/DatasetTableV2.jsx
- Stop showing introjs step in visualization
- Render introjs only once
=> Issue 2963/hide introjs in visualization editor

backend/specs/akvo/lumen/specs/visualisation/legend.clj
=> [#3027] Adapt legend value to null values

backend/resources/akvo/lumen/admin.edn, backend/resources/akvo/lumen/prod.edn
Ensure "LUMEN_DB_URL" env var exists
=> [#3031] Remove old :akvo.lumen.admin.db/config settings

backend/resources/akvo/lumen/prod.edn, backend/src/akvo/lumen/admin/db.clj, backend/src/akvo/lumen/admin/util.clj, ci/k8s/deployment.yaml.template
Co-authored-by: Daniel Sunnerek <daniel@akvo.org> 
Co-authored-by: Iván Perdomo <ivan@perdomo.me> 
=> [#3031] Use postgres-uri var

backend/src/akvo/lumen/admin/add_tenant.clj, backend/src/akvo/lumen/admin/db.clj
=> [#3031] Final fixes

backend/specs/akvo/lumen/specs/transformation.clj, backend/specs/akvo/lumen/specs/transformation/engine.clj, backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/transformation/engine.clj
to be merged on issue/3036-to-uppercase
=> [#3036] Extract column name from payload (re)using specs

backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/data_groups.clj
=> [#2127] Remove rqg flag

backend/src/akvo/lumen/lib/dataset.clj
We have explored the idea of hiding the the `Instance id` for
non-metadata groups in the client. The result is that some code uses
the Redux store (a central place for state) but other parts, like the
Grid, uses the direct response from the XHR call.
Hiding only visually in the Grid and Dropdowns makes us wonder how the
grid will behave if the server is responding more data than the
visible one. How this will play out when transformations are added.
For now it seems *safer* to filter the `hidden` columns in the
backend.
Closes #3045 #3036
=> [#3045] Hide `Instance id` in the backend

client/src/components/dataset/DatasetHeader.jsx, client/src/containers/Dataset.jsx
This will not remove the classic dataset view from the code base, thought is
that it should be easy to rollback if needed.
Closes #3049
=> Use data group dataset view

client/src/components/dataset/DatasetTableV2.jsx
=> [#3052] Into does not reference the view toggle

backend/specs/akvo/lumen/specs/visualisation/legend.clj
relates to #3027 and https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-430396-from-jigmy-at-akvo-dot-org?action=show&controller=admin%2Fconversations&id=akvolumen-support-request-number-430396-from-jigmy-at-akvo-dot-org
=> [#3027] Update spec to conform with empty order

backend/src/akvo/lumen/db/data_group.clj, backend/src/akvo/lumen/lib/data_group.sql, backend/src/akvo/lumen/lib/transformation/engine.clj
=> [#3036] Add support for transformations that produce derived column(s)

backend/src/akvo/lumen/lib/transformation/engine.clj
=> [#3036] Include multiple-column-txs but derive, merge-datasets and reverse-geocode

backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj
=> Add data-group derive and reverse-geocode transformation support

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj, client/src/components/transformation/ReverseGeocodeTransformation.jsx
=> Fix data-group reverse-geocode impl

backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
=> [#3036] Add merge-datasets data-groups transformation support

backend/src/akvo/lumen/lib/transformation/merge_datasets.clj
=> Adapt merge-dataset with datagroups transformation

backend/src/akvo/lumen/lib/transformation/engine.clj
=> [#3061] Restrict data-groups number in transformation payload 

client/src/components/transformation/merge/SourceMergeOptions.jsx, client/src/components/transformation/merge/SourceMergeOptions.scss
=> [#3073] Show data-groups source columns in merge-dataset

backend/src/akvo/lumen/db/transformation.clj, backend/src/akvo/lumen/endpoint/transformation.clj, backend/src/akvo/lumen/lib/transformation.sql, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/test_utils.clj
=> Add Undo transformation support for data-groups

client/src/components/charts/bar/StackedBarChart.jsx
Closes #3088 
Reproduced locally the error and double checked that the changes in this PR fixed the problem
=> [#3088] Return false if no data available

NEW_TENANT.md, ci/new-instance.sh
=> [#3031] New instance bash

backend/.dir-locals.el
Co-authored-by: Iván Perdomo <ivan@perdomo.me>
Using https://gist.github.com/iperdomo/88f3156dbb79fe99bc440d1700bb7162
=> Configure cider-path-translations dynamically

backend/src/akvo/lumen/lib/dataset.clj
- api/datasets/uuid/sort/column-name/text?order=value
- api/datasets/uuid/sort/column-name/number?order=value
=> [#3100] Adapt api sort/column-name endpoints to data-groups flag

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/test/akvo/lumen/lib/transformation/derive_test.clj
=> [#3102] Don't mutate original transformation value

client/src/components/dataset/ColumnHeader.jsx, client/src/components/dataset/ColumnHeader.scss
Closes #2740 
Relates https://github.com/akvo/akvo-lumen/issues/2740#issuecomment-810072467
=> [#2740] Add fx column flag

client/src/components/dataset/ColumnHeader.jsx
=> [#2740] Dont include icon in tooltip when long column titles

backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/engine.clj
- Add :main-op to transformation payload
- Inside delete-column transformation we only check visualisations related if :main-op is different of :update or :undo
=> [#3108] Check visualisations only if main-op = :tranformation

backend/src/akvo/lumen/lib/auth.clj
akvo authz service is not currently deployed
=> [#2476] Dont call authz service

backend/run-server.sh, ci/k8s/deployment.yaml.template
=> [#3125] Collect heap dump on OutOfMemory Error

backend/run-server.sh
=> [#3125] Increase JVM heap to 75% and enable UseContainerSupport

client/package-lock.json, client/src/components/charts/bar/SimpleBarChart.jsx, client/src/components/common/ColorPicker.jsx
- fixed the colour picker not appearing in the right place
=> fixed color picker positioning

backend/project.clj
=> [#3132] Move :pedantic? :abort to :uberjar profile

client/src/actions/collection.js, client/src/actions/dataset.js, exporter/package-lock.json
1. Fixed error on importing new dataset to collection
2. Implement Adding dataset to collection automatically on import
=> fixed adding dataset to collection error

client/src/actions/collection.js, client/src/app-pub.jsx, client/src/components/common/ErrorScreenCustom.jsx, client/src/components/common/ErrorScreenCustom.scss
- Fixed dashboards errors causing page break
- Added Error screens when dashboards are unavailable
=> [2794]Fix: Improved errors for loading public dashboard

backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/test/akvo/lumen/lib/transformation_test.clj
=> [#3145] Don't reorder source merge columns

client/src/components/charts/MapVisualisation.jsx
=> [#3152] Update popups if no filter

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx
https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-551395-from-joy-at-akvo-dot-org
=> [#3155] Fix map popup toggle button
