client/index.html, client/src/store/configureStore.prod.js, client/webpack.config.js
* bundle.js and other assets are set up to be served from the `/assets/` path
=> [#26] Make sure that the client production build works

backend/provision/tear-down.sh
Tear-down now accepts an -f to force client connections to be closed.
=> [#111] tear-down.sh takes force (-f) argument.

backend/resources/org/akvo/dash/migrations_tenant_manager/001-tenants.up.sql, backend/test/org/akvo/dash/fixtures.clj
The migrations weren't completely rolled back in fixtures resulting in multiple records of tenants after testing more than once.
I'm fixing this by rolling back fully and I'm also adding a UNIQUE constraint to the tenants.label field to safeguard against it happening again (And other bad things that might come from not having unique labels).
=> #118 migrations rollback

backend/resources/org/akvo/dash/migrations_tenants/005-dataset-version.up.sql, backend/src/org/akvo/dash/import.clj, backend/src/org/akvo/dash/import.sql
* In addition to creating the ds_<uuid> table on import we need another copy
of the exact same data in another table (called imported_<uuid>). This table
will be used when re-applying the transformation log from the beginning, for
example in an undo operation.
* Later, in the case of updating datasets (refetching from the data source)
it will be essential to be able to get back to the data that was successfully
reimported but failed the subsequent automatic transform operation
=> [#170] Store imported data twice

client/src/components/dataset/sidebars/ChangeDataType.jsx, client/src/reducers/transform.js
* We need to figure out how to communicate to the user that a transformation
was aborted (as requested by the user).
=> [#229] Catch and return original dataset if the error strategy is 'fail'

client/src/containers/Visualisation.jsx, client/src/reducers/visualisations.js
@gabemart I hope I didn't break something but can you quickly test
* Creating a new visualisation by selecting New->Dataset in the UI
* Creating a new visualisation by going directly to the url `/visualisation/create`
* Open and edit an existing visualisation via the UI
* Go directly to a visualisation via `/visualisation/<some-valid-uuid>` and edit/save.
=> [#246] Permalinks for visualisations and visualisation/create

client/src/components/library/LibraryListing.jsx
* Datasets & visualisations have `name` property while
dashboards have `title` property instead
* We'll move to using `title` everywhere later, both on
the client and on the backend.
=> [#238] Resolve library sorting by name

client/src/components/visualisation/ConfigMenu.jsx
#289 
@jonase these are the requested changes to the visualisation editor in advance of the MVP demo.
It's clear that some deeper changes are needed - if we want to keep this new order, then the names for the various visualisation properties should also be changed to make things less confusing. But given the time constraints, I think these changes are enough for now, and we can have a discussion of the best way forward after the demo.
=> [#289] Change visualisation editor input order to match feedback

backend/src/org/akvo/lumen/auth.clj, backend/src/org/akvo/lumen/config.clj, backend/src/org/akvo/lumen/system.clj, backend/test/org/akvo/lumen/auth_test.clj
Also renamed middleware namespace to auth.
=> [#258] [#303] Lumen now pass correct issuer to wrap-jwt-claims

backend/src/org/akvo/lumen/config.clj, backend/src/org/akvo/lumen/main.clj, backend/src/org/akvo/lumen/migrate.clj
We should run migrations on app init to make sure we progress the db on
deployments. Bindings had to be moved to a separate namespace to
circumvent circular dependencies.
=> [#337] Migrate on init

backend/src/org/akvo/lumen/config.clj, backend/src/org/akvo/lumen/main.clj, backend/src/org/akvo/lumen/migrate.clj
=> [#340] Assert correct env vars in production

client/src/components/modals/createDataset/AkvoFlowDataSourceSettings.jsx
* Recent update to react-select made a change to the callback api. Instead of the selected value, we get an object with both the label and the value now.
=> [#343] Resolve flow import regression

RELEASE_NOTES.md, client/src/components/charts/MapVisualisation.jsx, client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/utilities/chart.js
=> [#559] Sort pointColorMapping before render so order is constant

RELEASE_NOTES.md, client/src/utilities/chart.js
* We use `===` when comparing so we need to parse the test value to a float
for numbers and to an int for dates.
=> [#570] Fix filter "exactly matches" for numeric columns

RELEASE_NOTES.md, client/src/utilities/vega-specs/Pie.js
#600 
This also fixes a small visual bug where the highlight color for segments that are being hovered over would not show correctly when the cursor was over the label text part of the segment
=> [#600] Show percentage values in pie and donut chart hover labels

client/src/utilities/chart.js
#578 
By sorting the aggregated data before feeding it to vega, we increase the chances that pie charts will have more consistent segment colors across charts
=> [#578] Sort pie chart segments to get consistent colors

client/src/components/charts/PivotTable.jsx, client/src/components/visualisation/VisualisationEditor.jsx, client/src/components/visualisation/configMenu/FilterMenu.jsx, client/src/components/visualisation/configMenu/PivotTableConfigMenu.jsx, client/src/components/visualisation/configMenu/UniqueValueMenu.jsx, client/src/containers/Visualisation/pivotTableSpecTemplate.js, doc/spec/visualisations.md
#621 
I added some update logic so we only hit the `pivot` api when we expect the aggregated data to have changed. If we don't do anything, we'll hit the api on every `onChange` event for the text inputs for the new `rowTitle` and `categoryTitle` fields on the spec.
=> [#621] pivot column names

client/src/utilities/chart.js
Fixes https://github.com/akvo/akvo-lumen/pull/624#issuecomment-284686517
#578
=> [#578] Compare bucket labels to empty value string instead of null

client/src/components/dashboard/DashboardViewerItem.jsx, client/src/styles/DashboardViewerItem.scss
When the text of a text entity is too big to fit in a shared dashboard, allow the entity to scroll vertically so the reader can see all the text
#661
=> [#661] Let text entities scroll on published dashboards

client/src/components/visualisation/configMenu/LayerConfigMenu.jsx, client/src/styles/LayerConfigMenu.scss
#688 
Truncate column names longer than 128 chars in the popup menu editor for map visualisations
RELEASE_NOTES: `Fixed bug where long column names would overlap in the Popup editor for map visualisations`
=> [#688] Truncate long column names in map popup text menu

backend/src/akvo/lumen/lib/aggregation/filter.clj
RELEASE_NOTES: `Fix bug where multiple numeric filters would fail to filter the data correctly`
=> [#650] Fix operator precedence issues in aggregate filters

client/src/index.jsx
`RELEASE_NOTES`: Fixed bug where the user would stop being authenticated after keeping lumen open but not using it for 30 minutes.
=> [#849] Disable SSO Idle Timeout by bumping the timeout every 10 minutes

client/src/components/common/ContextMenu.jsx, client/src/components/dataset/DatasetControls.jsx, client/src/components/dataset/DatasetTable.jsx, client/src/components/dataset/context-menus/ColumnContextMenu.jsx, client/src/components/dataset/context-menus/DataTypeContextMenu.jsx, client/src/components/library/CheckboxEntityMenu.jsx, client/src/components/library/LibraryListingItem.jsx, client/src/components/visualisation/configMenu/LayerMenuItem.jsx
#811 
I had to touch the same file as #775 refers to, so I made an additional one-line change to also resolve that issue
RELEASE_NOTES: `Renamed "Dataset Editor" menu to "+ Transform"`
(I don't think the context menu change warrants a mention in release notes)
=> [#811] [#775] Auto-dismiss context menus

client/src/components/charts/MapVisualisation.jsx, client/src/utilities/chart.js
`RELEASE_NOTES (bug fix)`: Resolved issue where map rendering would fail if there's only a single geo point
=> [#1020] Expand bounding box if min/max are equal

client/src/containers/Visualisation.jsx
`Release Notes (bug)`: Only show valid datasets in visualisation editor drop downs
=> [#1037] Only show valid datasets in visualisation editor dropdowns

client/src/containers/Dashboard.jsx
`RELEASE_NOTES (bug)` Fixed bug where it was not possible to immediately share an existing dashboard
#1066
=> [#1066] Set isUnsavedChanges to false when opening an existing dashboard

.gitignore, README.dev.md, backend/Dockerfile-dev, backend/import-and-run.sh, backend/run-as-user.sh, docker-compose.yml
* Setup an .env file with the host's user and group id
* Use lein image based on Alpine linux: 96MB (lein-2.7.1-alpine) vs 313MB (lein-2.7.1)
* The `run-as-user` makes sure the `akvo` user and group exists
with the hosts UID and GID
* docker-compose file adjustments to use .env settings
=> [#1098] Run lein commands as with host's user and group id

backend/src/akvo/lumen/lib/visualisation/map_config.clj
#1125 
It's not working at the moment because `null` is not a number so the value that gets into the cartocss is `"null"` instead of `null`. 
Another approach would be adding an explicit null check
=> [#1125] Avoid treating null as a string in cartocss

client/src/components/visualisation/VisualisationEditor.jsx
#1127
To test: create a new map, add a pointColorMapping, save the visualisation (i.e. save it for the first time) and then verify that the point color inputs don't disappear and remain functional
=> [#1127] First pass at updating container with pointColorMapping

client/src/components/common/LumenBranding.jsx, client/src/components/common/LumenBranding.scss, client/src/components/visualisation/VisualisationViewerContainer.jsx, client/src/components/visualisation/VisualisationViewerContainer.scss, client/src/index-pub.jsx
#1163 
Resizing strategy for visualisations remains the same, but now we add padding to the parent div and measure the size of a new child div to pass down to children
=> [#1163] Add padding to shared visualisations and reduce branding size

windshaft/Dockerfile
New image is backwards compatible and requires no changes in Lumen.
Changes that affect Lumen:
1. Smaller container image (from 1gb to 256mb)
2. Fixed performance issue with stats collection. Minor impact for Lumen.
Other changes that do not affect Lumen, but maybe interesting:
1. Added health check endpoint
2. Added a statds-to-prometheus sidecar for monitoring
=> [#1217] Update to latest Windshaft container

client/src/components/visualisation/VisualisationEditor.jsx
#1229
RELEASE_NOTES: `Fix bug where new layers could not be added to old maps`
=> [#1229] Always use *current* spec for visualisation config menu

backend/src/akvo/lumen/lib/raster_impl.clj
- The reprojection and getting the sql data can fail too
- Move the try/catch to wrap the whole process and update the
job_execution status on failure
=> [#1161] Run import in a try/catch

backend/src/akvo/lumen/lib/raster_impl.clj
Catch a `java.lang.Throwable` to handle potential `OutOfMemoryError` when importing large raster files
=> [#1161] Catch Throwable to handle possible OutOfMemoryError

client/Dockerfile, client/default.conf
We know now that `GoogleHC` was not the cause of the high CPU usage on fluentd pod.
See: https://github.com/kubernetes/dashboard/issues/2723
=> [#1320] Rollback changes made in a1243d4

.travis.yml, ci/deploy.sh
- We moved the setup of the service account credentials to the last moment to allow builds from external forks
- We know that we're not going to deploy from an external fork, only from `develop` or `master` in the main repo
=> [#1336] Decrypt the service account credentials just before using it

.gitignore, backend/.dir-locals.el
Fix #1383 
Relevant installation info in #1383  specially this [one](https://github.com/akvo/akvo-lumen/issues/1383#issuecomment-383894327)
=> Fix CIDER find-var, can't jump to definition with a docker-nrepl connection

backend/src/akvo/lumen/transformation/derive.clj, backend/src/akvo/lumen/transformation/derive/js_engine.clj, backend/src/akvo/lumen/transformation/engine.clj
**_Decoupling js & sql & clj (code and execution)_** 
Separate js code to its own namespace
Js-process all sql data retrieved before executing sql updates to give
it a more data oriented approach
This PR leaves the js-engine code isolated to be replaced by a more robust version (org.javadelight/delight-nashorn-sandbox), =>  https://github.com/akvo/akvo-lumen/compare/issue/1296-js-engine
Relates to #1296
=> Refactor a.l.t.derive 

keycloak/Dockerfile
It means that if the default akvo.json is changed the KC container must
be recreated (or the whole dev env) but it also means that any change
in the realm is not lost when restarting the container, which is more
in line with how the Postgres DB actually works.
Fixes #1439
=> [#1439] Using IGNORE_EXISTING when importing

backend/test/akvo/lumen/import/csv_test.clj
specifically this output
```
09:17:22.976 [main] ERROR akvo.lumen.import - #error {
:cause Invalid csv file. Varying number of columns
:data {}
:via
[{:type clojure.lang.ExceptionInfo
:message Invalid csv file. Varying number of columns
:data {}
:at [clojure.core$ex_info invokeStatic core.clj 4739]}]
:trace
[[clojure.core$ex_info invokeStatic core.clj 4739]
[clojure.core$ex_info invoke core.clj 4739]
[akvo.lumen.import.csv$get_column_count invokeStatic csv.clj 72]
[akvo.lumen.import.csv$get_column_count invoke csv.clj 68]
[akvo.lumen.import.csv$csv_importer invokeStatic csv.clj 77]
[akvo.lumen.import.csv$csv_importer invoke csv.clj 74]
[akvo.lumen.import.csv$eval9604$fn__9606 invoke csv.clj 100]
[clojure.lang.MultiFn invoke MultiFn.java 233]
[akvo.lumen.import$do_import invokeStatic …
```
=> Tidy up test logging output

client/src/components/charts/LineChart.jsx, client/src/components/charts/ScatterChart.jsx, client/src/components/charts/SimpleBarChart.jsx, client/src/components/charts/StackedBarChart.jsx, client/src/utilities/chart.js
#1456
For chart types where we show a tooltip, and where the user has chosen an aggregation (e.g. mean, q1 etc) then we should display the aggregated value to an appropriate number of decimal places
=> [#1456] Add rounding heuristic for chart display values

backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/pie.clj, backend/src/akvo/lumen/lib/aggregation/pivot.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, backend/src/akvo/lumen/lib/visualisation/map_config.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj, backend/src/akvo/lumen/postgres.clj, backend/src/akvo/lumen/postgres/filter.clj, backend/src/akvo/lumen/transformation/change_datatype.clj, backend/src/akvo/lumen/transformation/engine.clj
IMO makes sense to put in its own namespace `akvo.lumen.postgres` the postgres code that could be used in any akvo project. I found that `akvo.lumen.lib.aggregation.filter` could perfectly extracted 
Maybe this is the beginning of taking out reusable postgres logic from other lib namespaces too
=> Move postgres independent logic outside aggregation domain

backend/dev/resources/dev.edn, backend/resources/akvo/lumen/system.edn, backend/src/akvo/lumen/component/caddisfly.clj, backend/src/akvo/lumen/config.clj, backend/test/akvo/lumen/component/caddisfly_test.clj, backend/test/resources/caddisfly/tests-schema.json
Just add 2 versions of caddisfly component, one for `production` and one for `test` and `dev` envs. 
Only production will try to retrieve online schema using http client. The other version doesn't need internet connection so it's handy for development purposes
for this development component version we add akvo-lumen/backend/test/resources/caddisfly/tests-schema.json as a local resource (1233 LOC)
=> Add caddisfly component

backend/src/akvo/lumen/import.clj, backend/src/akvo/lumen/import/common.clj, backend/src/akvo/lumen/import/flow_v3.clj, backend/src/akvo/lumen/update.clj, client/src/components/dataset/context-menus/ColumnContextMenu.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
Multiple means that columns with this type contain multiple values that could be
extracted to multiple columns
so far, and internally, this `multiple` type is only taken by caddisfly data imported by flow
=> Add new `multiple` lumen type

backend/resources/akvo/lumen/system.edn, backend/src/akvo/lumen/endpoint/transformation.clj, backend/src/akvo/lumen/transformation.clj, backend/src/akvo/lumen/transformation.sql, backend/src/akvo/lumen/transformation/engine.clj, backend/src/akvo/lumen/transformation/multiple_column.clj, backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj, backend/test/akvo/lumen/lib/pivot_test.clj, backend/test/akvo/lumen/transformation/engine_test.clj, backend/test/akvo/lumen/transformation_test.clj, backend/test/resources/columns_test.json
Relates to #1571 
These changes allow multiple-column cell data to be extracted to new columns 
the `client` [side](https://github.com/akvo/akvo-lumen/pull/1614) will send following payload ...
core/extract-multiple transformation payload
- `args.selectedColumn.multipleType` and `args.selectedColumn.multipleId` should be used to dispatch functionality on backend
- `args.columns`  payload describes the extraction column schema 
```
{
"op": "core/extract-multiple",
"args": {
"columns": [
{
"id": 1,
"name": "Soil Electrical Conductivity :: μS/cm",
"type": "text",
"extract": true
},
{
"id": 2,
"name": "Temperature :: °Celsius",
"type": "text",
"extract": false
}
],
"columnName": "c107069115",
"extractImage": false,
"selectedColumn": {
"columnName": "c107069115",
"multipleType": "caddisfly", …
```
=> Add core/extract-multiple transformation op 

backend/resources/akvo/lumen/system.edn, backend/src/akvo/lumen/endpoint/multiple_column.clj, backend/src/akvo/lumen/lib/multiple_column.clj, backend/test/akvo/lumen/component/caddisfly_test.clj, backend/test/akvo/lumen/lib/multiple_column_test.clj
retrieving details for multiple column
so far only `caddisfly` multipleType is implemented
example request:
`/api/multiple-column?query=%7B%22multipleType%22%3A%22caddisfly%22%2C%22multipleId%22%3A%2280697cd1-acc9-4a15-8358-f32b4257dfaf%22%7D`
parsed values `query: {"multipleType":"caddisfly","multipleId":"80697cd1-acc9-4a15-8358-f32b4257dfaf"}`
=> Add GET /api/multiple-column/ endpoint

backend/src/akvo/lumen/import/flow_v3.clj
Relates to #1595
I've tested this change importing a fresh flow dataset and updating an older one, in both cases Device ID is showed with proper values
=> Add Device ID to imported dataset from flow

client/src/components/dashboard/DashboardCanvasItemEditable.scss, client/src/components/dashboard/DashboardViewerItem.jsx, client/src/components/dashboard/DashboardViewerItem.scss
Ive fixed this but as a result the comment here about white space under text cannot be fixed - https://github.com/akvo/akvo-lumen/issues/1576#issuecomment-415463201 - we cant have a dashboard where the elements are laid out properly AND the text elements have variable heights. All boxes need to be absolutely positioned with fixed heights @janagombitova
=> Last graphs cut off in shared dashboards #1639

ci/k8s/deployment.yaml.template
Raise the container max CPU limit to 2000.
=> [Fixes #1697] Maps container set to 2000m

backend/resources/akvo/lumen/migrations/tenants/020-dataset-version-create-index-version.down.sql, backend/resources/akvo/lumen/migrations/tenants/020-dataset-version-create-index-version.up.sql, backend/src/akvo/lumen/dataset.clj, backend/src/akvo/lumen/dataset.sql, backend/src/akvo/lumen/transformation.sql, backend/src/akvo/lumen/transformation/merge_datasets.clj
Problematic datasets are those that have merge transformations that use datasets columns that don't exist anymore, maybe the column was removed, maybe the dataset was removed
=> Avoid database inconsistencies on updating problematic datasets (Connect #1689 )

backend/src/akvo/lumen/dataset.clj, backend/src/akvo/lumen/transformation.clj, backend/src/akvo/lumen/transformation.sql, backend/src/akvo/lumen/transformation/delete_column.clj, backend/src/akvo/lumen/transformation/engine.clj, backend/src/akvo/lumen/transformation/merge_datasets.clj, client/src/actions/dataset.js
These changes  don't allow either to delete columns that participate in an external merge-transformation
=> Don't allow deletion of dataset that is used in a merge transformation

backend/src/akvo/lumen/lib/aggregation/bar.clj
Use "count" metricAggregation when no metricColumnY but there is bucketColumn [#1055]
Extracted from slack ...
```
in `/backend/src/akvo/lumen/lib/aggregation/bar.clj` if we do not send `metricColumnY` in the query parameters but we do send bucketColumn then we need to use count aggregation for the y value. make sense?
```
=> Use "count" metricAggregation  (Connect #1055)

backend/dev/resources/dev.edn, backend/project.clj, backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/hikaricp.clj, backend/src/akvo/lumen/component/tenant_manager.clj, backend/src/akvo/lumen/lumen_monitoring.clj
Using Prometheus:
* Added monitoring stats from HikariCP (https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics)
* Added very basic HTTP metrics.
* JVM (memory/threads/gc)
Also fixed a connection pool leak.
About the HTTP metrics, there is no way to get the full compojure matched path, so instead of
having thousands of urls (due to the REST urls), prefer to have just one
stat, so at least we can see the traffic and error rates.
Compojure has a wrap-routes function to do this, but it doesnt work as we
need when using compojure/context. When using context, we can just capture
the latest bit of the matched api. For example:
(context "/visualization/:id"
(GET "/meta"...
We are just able to get the "/meta" part, when what we actually want is
"/visualization/:id/meta".
=> Add some monitoring

backend/src/akvo/lumen/component/handler.clj
Since middleware arguments are defined in vectors and
(seq? []) ;; false
(sequential? []) ;; true
=> [#1745] Handle middleware args as vectors

ci/k8s/blue-green-gateway.yaml
Removing unused config, as the dark/live to blue/green mapping is stored
in the lumen-live service
Fixes #1751
=> Clean up blue-green-gateway

backend/maybe-import-and-java-jar.sh
We use WAIT_FOR_DB as signal for develop and testing in CI. When
running a bash script with `set -o nounset` we need to provide defaults
to potentially uninitialized variables. We use the "${VAR:=default}"
as way to default a value.
> ${parameter:=word}
>
>    If parameter is unset or null, the expansion of word is assigned
>    to parameter. The value of parameter is then
>    substituted. Positional parameters and special parameters may not
>    be assigned to in this way.
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
=> [#1710] Fix ubound variable

backend/dev/src/dev.clj, backend/project.clj, backend/src/akvo/lumen/component/caddisfly.clj, backend/src/akvo/lumen/import.clj, backend/src/akvo/lumen/import/common.clj, backend/src/akvo/lumen/lib/multiple_column.clj, backend/src/akvo/lumen/specs/components.clj, backend/src/akvo/lumen/specs/components/caddisfly.clj, backend/src/akvo/lumen/transformation/merge_datasets.clj, backend/src/akvo/lumen/transformation/multiple_column.clj, backend/src/akvo/lumen/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/update.clj, backend/test/akvo/lumen/component/caddisfly_test.clj, backend/test/akvo/lumen/test_utils.clj, backend/test/akvo/lumen/transformation_test.clj
Relates to #1441 
Adding specs to current code will need in many times some apparently unrelated changes like changing type of arguments (instead of seq of args to use a single arg map type with keys keywordized ... ) and/or changing functions to be somehow more _specable_ (moving to another ns, renaming ... ).  As a practical example this PR also contains refactors that affect to caddisfly logic
=> Add clojure spec gradually (Connect #1441)

backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/raster_impl.clj, backend/src/akvo/lumen/transformation/geo.clj, backend/src/akvo/lumen/update.clj, backend/test/akvo/lumen/lib/import/csv_test.clj, backend/test/akvo/lumen/lib/import/raster_test.clj, backend/test/akvo/lumen/test_utils.clj
=> [#1796] Move akvo.lumen.import logic inside akvo.lumen.lib

backend/src/akvo/lumen/component/emailer.clj, backend/src/akvo/lumen/component/error_tracker.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/component/tenant_manager.clj, backend/src/akvo/lumen/endpoint/aggregation.clj, backend/src/akvo/lumen/endpoint/collection.clj, backend/src/akvo/lumen/endpoint/dashboard.clj, backend/src/akvo/lumen/endpoint/data_source.clj, backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/endpoint/invite.clj, backend/src/akvo/lumen/endpoint/job_execution.clj, backend/src/akvo/lumen/endpoint/library.clj, backend/src/akvo/lumen/endpoint/public.clj, backend/src/akvo/lumen/endpoint/raster.clj, backend/src/akvo/lumen/endpoint/resource.clj, backend/src/akvo/lumen/endpoint/share.clj, backend/src/akvo/lumen/endpoint/split_column.clj, backend/src/akvo/lumen/endpoint/tier.clj, backend/src/akvo/lumen/endpoint/transformation.clj, backend/src/akvo/lumen/endpoint/visualisation.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/update.clj, backend/src/akvo/lumen/lib/user.clj, backend/src/akvo/lumen/protocols.clj
Reasoning behind these changes is that having currently these protocols defined and in use, we need to put them in a generic place (I've defined only one to put all together but we could create more specific namespaces if we need it) to decouple implementation. That's to say, service clients doesn't need to know where implementation lives 
Relates to #1796 specifically to https://github.com/akvo/akvo-lumen/issues/1796#issuecomment-441480602 and https://github.com/akvo/akvo-lumen/issues/1796#issuecomment-441519559
Review could iterate through commits thus they are isolated (Commit titles should serve as doc porpose)
=> [#1796] Move current protocols to akvo.lumen.protocols ns

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/lib/transformation/derive_test.clj, backend/test/akvo/lumen/lib/transformation/engine_test.clj
move apply-transformation-log from a.l.update to transformation.engine
thus transformation logic should live under a.l.transformation namespace
+ also hide a.l.t.engine/try-apply-operation 
+ tidy up
=> Decouple a.l.transformation from a.l.update (Connect #1796)

backend/src/akvo/lumen/lib/transformation/change_datatype.clj, backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/geo.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/src/akvo/lumen/lib/transformation/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/rename_column.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj, backend/src/akvo/lumen/lib/transformation/sort_column.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj, backend/src/akvo/lumen/lib/transformation/text.clj, backend/src/akvo/lumen/lib/visualisation/maps.clj, backend/src/akvo/lumen/util.clj, backend/test/akvo/lumen/lib/visualisation/maps_test.clj
Theoretically and later on, we'll need to create some kind of domain model namespace
to grab this common functionality a bit better
But so far let's put common things into util namespace
=> Extract common functions from a.l.l.t.engine to a.l.util (Connect #1796)

backend/src/akvo/lumen/lib/import/flow.clj
Theoretically should be better to wrap the cause exception into a greater one with `(ex-info msg map cause)` but looking at current `akvo.lumen.component.error-tracker/event-map` [implementation](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/component/error_tracker.clj#L25) seems that we only send to sentry the main exception data.
So current changes will add data to current exception data instead of wrapping into a new one
=> [#1845]Add instance details to import flow data ex

client/src/components/charts/BubbleChart.jsx, client/src/components/charts/BubbleLegend.jsx
this fixes a bug where we try render a bubble chart and the title for the bubble legend is not set
=> #1854 hide bubble legend if no label set

backend/project.clj, backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/db.clj, backend/specs/akvo/lumen/specs/import.clj, backend/specs/akvo/lumen/specs/import/values.clj, backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/multiple_column/caddisfly.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj, backend/src/akvo/lumen/util.clj, backend/test/akvo/lumen/fixtures.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/test_utils.clj
Relates to #1441 & #1450 & #1858 
Also conform in `test` and `dev` the new-dataset-version db call in import and transformation processes 
Thus we need some data adaptation for conforming the new-dataset-version payload, we can't use plain s/instrument facility for conforming the spec. As an alternative the PR uses robert-hooke library to check specs that need this data adaptation in `dev` and `test` environments
=> Add transformation and db specs (Connect #1441 & #1450 & #1858)

backend/specs/akvo/lumen/specs/import.clj, backend/specs/akvo/lumen/specs/import/column.clj, backend/src/akvo/lumen/lib/import.clj, backend/test/akvo/lumen/lib/import/clj_data_importer.clj, backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/lib/transformation_test.sql
All changes related to `test` and `spec` besides this commit https://github.com/akvo/akvo-lumen/pull/1878/commits/6698ffadebb7532a8fd06cd882559d2623ab5035 that makes possible fully import functionality of clj-data-importer `backend/test/akvo/lumen/lib/import/clj_data_importer.clj` 
- Add date generators
- Add core/merge-datasets transformation test
=> Add more work on  #1858 and #1450

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/change_datatype.clj, backend/src/akvo/lumen/lib/transformation/combine.clj, backend/src/akvo/lumen/lib/transformation/delete_column.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/filter_column.clj, backend/src/akvo/lumen/lib/transformation/geo.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/src/akvo/lumen/lib/transformation/multiple_column.clj, backend/src/akvo/lumen/lib/transformation/rename_column.clj, backend/src/akvo/lumen/lib/transformation/reverse_geocode.clj, backend/src/akvo/lumen/lib/transformation/sort_column.clj, backend/src/akvo/lumen/lib/transformation/split_column.clj, backend/src/akvo/lumen/lib/transformation/text.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/test_utils.clj
Keyword aren't jsonables in db (postgres/json) nor client
side (javascript/json)
So far we change `op` value to keyword when backend tries to
process/dispatch the transformation client request, that force
implementation to manage the same data with different types, firstly
as string, later as keyword, finally as string.
Also the approach is not the dafault one. Dispatching aggregation is based on
strings, also dispatching import process is based on strings too
So this commit will unify the dispatching approach to be always based
on strings
=> Change transformation.op to string type

backend/test/akvo/lumen/lib/transformation_test.clj
if  :akvo.lumen.specs.transformation.change-datatype/newType is equal to `date` `parseFormat` can't be nilable
=> Fix transformation.change-datatype/parseFormat spec

backend/dev/resources/dev.edn, backend/resources/akvo/lumen/config.edn, backend/specs/akvo/lumen/specs.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/component/tenant_manager.clj, backend/src/akvo/lumen/migrate.clj, backend/test/akvo/lumen/lib/user_test.clj
This PR relates to following error
```
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'init-key' for dispatch value: :akvo.lumen.specs
at clojure.lang.MultiFn.getFn (MultiFn.java:156)
at clojure.lang.MultiFn.invoke (MultiFn.java:233)
at integrant.core$try_build_action.invokeStatic (core.cljc:292)
```
https://weavejester.github.io/integrant/integrant.core.html#var-load-namespaces  impl doesn't work properly when component keys aren't fully qualified keywords. 
So `load-namespaces` doesn't work with `:akvo.lumen.specs` but integrant let's you use this identifier
Then adapting code to ensure that lumen can use this utility function https://github.com/weavejester/integrant#loading-namespaces 
- `akvo.lumen.specs` changes to `akvo.lumen.specs/specs`
- …
=> Fix java.lang.IllegalArgumentException: No method in multimethod 'init-key' for dispatch value: :akvo.lumen.specs

backend/src/akvo/lumen/lib/aggregation/pivot.clj, backend/test/akvo/lumen/lib/aggregation_test.clj
It's possible to filter out all rows that is needed as categories for
crosstab(text source_sql, text category_sql) in postgres. According to Postgres docs
this is not valid:
"category_sql is a SQL statement that produces the set of categories. This
statement must return only one column. It must produce at least one row,
or an error will be generated" (https://www.postgresql.org/docs/11/tablefunc.html).
Hence when there is no categores we return an empty table.
=> Support filter out all values in Pivot table (Connect #741)

client/src/components/modals/ShareEntity.scss, client/src/containers/Dashboard.jsx, client/src/utilities/visualisation.js
There are some outstanding issues. For example, if a password is set. And then the user tries to update the password to a too short one. He/she will get an error dialog at the bottom of the screen (the backend responded with error) but the alert in the modal will be all happy with a green succeded. But I think that is another issue than this initial one. I tried to fix that one too, but backed out of it since it looked to me like a little bit of rearchitecting is needed. @finnfiddle if you think different ping me.
=> Fix for error protecting dashboards (Connect #2024)

backend/src/akvo/lumen/component/handler.clj
Fix flatten consequences in reitit middleware vector expectations
Made reverse ordering when configs where merged through duct.core/merge-configs....
=> Fix vector type in reitit data middleware

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj
**To be reviewed&merged after https://github.com/akvo/akvo-lumen/pull/2070**
- Auth id in "/datasets/:id*" with middleware
- Move lib http details from lib.dataset to endpoint.dataset
- Auth outcome data for "GET /datasets/id"
=> [#1949] Auth "api/datasets" continuation

backend/specs/akvo/lumen/specs/collection.clj, backend/src/akvo/lumen/endpoint/collection.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/collection.clj, backend/src/akvo/lumen/protocols.clj, backend/test/akvo/lumen/endpoint/collection_test.clj, backend/test/akvo/lumen/lib/auth_test.clj
Add protocol provisional workaround that only ensure uuid but not [uuid collection-type] relation. 
Depends on #2080 
```clojure
(defprotocol AuthService2080
(optimistic-allow? [_ d]
"Provisional workaround for
https://github.com/akvo/akvo-lumen/issues/2080
'Refactor api/collections payload'"))
```
=> [#1949] Auth "PUT /collections/:id" & "POST /collections" payloads 

backend/specs/akvo/lumen/specs/visualisation.clj, backend/specs/akvo/lumen/specs/visualisation/maps.clj, backend/specs/akvo/lumen/specs/visualisation/maps/layer.clj, backend/src/akvo/lumen/lib/auth.clj
`PUT /api/visualisations/:id` and `POST /api/visualisations` can have more than one dataset-id attached if visualisation type is `map` type.
So, with these changes we ensure that user is allowed to use those dataset-ids 
payload example:
```clojure
{:name "my vis name",
:visualisationType "map",
:type "visualisation",
:created 1555933154021,
:modified 1555933154021,
:datasetId nil,
:spec
{:version 1,
:baseLayer "street",
:layers [{:aggregationMethod "avg",
:popup [],
:filters [],
:layerType "geo-location",
:legend {:title "latitude", :visible true},
:rasterId nil,
:pointSize 3,
:pointColorMapping [],
:longitude nil,
:datasetId "5cbd79a7-ba3b-4443-8433-2d14639dd269",
:title "Untitled layer 1",
:geom "d1",
:pointColorColumn "c2",
:latitude nil,
:visible true}]},
:status "OK",
:id …
```
=> [#1949] Auth visualisation map type payloads 

client/src/actions/dashboard.js, client/src/components/dashboard/DashboardCanvasItem.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardEditor.scss, client/src/containers/App.jsx, client/src/containers/Dashboard.jsx, client/src/containers/Dashboard.scss, client/src/utilities/dashboard.js, client/src/utilities/withExport.jsx, client/src/utilities/withProps.jsx, client/test/utilities/dashboard.js
Ok so this turned out to be quite a tricky little task - basically a packing algorithm to pack items onto pages when exporting pdf - and moving items around creates cascading changes to subsequent pages. I wrote tests so I'm confident everything is working. Here is a pdf created with the new algorithm
[Map Dashboard (29).pdf](https://github.com/akvo/akvo-lumen/files/3111523/Map.Dashboard.29.pdf)
=> Visualisation get split for dashboard pdf exports #1740

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/test/akvo/lumen/lib/auth_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj
Relates to #2071 
```
{
op: 'core/derive-category',
args : {
source: {column: {columnName: 'c1'}},
target: {column: {title: 'Color'}},
derivation: {mappings: [
[['source-val-1'],'derived-val-1'],
[['source-val-2', 'source-val-3'], 'derived-val-2'],
[['source-val-4', 'source-val-5', 'source-val-6'],'derived-val-3']],
uncategorizedValue: "Uncategorised"
}
}
}
```
=> Add core/derive-category transformation backend op

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive_category.clj, backend/test/akvo/lumen/lib/transformation/derive_category_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj, client/src/components/transformation/DeriveCategoryTransformation.jsx
#2071 
Example payload: 
```clojure
{:source {:column {:columnName "c3"}},
:target {:column {:title "Column 1"}},
:derivation
{:uncategorizedValue "8",
:mappings
[[["<=" -1] ["<" -1] "0"]
[[">" -1] ["=" -2.0] "q"]
[[">=" -1] [">" 0] "0a"]
[["<=" -1.0] ["<" 2.0] "Z5"]
[["<" 1.0] [">=" 0] "G"]
[[">" 0] [">" 2.0] "3"]
[[">" -1] ["=" -1.0] "C"]
[["<=" -1] ["=" -1] "1s"]
[["=" 0] ["<" -1.0] "S"]
[[">=" 1.0] nil "2tk1"]],
:type "number"}}
```
`[["<=" -1] ["<" -1] "0"]` 
+ First expression `["<=" -1]`
+ Second/optional/and expression `["<" -1] `
+ mapped category `"0"`
`[["<=" -1] nil "0"]` 
+ First expression `["<=" -1]`
+ Second/optional/and expression `nil`
+ mapped category `"0"`
=> Add number type support for derive-category transformation

backend/project.clj
Relates #2037 
included all deps returned by lein `ancient updated` except following ones:
```
[org.clojure/clojure "1.10.0"] is available but we use "1.9.0" 
[org.postgresql/postgresql "42.2.5"] is available but we use "42.2.2"
```
=> Update backend deps 

client/src/components/transformation/MergeTransformation.jsx, client/src/components/transformation/merge/SourceMergeOptions.jsx
=> Add select-all option to merge dataset view [client]

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/test/resources/test.edn
Currently we are calling open-id certs for every entrypoint we declare in config.edn, 
working with current keycloak `dev` environment doesn't affect performance thus the http calls are done in local docker, but switching to other not-local auth system  (like auth0) will slow the system startup in `dev` too
=> [#2218] Call only once http open-id certs for each auth system

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/auth0.clj, backend/test/resources/test.edn
So far, this component is in charge of wrapping auth0 config data and to get the rsa-cert doing an http call ... so same functionality as the current keycloak component
=> [#2218] Add auth0 component [backend]

backend/resources/akvo/lumen/email/auth0/create_new_account_and_invite_to_tenant.txt, backend/resources/akvo/lumen/email/auth0/invite_to_tenant.txt, backend/resources/akvo/lumen/email/keycloak/create_new_account_and_invite_to_tenant.txt, backend/resources/akvo/lumen/email/keycloak/invite_to_tenant.txt, backend/src/akvo/lumen/endpoint/invite.clj, backend/src/akvo/lumen/lib/user.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/user_test.clj, client/src/app.jsx, client/src/components/Users.jsx
After agreeing with Jana about sending an email with auth0 to add the specific email account to use, this PR adds specific email templates for each auth system option (keycloak and auth0) 
About keeping the verification link in auth0 version is just to keep compatibility with keycloak, that's to say that we could remove it once keycloak is removed. So far it's needed  thus keycloak users verification-email is supported by lumen and authorisation is based on keycloak users and verification-email by lumen
=> Sign up with auth0

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth.clj, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/config.clj, backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/test/resources/test.edn
Relates #2228, implements https://github.com/akvo/akvo-lumen/issues/2228#issuecomment-521193513
Added integrant function `:akvo.lumen.component.flow/internal-api-headers` to inject different logic depending environment.
In `dev` and `test` envs we select api-_external_-headers logic so the jwt-token is passed from the frontend to the flow-api directly (though with a limited expired time)
We can increase the jwt-time-expiration in auth0 settings for akvo-auth0-`test` environment too so we could avoid time expiration problems related
=> Avoid refresh-token support with no auth in internal-flow-api 

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/component/flow.clj, backend/src/akvo/lumen/config.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/test/resources/test.edn, ci/k8s/deployment.yaml.template, docker-compose.ci.yml
Currently client is rejected when it tries to connect to flow-api using auth0 thus the flow-api url used validates the token against keycloak as auth system
With these changes, client side will target proper flow-api url value
Relates to
#2228, https://github.com/akvo/akvo-platform/pull/162, https://github.com/akvo/akvo-platform/issues/163
=> Adapt to flow-api-auth0 url

client/src/components/modals/CreateDataset.scss, client/src/containers/Modal.jsx
An attempt to squeeze the height of the modal to make users with tiny screens see the action buttons. Hopefully this is enough, otherwise, I think more drastic redesigns of the options in the panels of the steps in the modal is needed.
=> [#2322] Squeeze the createDataset modal height

backend/resources/akvo/lumen/config.edn, backend/src/akvo/lumen/auth/api_authorization.clj, backend/src/akvo/lumen/component/keycloak.clj, backend/src/akvo/lumen/protocols.clj, backend/test/akvo/lumen/component/keycloak_test.clj
Relates #2307 
It'll try to read a `LUMEN_PATHS_CACHE_SECONDS` ENV seconds or just the config.edn hard coded value, that's `60`
=> Add cache to allowed-paths auth api call

ci/build.sh
until we had an alternative cypress test that uses the auth0 [recommended approach](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/), that is, to make a POST call to get the token instead of hitting the UI login page
=> [#2378] Disconnect lumenci e2e test

ci/build.sh, ci/deploy.sh, ci/e2e-test.sh, client/e2e-test/cypress/integration/index.spec.js, client/src/containers/Main.jsx, docker-compose.ci.yml, docker-compose.yml, exporter/index.js
Relates [#2378]
- Adds travis ci vars `AUTH_CLIENT` and `AUTH_PASSWORD` that contain the auth0 client-id and auth0 client-password
=> Adapt cypress tests based on auth system

.gitignore, ci/flip-blue-green-deployment.sh, ci/helpers/generate-slack-notification.sh, ci/promote-test-to-prod.sh
Generate a script that when run will post to Slack the changes to be
promoted to dark production, or the changes after a production flip.
Script requires a Slack legacy token (https://api.slack.com/custom-integrations/legacy-tokens). 
Fixes #2427
=> Optional slack notification script when promoting/flipping production

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/update.clj, client/src/actions/dataset.js
Relates [#1361] 
Add transformation index
Specify js columns not found references
Example of improved message:
To test it locally, you need to edit your local.edn with these settings:
```clojure
{
:akvo.lumen.component.flow/api {:url "https://api-auth0.akvotest.org/flow"
:internal-url "https://api-auth0.akvotest.org/flow"
:internal-api-headers #ig/ref :akvo.lumen.component.flow/api-headers}
:akvo.lumen.component.authentication/public-client    
{:url "https://akvotest.eu.auth0.com/"
:client-id "PIcm0mTZLfzufij7mlGP1v72VPwXDGfw"
:rsa-suffix-url ".well-known/jwks.json"
}
}
```
Then import a flow dataset, define a new js trasnformation that points to a non existent column, then click on update
=> Improve error message on flow update errors

client/src/components/dataset/sidebars/DeriveColumnJavascript.jsx, client/src/translations/en.json, client/src/translations/es.json, client/src/translations/fr.json
=> [#2244] Don't allow the word "function" nor the sign "=>" [client]

exporter/index.js
Following k8s logs, by default is 30000ms
Exception captured for run ID: - { TimeoutError: waiting for selector ".render-completed-5e393b63-7144-453a-be41-76d2b2fff4d9" failed: timeout 30000ms exceeded at new WaitTask (/node_modules/puppeteer/lib/DOMWorld.js:561:28) at DOMWorld._waitForSelectorOrXPath (/node_modules/puppeteer/lib/DOMWorld.js:490:22) at DOMWorld.waitForSelector (/node_modules/puppeteer/lib/DOMWorld.js:444:17) at Frame.waitForSelector (/node_modules/puppeteer/lib/FrameManager.js:628:47) at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:23) at Frame.waitFor (/node_modules/puppeteer/lib/FrameManager.js:613:19) at Page.waitFor (/node_modules/puppeteer/lib/Page.js:1037:29) at Promise.all.selectors.map (/usr/src/app/index.js:116:22) at Array.map (<anonymous>) at …
=> [#2534] Increase timeout in page.waitFor [exporter]

backend/src/akvo/lumen/lib/aggregation.clj, client/src/components/dashboard/Dashboard.jsx, client/src/components/dashboard/DashboardCanvasItem.jsx, client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/shared/DashboardViewer.jsx, client/src/components/dashboard/shared/DashboardViewerItem.jsx
- Rename visualisation.unfiltered prop to filterAffected [backend]
[client]
- Pass filter to DashboardCanvasItem and DashboardViewerItem to
internally decide if dash[hasBeen]Filtered [client]
=> [#1656] Fix unfiltered icon on no filter value [backend] [client]

client/src/components/dashboard/DashboardEditor.jsx, client/src/components/dashboard/DashboardVisualisationList.jsx, client/src/utilities/visualisation.js
Fix "On filter editor “x/n Visualisations” (x not working)"
=> [#1656] Reuse visualisation by dataset condition [client]

ci/k8s/blue-green-gateway.yaml.template, ci/k8s/service.yaml
lumen exporter service needs more than the 30s timeout default value
=> [#2591] Increase timeoutSec to 100s using beta.cloud.google.com/backend-config service.yaml definition

client/src/components/charts/MapVisualisation.jsx
Delay the call to `invalidateSize()` so the parent has the new dimension.
When we trigger the `renderLeafletMap` on `componentDidMount` and
`UNSAFE_componentWillReceiveProps` the dimensions of the parent container
element are the *old* ones.
Found it via:
let parent = this.leafletMapNode.parentElement;
console.log(parent.clientHeight, parentclientWidth);
More info:
PaulLeCam/react-leaflet#40
=> Issue 2606 wip

client/src/components/charts/LineChart.jsx
Relates to #2610 
we (with @muloem ) agree on not abbreviate x-axis num values on this line chart viz type
Viz after changes:
=> [#2610] Dont abbreviate x-axis values

backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj
```
clojure.core/take
Returns a lazy sequence of the first n items in coll, or all items if
there are fewer than n.  Returns a stateful transducer when
no collection is provided.
```
=> [#2665] Add 500K dataset rows limit

backend/src/akvo/lumen/endpoint/aggregation.clj, backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/line.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/LineConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
- add backward compatibility with v1 (the sampling one)
=> [#2537] Remove sampling in bubble/line/scatter v2 spec vizs and warn the user if results are greater than 2.5K 

backend/resources/akvo/lumen/config.edn, backend/resources/akvo/lumen/migrations/tenants/022-environment.down.sql, backend/resources/akvo/lumen/migrations/tenants/022-environment.up.sql, backend/src/akvo/lumen/db/env.clj, backend/src/akvo/lumen/endpoint/env.clj, backend/src/akvo/lumen/lib/env.clj, backend/src/akvo/lumen/lib/env.sql
The new `environment` table is a "id => value" type of setup where the
`id` is any string and `value` is any JSON value. Since a JSON value
can be Boolean|Number|Null|Array|Object we can (ab)use it as we want.
Simple boolean value for feature flag:
The `environemnt` table is empty
```
$ curl http://t1.lumen.local:3030/env | jq -M .
{
"auth": {
"clientId": "akvo-lumen",
"url": "http://auth.lumen.local:8080/auth/realms/akvo",
"domain": "http://auth.lumen.local:8080/auth/realms/akvo",
"endpoints": {
"issuer": "http://auth.lumen.local:8080/auth/realms/akvo",
"authorization": "http://auth.lumen.local:8080/auth/realms/akvo/protocol/openid-connect/auth",
"userinfo": "http://auth.lumen.local:8080/auth/realms/akvo/protocol/openid-connect/userinfo",
"endSession": …
```
=> [#2676] Adds support for exposing environment config to `/env` endpoint

client/src/app.jsx
Call `/api/env` after getting the user profile, which means after knowing that we have the auth token.
The resulting `env` object contains the static configuration *plus* a _dynamic_ `environment` key.
=> [#2676] Calls `/api/env` after authentication

backend/specs/akvo/lumen/specs/import/column.clj, backend/specs/akvo/lumen/specs/import/values.clj, backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/update.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/endpoints_test/commons.clj, backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj
Metadata will be used so far to store RQG columns metadata
the future api response with rqg metadata will be more or less like ...
=> [#2127] Add column metadata

backend/src/akvo/lumen/lib/import/flow_common.clj
When enabling `rqg` flag we can use a single value `true` for
enabling/disabling
The different code-path gets enabled by:
```
insert into environment(id, "value") VALUES('rqg', 'true'::jsonb);
```
=> [#2676] Use single value for feature flag

backend/specs/akvo/lumen/specs/import/values.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/test/akvo/lumen/lib/import/flow_common_test.clj
Being a map is more flexible to adapt to each column type needs
this PR is against `issue/2127-rqg-js`
=> [#2127] Use map instead of vector to store column metadata

docker-compose.override.yml
As part of the local development setup we don't need the possibility
of refreshing the JS code via `nodemon`. We only need to use the
published container.
Use `image` instead of `build` and expose the config files as binding
mounts.
=> [#2713] Use akvo/maps image instead of "build" a local one

backend/src/akvo/lumen/endpoint/dataset.clj, backend/src/akvo/lumen/lib/auth.clj, backend/src/akvo/lumen/lib/dataset.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/test/akvo/lumen/endpoints_test.clj, backend/test/akvo/lumen/lib/import/csv_test.clj
Anyway these "static" groupIds will be returned by backend call `/dataset/<id>/groups` returning this kind of [data](https://github.com/akvo/akvo-lumen/issues/2127#issuecomment-644232253) 
so far both groups ^^ are calculated on client-side based on domain conditions such as column names
example json responses
`/dataset/<id>/groups` https://gist.github.com/tangrammer/046a954beba038d34c1f61cbe67cbd22#file-fetch-groups-json
`/dataset/<id>/group/metadata` https://gist.github.com/tangrammer/046a954beba038d34c1f61cbe67cbd22#file-fetch-metadata-group-json
=> [#2127] Add backend APIs to support groups

client/src/components/dataset/DatasetTableV2.jsx
Show all columns when doing transformations, except for Combine columns and Generate Geopoints. More context here (https://github.com/akvo/akvo-lumen/issues/2741)
=> [#2741] - Allow to select all column in transformation dropdown

client/src/components/dataset/ColumnHeader.scss, client/src/components/dataset/DatasetTable.jsx, client/src/components/dataset/DatasetTable.scss, client/src/components/dataset/DatasetTableV2.jsx
This commit will fix the bug that hides the divider line in odd rows.
And also make the dataset table row height smaller
=> [#2735] - show divider line and reduce row height

backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj
The client needs to know which data groups are repeatable. For that,
we client can rely on the metadata in the column definition.
After importing a Flow form, we store as part of the columns
definition the `ns` and `repeatable` keys in the columns and expose
them as part of the endpoint `/dataset/<id>/groups`.
=> [#2127] When `rgq` flag is on, add `ns` and `repeatable` keys

client/src/components/dataset/ColumnGroupHeader.scss, client/src/components/dataset/DatasetTable.scss
=> [#2735] - remove duplicate border from dataset grid

client/src/components/dataset/DatasetTableV2.jsx, client/src/containers/Dataset.jsx
This commit contains some changes
- First, Refactored the effect for dataset groups
- Check if a group is already selected then re-fetch the selected group
data
- Stop the sidebar from automatically closing on every component update
=> [#2753] - Stop transformation from taking user to metadata

client/src/components/dataset/DatasetTableV2.jsx
Using local storage we can track when a user has seen the data group walkthrough so we know not to show the user again. The only limitation is the user sees it If he logs in from another device.
=> [#2749] - only show intro once

backend/resources/akvo/lumen/migrations/tenants/023-dataset-version-alter-unique-constraint.down.sql, backend/resources/akvo/lumen/migrations/tenants/023-dataset-version-alter-unique-constraint.up.sql, backend/resources/akvo/lumen/migrations/tenants/024-dataset-version-add-ns-and-constraint.down.sql, backend/resources/akvo/lumen/migrations/tenants/024-dataset-version-add-ns-and-constraint.up.sql
So far dataset_version identity is based on `dataset-id` and `version``
but with RQG approach we'll have `N` dataset_version for each dataset 
`namespace` column is added to identity together with `dataset-id` and `version`
This PR changes the `columns` value as identity prop and proposes `namespace` thinking in backwards compatibility and to don't need querying the `columns` jsonb value to derive which "data-group" is related with, in other words it should simplify the sql query and domain logic 
By default this column will have `main` as default value
=> [#2127] Add namespace column to dataset_version

backend/src/akvo/lumen/lib/import.clj, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/import/csv.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/update.clj, backend/src/akvo/lumen/util.clj, backend/test/akvo/lumen/lib/import/clj_data_importer.clj, backend/test/akvo/lumen/lib/import/common_test.clj, backend/test/akvo/lumen/lib/import/flow_common_test.clj, backend/test/akvo/lumen/util_test.clj
So far we don't change functionality, so each flow form submission will be represented by one row in dataset_version table, containing only one RQG question/response iteration
In next PRs and behind feature-flag,  we should remove the included adapter logic https://github.com/akvo/akvo-lumen/pull/2784/files#diff-408f43d0bce4b90be771a7b1286a0f1eR54 we could store all RQG question/response iterations
Relates to https://github.com/akvo/akvo-lumen/pull/2734
but instead of trying
```
FROM
;; {question-id -> response1 }
TO
;; {question-id -> [response1]}
```
we do ...
```
FROM
;; {question-id -> response1 }
TO
;; [{question-id -> response1} {question-id -> response2}]
Being each map a table representation, so first map will be main
table, the others will be RQG answers
```
thanks to @iperdomo …
=> [#2127] Normalise import data (processing one of multiple responses)

backend/src/akvo/lumen/db/job_execution.clj, backend/src/akvo/lumen/lib/job-execution.sql, backend/src/akvo/lumen/lib/transformation.clj, backend/src/akvo/lumen/lib/update.clj
Relates #2763 
Thus VACUUM can **not** be run inside a transaction **SO FAR** we need to wait for the full dataset update that also processes the transformations related instead of calling VACUUM after every transformation as should be the ideal implementation
=> [#2763] Run VACUUM after "apply/undo transformation" and after "update dataset"

backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/update.clj
Expected behaviour after applying transformation-log after a new update is to get a new dataset_version with incremented version as a result of applying all transformations with new data imported
Right now we loop all transformations and create/update only one dataset_version row to get the final dataset_version row state
This PR doesn't create a new dataset_version until all transformations are applied to the new ds_table.
The transformations are applied to the new ds_table without db transaction thus if we had any problem we just discard this table
=> [#2763] Vacuum after every tx of update process

backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/db/dataset_version.clj, backend/src/akvo/lumen/db/transformation.clj, backend/src/akvo/lumen/lib/dataset.sql, backend/src/akvo/lumen/lib/dataset_version.sql, backend/src/akvo/lumen/lib/transformation.sql, backend/src/akvo/lumen/lib/visualisation/map_metadata.clj, backend/test/akvo/lumen/db/transformation_test.clj, backend/test/akvo/lumen/endpoint/share_test.clj, backend/test/akvo/lumen/lib/import/clj_data_importer_test.clj, backend/test/akvo/lumen/lib/import/csv_test.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/akvo/lumen/lib/transformation_test.sql, backend/test/akvo/lumen/test_utils.clj
Relates https://github.com/akvo/akvo-lumen/pull/2781
In relation to dataset or dataset-version, remove direct sql references and use clj namespaces for it 
Use default `main` dataset_version.namespace value in updated queries
=> [#2127] Adapt sql dataset_version queries to main ns column value

backend/src/akvo/lumen/lib/aggregation/bar.clj, backend/src/akvo/lumen/lib/import/flow.clj, backend/src/akvo/lumen/lib/import/flow_common.clj, backend/src/akvo/lumen/lib/import/flow_v2.clj, backend/src/akvo/lumen/lib/import/flow_v3.clj, backend/src/akvo/lumen/lib/update.clj, backend/src/akvo/lumen/postgres.clj, client/src/components/visualisation/configMenu/BarConfigMenu.jsx, client/src/translations/en.json
Before this PR, we had "OPTION" values represented as:
`TEXT` in `client`
`TEXT` in `backend`
`TEXT` in `db`
This PR changes the way "OPTION" is represented in client and backend but db keeps the same
`OPTION` in `client`
`OPTION` in `backend`
`TEXT` in `db`
Changes will be behind feature-flag `optionColumnType` 
To test it, we need to update the flow dataset or import a new one
=> Aggregate on OPTION column types

backend/src/akvo/lumen/lib/aggregation/bubble.clj, backend/src/akvo/lumen/lib/aggregation/scatter.clj, backend/test/akvo/lumen/lib/aggregation/scatter_test.clj, backend/test/akvo/lumen/lib/aggregation_test.clj, client/src/components/charts/BarChart.jsx, client/src/components/charts/BubbleChart.jsx, client/src/components/charts/Chart.jsx, client/src/components/charts/LegendsSortable.jsx, client/src/components/charts/PieChart.jsx, client/src/components/charts/PolarAreaChart.jsx, client/src/components/charts/bar/SimpleBarChart.jsx, client/src/components/charts/bar/SimpleBarChartHorizontal.jsx, client/src/components/visualisation/configMenu/BarConfigMenu.jsx, client/src/components/visualisation/configMenu/BubbleConfigMenu.jsx, client/src/components/visualisation/configMenu/ScatterConfigMenu.jsx
Add support for the following types:
- Polar chart
- Horizontal Simple Bar
- Vertical Simple Bar
- Bubble chart
Also needs feature flag 'optionColumnType'
=> [#625] Add more legend order support

client/src/containers/Dataset.jsx
When other groups are clicked, stop the selecting metadata
=> [#2865] -  stop data groups from auto-selecting metadata

backend/specs/akvo/lumen/specs.clj, backend/specs/akvo/lumen/specs/import/column.clj, backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/test/akvo/lumen/lib/transformation_test.clj
Having a `created` transformation timestamp we could generate a history transformation list indexed by that value when we'll have transformations spread in N dataset-versions
Relates to #2861 but could be merged directly against the master branch without more dependencies
=> [#2861] Add transformation "created" timestamp

client/package-lock.json, client/src/components/dataset/DatasetTableV2.jsx, client/src/containers/Dataset.jsx, client/src/utilities/dataset.js
When doing transformations on CSV based datasets, show the sidebar when there's a transformation group available and remove it when there's no transformations
=> [#2901] - show transformations on CSV datasets

backend/specs/akvo/lumen/specs/caddisfly.clj
This PR fixes the return spec by not stating it will return a caddisfly spec but is fairly open with a list of any?'s but is not super stringent. What's returned is {:keys [hasImage :id :name :type]} described at
https://github.com/akvo/akvo-lumen/blob/9e4aadb28f57fdae55a56b609266056c910f70cf/backend/src/akvo/lumen/lib/multiple_column.clj#L11-L17.
=> [#2905] Adopt-schema spec

client/src/containers/IntlWrapper.jsx
Use `Español` and `Français` for language labels.
Closes #2909
=> [#2909] Use proper language labels

client/src/components/dataset/sidebars/GenerateGeopoints.jsx
We have now a new structure `["main", [{col_1}, {col_2}, {col_2}]]`,
we need to pass the 2nd position in the array to the `Select`
component.
Closes #2933
=> [#2933] Adjust the position of the column definition

docker-compose.ci.yml
The build.sh script uses the image declared in
`docker-compose.override.yml` to run the initial checks.
```
backend_image_version=$(awk -F':' '/backend-dev/ {print $3}' docker-compose.override.yml)
```
If we use a different (outdated) image for functional tests (in
`docker-compose.ci.yml`), we're wasting network and space in CI
environment.
=> [#2940] Use the same image for building and functional tests

client/src/components/charts/LegendsSortable.jsx
Sometimes backend aggregation series return "null" label series and client needs to adapt this null value to be able to sort it
=> [#2944] Use chart/displayTextForNullValues instead of null

client/src/components/dashboard/DashboardEditor.jsx
Removing the fetchColumn call when a dashboard filter is removed, because it's being called with a null value
=> [#2954] - remove invalid fetchColumn call in dashboard filters

backend/dev_helpers/local-admin.sh
The scripts creates a new "Local Admin"  user in Keycloak, with the email address passed as argument. It configures the user to be *admin* of `t1` tenant.
Usage:
./backend/dev_helpers/local-admin.sh "<email>"
Example:
./backend/dev_helpers/local-admin.sh "bob@akvo.org"
=> [#1098] Setup local-admin using an @akvo.org email address

backend/src/akvo/lumen/postgres/filter.clj
Option column types are stored as text, so empty value in option column types means "" instead of NULL
Relates #2964
=> [#2964] Filter isEmpty option column as text type

backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/postgres/filter.clj
relates #2964 and https://flowhelp.reamaze.com/admin/conversations/akvolumen-support-request-number-410009-from-irene-at-akvo-dot-org?action=show&controller=admin%2Fconversations&id=akvolumen-support-request-number-410009-from-irene-at-akvo-dot-org
dataset already in akvotest https://lumen.akvotest.org/dataset/5f86cd23-3afd-437b-8536-7546cc5d6c2e 
we can check that there is a option value that has this shape `Options Manual development|Biodiversity monitoring tool development|` 
the changes added in this commit fix this corner data case
PS: reverted this change https://github.com/akvo/akvo-lumen/pull/2966
=> [#2964] Remove empty option value

backend/src/akvo/lumen/lib/aggregation/bar.clj
Example viz showing proper count vs [dark-demo issue](https://dark-demo.akvolumen.org/visualisation/5f8841c5-9226-4dc7-b2e2-271ec3571e5d)
=> [#2964] Use count(*) instead of count(col_name)

.semaphore/semaphore.yml
* Authenticate with the credentials already defined in SemaphoreCI
Docs: https://docs.semaphoreci.com/ci-cd-environment/docker-authentication/#how-to-authenticate-docker-pulls
Closes #2997
=> [#2997] Docker Hub authentication as part of the build process

client/src/containers/Dataset.jsx
Fixing classical view. So setting rowsCount on data-groups=false
before the change
After the change rows are shown
=> [#3007] Adapt logic to classic dataset view

NEW_TENANT.md, backend/resources/akvo/lumen/prod.edn, backend/src/akvo/lumen/admin/add_tenant.clj, backend/src/akvo/lumen/admin/db.clj, backend/src/akvo/lumen/admin/remove_tenant.clj, backend/test/akvo/lumen/admin/db_test.clj
- Add a [config-adapter](https://github.com/akvo/akvo-lumen/pull/3032/files?file-filters%5B%5D=.clj&file-filters%5B%5D=.edn#diff-c64b11f481cc621606409b80009a080ba39863225c4293d755ae743b56a08795R9) admin component to reuse current `LUMEN_DB_URL` env var
- Adapt add-tenant and remove-tenant scripts
- docs updated => https://github.com/akvo/akvo-lumen/blob/e3c4670103060c5902971624ffd971e9bf1f6372/NEW_TENANT.md
Relates #3031 
tested locally (tenant:tangrammer)
=> [#3031] Adapt admin scripts to be executed with kubectl

client/src/utilities/dataset.js
In previous iterations the `repeatable` property was set in the
column, now we have it at group level, in the 3rd position:
```
["<group-name">, [<columns definition>], <is_repeatable>, [...]]
```
Example:
```
["group name", [{col1},{col2},{col2}], true]
```
Closes #2748
=> [#2748] Use new property to set a repeatable icon

backend/src/akvo/lumen/lib/transformation/engine.clj
Using set/difference we lost the original columns order
previous result (derived column is "test combine column")
result with this PR changes (order is preserved and new derived column is places at the end)
=> [#3036] Preserve columns order after transformation

backend/src/akvo/lumen/lib/transformation/derive.clj, backend/test/akvo/lumen/lib/transformation/derive_test.clj
so backend could work with:  
`Main` or `main`
`Transformations` or `transformations`
`Metadata` or `metadata`
=> [#3092] Adapt backend to uppercase default groups

client/src/components/dataset/ColumnHeader.jsx, client/src/components/dataset/DatasetTable.jsx, client/src/components/dataset/DatasetTableV2.jsx, client/src/containers/Dataset.jsx
Thus, on the contrary we'll have in transformatios group every column
with the icon
to avoid https://github.com/akvo/akvo-lumen/issues/2740#issuecomment-654152490
=> [#2740] Only show icon if data-groups flag

backend/specs/akvo/lumen/specs/transformation.clj, backend/src/akvo/lumen/lib/transformation/derive.clj, backend/src/akvo/lumen/lib/transformation/derive/js_engine.clj, backend/src/akvo/lumen/util.clj, client/src/components/dataset/sidebars/DeriveColumnJavascript.jsx
- Now js derivation can output a `option` type column too
- added js function: `akvoMultipleToMultiple(valuesToKeep, uncategorizedValue, v)`
eg: `akvoMultipleToMultiple(['opt1','opt2'], 'others', row['col title'])`
=> [#3110] Add support for multiple to multiple using js derivation

backend/src/akvo/lumen/db/dataset.clj, backend/src/akvo/lumen/lib/dataset.sql, backend/src/akvo/lumen/lib/import/common.clj, backend/src/akvo/lumen/lib/transformation/engine.clj, backend/src/akvo/lumen/lib/transformation/merge_datasets.clj, backend/test/akvo/lumen/lib/transformation_test.clj, backend/test/resources/names.csv
Current functionality
FLOW-source FLOW-target
New functionality added
FLOW-source - CSV-target
CSV-source  - CSV-target
CSV-source  - FLOW-target
When you merge into a flow dataset then you get a new data-group, but
if you merge into a csv dataset you keep the new columns into the same data-group
=> Add CSV merge-dataset with data-groups support

backend/src/akvo/lumen/lib/aggregation.clj, backend/src/akvo/lumen/lib/aggregation/commons.clj, backend/src/akvo/lumen/lib/data_group.clj, backend/test/akvo/lumen/lib/data_group_test.clj
This approach is to use temporary and dynamic db views for all aggregations but map types.
Using specs to extrac col-names from aggregation query payload (Follows same auth approach https://github.com/akvo/akvo-lumen/blob/master/backend/src/akvo/lumen/lib/auth.clj#L215-L231) we derive the data-groups used in the aggregation and then build a temp view (previously we changed temp views to persisted views thus map aggregations needs to be called from external windshaft service) 
Map aggregations keeps the same (persistent and complete dataset db views) ... perhaps we'd need to change the approach in the future too
=> [#3158] Aggregation temp views (except map types)
